### ISSUE TITLE
az interactive fails: No module named 'prompt_toolkit.interface'

### ISSUE THREAD

**Issue by doodlemania2** [Azure/azure-cli#10200]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/interactive/custom.py, ln 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Linux-4.15.0-1052-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.70

Extensions:
interactive 0.4.1

```

**Comment by jdoof** [comment]
getting this issue also

**Comment by jiasli** [comment]
This is a duplication of #10088. We have fixed it in 2.0.71 and will release it on 2019-08-13. See https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/HISTORY.rst

**Comment by JJussi** [comment]
Same error here at Bash CLI

**Comment by jiasli** [comment]
Fixed in 2.0.71.

**Comment by 2ps** [comment]
Please reopen, this still occurs on 2023-09-10.  

```
azure-cli                         2.51.0 *

core                              2.51.0 *
telemetry                          1.1.0

Extensions:
interactive                        0.5.3

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/u/upholstery/bin/python3.8'
Extensions directory '/home/2ps/.azure/cliextensions'

Python (Linux) 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0]```

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal```

python 3.8.10

**Comment by bebound** [comment]
@2ps I can't repro
It appears that you're installing cli by pypi, it might be a dependency conflict.
Please see https://github.com/Azure/azure-cli/issues/10200#issuecomment-519742492. You can also try the deb package.
