### ISSUE TITLE
Issue with ubuntu apt repo on Azure Pipelines hosted ubuntu-latest (xenial)

### ISSUE THREAD

**Issue by lvlie** [Azure/azure-cli#11786]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
As of today I am receiving:
```
Get:37 https://packages.microsoft.com/repos/azure-cli xenial/main amd64 Packages [39.5 kB]
Err:37 https://packages.microsoft.com/repos/azure-cli xenial/main amd64 Packages
  Writing more data than expected (40278 > 39457)
```

When trying to install a random package on an "ubuntu-latest" Microsoft hosted Azure pipeline host (e.g. "sudo apt update && sudo apt install qemu"). Not sure if this is an issue with the repo or with the Azure pipeline host itself. 

**To Reproduce**
sudo apt update && sudo apt install qemu (also after apt-get clean)

**Expected behavior**
Installing a package

**Environment summary**
apt using the official microsoft ubuntu repo (see above)

**Comment by h2floh** [comment]
Get it for xenial (16.04) and bionic (18.04) as well. There was an update to the packages just some hours ago, before it worked for me.

**Comment by bim-msft** [comment]
@fengzhou-msft Please take a look.

**Comment by K-Visscher** [comment]
We're also having the same error over here on xenial (16.04)
```
2020-01-07T08:25:44.9161012Z Err:61 https://packages.microsoft.com/repos/azure-cli xenial/main amd64 Packages
2020-01-07T08:25:44.9161683Z   Writing more data than expected (40278 > 39457)
2020-01-07T08:25:51.4358553Z E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/xenial/main/binary-amd64/Packages  Writing more data than expected (40278 > 39457)
2020-01-07T08:25:51.4360631Z E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by baruchiro** [comment]
Same in my Github Action:

https://github.com/baruchiro/israeli-bank-scrapers-desktop/runs/377085755

**Comment by prashantbhutani90** [comment]
Seeing the same in my project.

**Comment by fengzhou-msft** [comment]
We'are contacting internal teams to resolve this issue. Please download the package and install it locally for temp fix:
```
$curl -O https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.0.79-1~xenial_all.deb
$apt install ./azure-cli_2.0.79-1~xenial_all.deb 
```

**Comment by fengzhou-msft** [comment]
The repo gets updated correctly and it should work now.

**Comment by baruchiro** [comment]
> The repo gets updated correctly and it should work now.

Still failed:

https://github.com/baruchiro/israeli-bank-scrapers-desktop/runs/377185914#step:4:43

**Comment by fengzhou-msft** [comment]
> > The repo gets updated correctly and it should work now.
> 
> Still failed:
> 
> https://github.com/baruchiro/israeli-bank-scrapers-desktop/runs/377185914#step:4:43

bionic is also fixed. Please try again.

**Comment by lvlie** [comment]
Confirmed for xenial at least. I assume you will also fix the root cause to prevent further occurrences, but thats not for this issue of course 👍 

Thanks for the help!
