### ISSUE TITLE
az webapp up provides misleading information when invalid name is provided

### ISSUE THREAD

**Issue by sputnik13** [Azure/azure-cli#11884]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
Unable to retrieve details of the existing app mpae_webapp. Please check that the app is a part of the current subscription
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --resource-group {} --name {} --html`

## Expected Behavior
The error that is captured is incomplete, on the screen it gives

```
Webapp random_webapp already exists. The command will deploy contents to the existing app.
Unable to retrieve details of the existing app random_webapp. Please check that the app is a part of the current subscription
```

The first portion of that output is incorrect and misleading.  The error seems to be that underscore is not allowed in the name.  However, the error says that the instance exists instead.

## Environment Summary
```
Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.80
azure-cli-iot-ext 0.8.3

Extensions:
azure-cli-iot-ext 0.8.3

```

**Comment by panchagnula** [comment]
This means the app name you provided is already taken - must belong to some other subscription, so you need run with a different app name.

**Comment by panchagnula** [comment]
Should be fixed by siteName validation

**Comment by panchagnula** [comment]
@calvinsID this is the GitHub issue for checking if invalid site name is given to az webapp up.
For this please check this API https://docs.microsoft.com/en-us/rest/api/appservice/checknameavailability/checknameavailability#details
we already use this API, however we never look into the details & show a detailed error message, so check if we can make some changes here to fix this.

**Comment by frank-nankivell** [comment]
Bumping this, as still not resolved and continues to be confusing

```
WARNING: Webapp 'app-example' already exists. The command will deploy contents to the existing app.

ERROR: Unable to retrieve details of the existing app 'app-example'. Please check that the app is a part of the current subscription if updating an existing app. If creating a new app, app names must be globally unique. Please try a more unique name or leave unspecified to receive a randomly generated name.
```
