### ISSUE TITLE
How to list policy assignments applied to management group.

### ISSUE THREAD

**Issue by na2ko-ucym** [Azure/azure-cli#12089]
I try to list policy assignments applied to management group.
&gt; $ az policy assignment list --scope /managementGroups/management-group-id

However, I get this error.
&gt; usage error `--scope`: must be a fully qualified ARM ID.

Could you tell me how to get the list ?

For your reference, I can list policy assignment applied to subscriptions.
&gt; $ az policy assignment list --scope /subscriptions/subscription-id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6760bb-c278-da56-a95c-4e82e221f1e8
* Version Independent ID: e25cbd2a-b415-214f-7d50-c403992c9361
* Content: [az policy assignment](https://docs.microsoft.com/en-us/cli/azure/policy/assignment?view=azure-cli-latest#az-policy-assignment-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
HI @jiasli could you pls have a look? thanks.

**Comment by na2ko-ucym** [comment]
> For your reference, I can list policy assignment applied to subscriptions.
> > $ az policy assignment list --scope /subscriptions/subscription-id

I tried some pattern and found out that I can only list policy assignment applied to the current active subscription.

**Comment by yonzhan** [comment]
add to S166.

**Comment by zhoxing-ms** [comment]
@na2ko-ucym Hi, this is a known issue. It's the same problem as https://github.com/Azure/azure-cli/issues/9067 and the relevant team is repairing.

**Comment by zhoxing-ms** [comment]
@na2ko-ucym Hello, this issue has been fixed in the latest version of azure-cli (2.2.0), please download the latest version of the package to try. 
If there are any questions, please feel free to give us feedback~

**Comment by Wiszanyel** [comment]
This issue is not fixed:

![image](https://github.com/Azure/azure-cli/assets/74936319/c8640633-ff82-4ca8-8fe0-cb290aecd3d0)

**Comment by flederflick** [comment]
@Wiszanyel 
Use the complete ID
`az policy assignment list --scope /providers/Microsoft.Management/managementGroups/<management group id>`
