### ISSUE TITLE
`az account list -o tables` shows TenantID but not SubscriptionID

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1257]
```
$ az account list -o table

State    TenantId                                IsDefault  Name                                             CloudName
-------  ------------------------------------  -----------  -----------------------------------------------  -----------
[data omitted]
```

Subscription ID should be listed. I'd rather copy/paste the subscription ID than the subscription name that have spaces in them.

**Comment by yugangw-msft** [comment]
`list` needs customized table field list

**Comment by derekbekoe** [comment]
Table can be customized with `--query`.
In this case:
```
$ az account list -otable --query '[].{subscriptionId: id, name: name, isDefault: isDefault, tenantId: tenantId, state: state, cloudName: cloudName}'
```

Still, if we want subscription id in table output by default, we can do that 👍

**Comment by colemickens** [comment]
>Still, if we want subscription id in table output by default, we can do that 👍

Yes, absolutely. Especially since the last time I tried... `az account set --name="Some name with spaces"` it just didn't work.

**Comment by yugangw-msft** [comment]
>az account set --name="Some name with spaces"

This should work now with `az account set  --subscription  "Some name with spaces"`.

**Comment by squillace** [comment]
subid is always more useful in this command than tenanted. 

0.1.0b11: 

I still get tenantId.
