### ISSUE TITLE
`az functionapp create` for .NET Core 3.1 on Linux  fails

### ISSUE THREAD

**Issue by sixeyed** [Azure/azure-cli#12622]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 
`az version`:  
"azure-cli": "2.2.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.2.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "interactive": "0.4.3"
  }

**Describe the bug**
Creating a function app for an existing app plan & storage account, using Linux consumption plan for a .NET Core 3.1 app fails with the error: `The parameter LinuxFxVersion has an invalid value`.

Confirmed the region is valid for consumption plan, and using a dedicated resource group with no other resources. I've tried various combinations of versions but can't find a winning combination.
 Creating the function app with the same setup in the portal works correctly.

**To Reproduce**

- create new RG
- create new storage account
- create function app plan

Run:

```
  az functionapp create \
    --resource-group $FUNCTION_RESOURCE_GROUP \
    --consumption-plan-location $AZURE_REGION \
    --name $FUNCTION_APP_NAME \
    --os-type Linux \
    --functions-version 3 \
    --runtime dotnet \
    --runtime-version 3 \
    --storage-account $STORAGE_ACCOUNT_NAME
```

**Expected behavior**
New function app created.

**Environment summary**
Bash on Cloud Shell.

**Additional context**

**Comment by yungezz** [comment]
thanks for reporting, will look at it

**Comment by anthonychu** [comment]
This should be fixed with #12577

**Comment by GeeWee** [comment]
Just want to chime in that I've tried this locally with the az cli as well, and I also cannot deploy any dotnet functions. It does not matter if you specify functions version, runtime version or anything like that.

**Comment by pascalnaber** [comment]
This bug is still happening with the latest version of the az cli (2.3.1)

az functionapp create --name test --consumption-plan-location westeurope --os-type Linux --functions-version 3 --resource-group test --runtime 
dotnet --storage-account /subscriptions/xxxxx/resourceGroups/test-data-dev/providers/Microsoft.Storage/storageAccounts/testdev

The parameter LinuxFxVersion has an invalid value.

**Comment by stmax82** [comment]
I ran into this problem today. It seems to be gone after upgrading to 2.4.0.
(Don't upgrade to 2.5.0, this is completely broken for me.. some problem with iot extensions)

**Comment by fabiocav** [comment]
@anthonychu @gzuber flagging this for review.

**Comment by anthonychu** [comment]
@gzuber Can you please confirm if this has been fixed? Thanks.

**Comment by gzuber** [comment]
Yes, this has been fixed in 2.4.0 with https://github.com/Azure/azure-cli/pull/12817. You can see the release notes [here](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#appservice-1). This can be closed (which I can't do :( ) @anthonychu can you close this?

**Comment by anthonychu** [comment]
I can't close this either. @fabiocav Can you close?
