### ISSUE TITLE
"az monitor log-analytics workspace --help" fail in azdev

### ISSUE THREAD

**Issue by daxianji007** [Azure/azure-cli#13024]
## Describe the bug

**Command Name**
`az monitor log-analytics workspace`

**Errors:**
```
cannot import name 'SkuNameEnum' from 'azure.mgmt.loganalytics.models' (e:\repos\azure-cli\venv\lib\site-packages\azure\mgmt\loganalytics\models\__init__.py)
Traceback (most recent call last):
lib\site-packages\knack\cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli\core\commands\__init__.py, ln 572, in execute
    parsed_args = self.parser.parse_args(args)
lib\site-packages\knack\parser.py, ln 260, in parse_args
    return super(CLICommandParser, self).parse_args(args)
...
command_modules\monitor\operations\log_analytics_workspace.py, ln 5, in <module>
    from azure.mgmt.loganalytics.models import SkuNameEnum
ImportError: cannot import name 'SkuNameEnum' from 'azure.mgmt.loganalytics.models' (e:\repos\azure-cli\venv\lib\site-packages\azure\mgmt\loganalytics\models\__init__.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Clone azure-cli repo (master branch) and type the cmds:
- `virtualenv --no-site-packages venv`
- `.\venv\Scripts\activate`
- `python -m pip install pywin32==225 azdev`
- `python -m azdev setup -c`
- `az monitor log-analytics workspace --help`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.7.4
Installer: PIP

azure-cli 2.3.1

```

**Comment by daxianji007** [comment]
**And If I clone the dev branch this is error would not happen.**

**Comment by yungezz** [comment]
HI @MyronFanQiu could you pls help to have a look? thanks

**Comment by colbylwilliams** [comment]
This is also causing `azdev linter` to fail with same error with attempting to lint extensions.

**Comment by MyronFanQiu** [comment]
@colbylwilliams cloning the latest dev branch and running 'azdev setup' should solve the issue.

**Comment by daxianji007** [comment]
@MyronFanQiu Can you drive to merge the related code from dev to master and release new packages? If I install the azure-cli package (instead of 'azdev setup') directly, this still happen. 

It is blocking the CLI document generation.

**Comment by MyronFanQiu** [comment]
One dependency package `azure-mgmt-loganalytic` has released a new version 0.3.0 on 4.9. There is a breaking change in it. We locked the version to 0.2 instead of 0.2.0. We have fixed it in our dev branch in 4.10. We're discussing about cherry-picking the fix to master branch right now.

**Comment by jsntcy** [comment]
As CLI will release new version next Tuesday and we'll merge dev into master at that time and the issue should be resolved at that time.

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171

**Comment by MyronFanQiu** [comment]
This should be solved.
