### ISSUE TITLE
'Off' is suddenly marked as an invalid value for '--public-access'

### ISSUE THREAD

**Issue by HermanCordes** [Azure/azure-cli#13373]
On every deployment we use the following Azure CLI script to create a container without public access:

```
az storage container create `
    --name $containerName `
    --account-key $accessKey `
    --account-name $storageAccountName `
    --public-access "off" `
    --subscription $subscriptionId `
    --fail-on-exist
```

Since today it fails with this error message:

> The value for one of the HTTP headers is not in the correct format. ErrorCode: InvalidHeaderValue
&lt;?xml version="1.0" encoding="utf-8"?&gt;&lt;Error&gt;&lt;Code&gt;InvalidHeaderValue&lt;/Code&gt;&lt;Message&gt;The value for one of the HTTP headers is not in the correct format.
> RequestId:XYZ
> Time:2020-05-07T05:49:34.9297306Z&lt;/Message&gt;&lt;HeaderName&gt;x-ms-blob-public-access&lt;/HeaderName&gt;&lt;HeaderValue&gt;off&lt;/HeaderValue&gt;&lt;/Error&gt;

It fails for multiple deployments through Azure DevOps hosted agents, but also when executed manually through Azure Cloud Shell. I don't see any notice that this value isn't supported anymore. What could be the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcba5ed-e693-6345-2c1b-c17422d7b8f9
* Version Independent ID: 58297400-b777-6868-1687-0af3a512a16f
* Content: [az storage container](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az-storage-container-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by Juliehzl** [comment]
@HermanCordes It should be a server error and it is fixed already. 
Could you try again?

**Comment by XinRedhat** [comment]
@Juliehzl the error still is there. 
$ az storage container create -n $BLOB_CONTAINER --public-access off --account-name $AZURE_STORAGE_ACCOUNT_ID
No connection string, account key or sas token found, we will query account keys for your storage account. Please try to use --auth-mode login or provide one of the following parameters: connection string, account key or sas token for your storage account.
The value for one of the HTTP headers is not in the correct format. ErrorCode: InvalidHeaderValue
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
RequestId:1ea970ba-501e-0048-67b5-258c8c000000
Time:2020-05-09T03:54:28.4005561Z</Message><HeaderName>x-ms-blob-public-access</HeaderName><HeaderValue>off</HeaderValue></Error>

**Comment by XinRedhat** [comment]
the issue still is there.
`$ az storage container create -n $BLOB_CONTAINER --public-access off --account-name $AZURE_STORAGE_ACCOUNT_ID --account-key $ACCOUNT_KEY`
```
 The value for one of the HTTP headers is not in the correct format. ErrorCode: InvalidHeaderValue
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
RequestId:5454f952-b01e-006c-76ba-253fe5000000
Time:2020-05-09T04:26:58.2070734Z</Message><HeaderName>x-ms-blob-public-access</HeaderName><HeaderValue>off</HeaderValue></Error>
```

**Comment by HermanCordes** [comment]
@Juliehzl I've confirmed the issue still exist today. I've tested on an Azure DevOps pipeline with the AzureCLI task running on an ubuntu-latest agent. See error message below.

> ##[error]The value for one of the HTTP headers is not in the correct format. ErrorCode: InvalidHeaderValue
> ##[error]<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
> ##[error]RequestId:861f7107-101e-0011-6a56-275897000000
> ##[error]Time:2020-05-11T05:42:14.2663151Z</Message><HeaderName>x-ms-blob-public-access</HeaderName><HeaderValue>off</HeaderValue></Error>
> ##[error]Script failed with exit code: 1
