### ISSUE TITLE
--source "$web" --account-name zero360staging

### ISSUE THREAD

**Issue by Lloydkwena** [Azure/azure-cli#13728]
## Describe the bug

**Command Name**
`az storage blob delete-batch`

**Errors:**
```
missing parameter container
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 709, in _run_job
    cmd_copy.exception_handler(ex)
...
command_modules/storage/operations/blob.py, ln 492, in storage_blob_delete_batch
    source_blobs = list(collect_blob_objects(client, source_container_name, pattern))
cli/command_modules/storage/util.py, ln 26, in collect_blob_objects
    raise ValueError('missing parameter container')
ValueError: missing parameter container
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob delete-batch --source {} --account-name {} --output {}`

## Environment Summary
```
Linux-4.15.0-101-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9
Installer: 

azure-cli 2.6.0

```

**Comment by yonzhan** [comment]
add to S171

**Comment by Lloydkwena** [comment]
Super cool, thanks.

**Comment by Juliehzl** [comment]
Hi @Lloydkwena, you need to add `\` for `$`. Here you need to use `"\$web"` for source parameter.

**Comment by yonzhan** [comment]
@Lloydkwena, was your issue resolved by above solution?

**Comment by Lloydkwena** [comment]
Hi @yonzhan

Apologies for late response. It did, thanks

**Comment by kirun141** [comment]
I am writing a groovy script for the automatic deployment i am having the similar issue but it still throws me the error as in the context of this ticket.
Sample of the script is here
'''az storage blob delete-batch -s "\$web" --account-name ''' + AZURE_STORAGE_ACCOUNT_NAME_DEV + ''' --account-key ''' + AZURE_STORAGE_ACCOUNT_KEY_DEV 

any issues with the above command
