### ISSUE TITLE
Remove IP Filter from Cosmos DB via Azure CLI does not work

### ISSUE THREAD

**Issue by Craigmeister68** [Azure/azure-cli#15291]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
We are migrating from firewall to using VNET using this document: 
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-vnet-service-endpoint#migrate-from-firewall-to-vnet

Step 5 is "Remove the IP firewall rule for the subnet from the Azure Cosmos DB account's Firewall rules."

However, when attempting to do this using Azure CLI, I get the error:
ArgumentParseError: argument --ip-range-filter: expected at least one argument

I do not see any other Azure CLI method to remove IP Firewall.

**To Reproduce**
az cosmosdb update -n 'database account name' -g 'resource group name' --ip-range-filter '’ 

**Expected behavior**
Remove the IP range filter. 

**Environment summary**

**Comment by MehaKaushik** [comment]
Hey @Craigmeister68 thanks for reporting this. Let me debug this. As a temporary work around you can use Powershell module Az.CosmosDB to do the same.

**Comment by shurd** [comment]
I am adding a fix that will allow an empty string to reset ip rules on an account via the command line. For the particular issue you are seeing, I believe this is a powershell issue where it does not recognize "" as a valid parameter. @yungezz, do you know if there is a workaround for supplying an empty/null string via powershell?

**Comment by Craigmeister68** [comment]
Using PowerShell command is the current workaround for this issue with Azure CLI.

**Comment by shurd** [comment]
Hi, by powershell, I mean the shell used to execute the "az cosmosdb update" command, not the powershell modules. Running the command in powershell versus command prompt yields different results because of how they handle the empty string.

**Comment by shurd** [comment]
We are still waiting for the PR to be reviewed, but it should be in the next CLI release.

**Comment by shurd** [comment]
Fixed in 2.14.0. It will work to use an empty string in command prompt, but Powershell shell does not handle empty strings

**Comment by DominiqueClaes** [comment]
Can you provide an example how this would work with Azure CLI? I still get the message 'argument --ip-range-filter: expected at least one argument' while I have version 2.27.2 for Azure CLI.
