### ISSUE TITLE
Webapp:Setting connection string from file

### ISSUE THREAD

**Issue by kmadof** [Azure/azure-cli#15395]
**Is your feature request related to a problem? Please describe.**
I want to be able to sync settings between slots. On of the part is to set connection strings from file as it is possible with app settings ('az webapp config appsettings set')

**Describe the solution you'd like**
I want to be able to run this command:

`az webapp config connection-string set --name hadar --resource-group TheCodeManual --settings "@con.json"`
where `con.json` is a file like:
```json
[
  {
    "name": "Deault",
    "slotSetting": false,
    "type": "SQLAzure",
    "value": "<RealConnectionString>"
  }
]
```

**Describe alternatives you've considered**
I can parse file in powershell and set connection string one by one.

**Additional context**
I wanted to check if this is possible even if it is not clearly stated in [documentation](https://docs.microsoft.com/en-us/cli/azure/webapp/config/connection-string?view=azure-cli-latest#az_webapp_config_connection_string_set) (like it is for instance for `--slot-settings`

![image](https://user-images.githubusercontent.com/1680172/94987740-d8fb0800-0568-11eb-8edd-d74e54de8c4a.png)

However, command stuck for more than 15 minutes and I had to break it. I checked portal bot all values remained as they were.

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by guestdj** [comment]
I was trying to achieve the same result as @kmadof, i.e. I wanted to set the value of deployment slot setting for a connection string using: `az webapp config connection-string set`

However it  worked for me when I supplied the following slot settings parameter , like so:
`az webapp config connection-string set --resource-group $(resourceGroup) --name $(appServiceName) --connection-string-type SQLAzure --settings web-db='$(stagingDBConnectionString)' --slot $(deploymentSlot) --slot-settings web-db=true`

**Comment by bbrandt** [comment]
Looks to still be broken even though there is an example here:
https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=cli#edit-connection-strings-in-bulk

```
az webapp config connection-string set --name app-my-app --settings "@connectionstrings-app-my-app.json"


the following arguments are required: --connection-string-type/-t
Examples from AI knowledge base:
az webapp config connection-string set --resource-group MyResourceGroup --name MyUniqueApp --connection-string-type mysql --settings mysql1='Server=myServer;Database=myDB;Uid=myUser;Pwd=myPwd;'
Add a mysql connection string.
az webapp config connection-string set --connection-string-type MySql --ids {ids} --settings mysql1='Server=myServer;Database=myDB;Uid=myUser;Pwd=myPwd;'
Update a web app's connection strings. (autogenerated)
https://docs.microsoft.com/en-US/cli/azure/webapp/config/connection-string#az_webapp_config_connection_string_set 
Read more about the command in reference docs
```

**Comment by bhaskar39** [comment]
Is there an update on this as I can still see the issue?

**Comment by seligj95** [comment]
reviewed. `--connection-string-type` should not be a required parameter. will follow up on this.

**Comment by RKSelvi** [comment]
This is still an issue. Just ran the command with JSON file and it is prompting for 

the following arguments are required: --connection-string-type/-t

**Comment by abezverkov** [comment]
Still an issue in the latest CLI.   Error:
the following arguments are required: --connection-string-type/-t

if providing the argument (which should be taken from the array in the file), the error is: 
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Edgaras91** [comment]
Is there really no fix for this yet? At least the docs should be updated.

**Comment by Edgaras91** [comment]
Here is my workaround while this is getting fixed:

```
$ConnectionStringsJson = ConvertFrom-Json $ConnectionStrings
for($i = 0; $i -lt $ConnectionStringsJson.Count; $i++)
{
	$settingName = $ConnectionStringsJson[$i].name
	$settingValue = $ConnectionStringsJson[$i].value

	az webapp config connection-string set --resource-group "rgname" --name "appname" --connection-string-type $ConnectionStringsJson[$i].type --settings "$settingName=""$settingValue"""
}
```

I needed this long-winded way for `""$settingValue"""` so the key vault reference string won't lose last bracket `(@Microsoft.KeyVault(VaultName=...;SecretName=...)` <=

**Comment by seligj95** [comment]
resolved by https://github.com/Azure/azure-cli/pull/27195

**Comment by seligj95** [comment]
Resolved by linked PR and now available in latest CLI version.

**Comment by Edgaras91** [comment]
> Resolved by linked PR and now available in latest CLI version.

Still not working. Command I run:
`az webapp config connection-string set --resource-group $StepAzureResourceGroupName --name $StepAzureAppServiceName --settings "@connectionStrings.json"`
Error I get: `argument --resource-group/-g: expected one argument`
