### ISSUE TITLE
DLL load failed while importing win32file: The specified module could not be found.

### ISSUE THREAD

**Issue by SenseiJoe** [Azure/azure-cli#17986]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

DLL load failed while importing win32file: The specified module could not be found.

**To Reproduce**

Any az command,
az --version, give no version or regular feedback.   I get...

DLL load failed while importing win32file: The specified module could not be found.
The command failed with an unexpected error. Here is the traceback:
DLL load failed while importing win32file: The specified module could not be found.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 223, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 125, in show_version
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 345, in get_az_version_string
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 332, in _get_local_versions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 256, in get_installed_cli_distributions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/telemetry/__init__.py", line 9, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/__init__.py", line 4, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/portalocker.py", line 9, in <module>
ImportError: DLL load failed while importing win32file: The specified module could not be found

**Expected behavior**

version information displayed

**Environment summary**

auto updated using windows MSI

**Additional context**

**Comment by turb0chrg** [comment]
Getting the same. Upgraded using chocolately from 2.20.0. I'm going to install 2.22.1 and see if that works since 2.23.0 was released today...

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by SenseiJoe** [comment]
Re-installed 2.22.1 and things all work better

**Comment by SenseiJoe** [comment]
Why is this closed?

**Comment by yonzhan** [comment]
I assumed that you issue was resolved by yourself? If not, I will reopen it. Sorry for the misunderstanding.

**Comment by pazdedav** [comment]
Same issue here. It is not just `az --version` command that fails, when I try e.g. `az group list -o table`, it first returns "DLL load failed while importing win32file: The specified module could not be found.", but after that it lists my resource groups correctly.

It seems there is something wrong with the build process and the way the packages are either referenced (paths with both types of slashes) or made available in the build agent:

```
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
```

**Comment by ryanbowden** [comment]
Same issue here :(

**Comment by aldodfm** [comment]
+1

**Comment by jiasli** [comment]
I am able to repo. It seems to be related to https://github.com/Azure/azure-cli/pull/17816, triggering https://github.com/mhammond/pywin32/issues/1431.

Investigating... 👨‍💻

**Comment by tirendra-reddy** [comment]
Not a problem, Thank you :) I will subscribe to that thread and follow it there.

**Comment by SenseiJoe** [comment]
I downgraded to solve the problem, it wasn't actually fixed.
@pazdedav is correct, it happens more than az --version.

**Comment by richardg1** [comment]
Same issue, not just a problem with az version. Uninstalling 2.23.0, installed 2.22.1 and working OK now.

**Comment by jiasli** [comment]
I was able to solve it by reinstalling `pywin32` with a terminal "Run as Administrator":

```
& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install pywin32==228 --force-reinstall
```

Though the root cause remains unknown...

**Comment by jiasli** [comment]
Unable to repro on a fresh Azure Virtual Machine:

![image](https://user-images.githubusercontent.com/4003950/117455528-d981d400-af79-11eb-852f-5a5656bfcca1.png)

**Comment by tirendra-reddy** [comment]
> I was able to solve it by reinstalling `pywin32` with a terminal "Run as Administrator":
> 
> ```
> & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install pywin32==228 --force-reinstall
> ```
> 
> Though the root cause remains unknown...

This fix worked for me. Thank you @jiasli!

**Comment by EvanMulawski** [comment]
@jiasli This worked for me.

Deleted `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2` and repaired the Azure CLI installation.

**Comment by dawwa** [comment]
Why is this closed? the issue still exists, I assume customer find a workaround does not mean the issue is fixed.

**Comment by thoemmi** [comment]
@dawwa I'd guess @jiasli closed this issue because it was fixed in #18012

**Comment by jiasli** [comment]
I am not able to precisely identify the root cause. Hopefully #18012 can fix it. 

Reinstalling is the official fix instead of a workaround. Thanks for understanding.

**Comment by tarockey** [comment]
When installing the CLI via python, uninstalling and reinstalling does not resolve this issue.

**Comment by oudajosefu** [comment]
> > I was able to solve it by reinstalling `pywin32` with a terminal "Run as Administrator":
> > ```
> > & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install pywin32==228 --force-reinstall
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Though the root cause remains unknown...
> 
> This fix worked for me. Thank you [@jiasli](https://github.com/jiasli)!

This worked for me but obviously after changing the relevant paths and versions to the correct and most recent values: `...\Program Files\...` for me and `pywin32==311`.

**Comment by asos-balazsszlovak** [comment]
> > > I was able to solve it by reinstalling `pywin32` with a terminal "Run as Administrator":
> > > ```
> > > & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install pywin32==228 --force-reinstall
> > > ```
> > > Though the root cause remains unknown...
> > 
> > 
> > This fix worked for me. Thank you [@jiasli](https://github.com/jiasli)!
> 
> This worked for me but obviously after changing the relevant paths and versions to the correct and most recent values: `...\Program Files\...` for me and `pywin32==311`.


this worked for me too to confirm
& "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install pywin32==311 --force-reinstall

**Comment by gsrit** [comment]
2025 and I had to face this , suddenly started facing this issue and landed here. Thanks @jiasli

**Comment by masquinyo** [comment]
I also found the issue for some reason. Thanks @jiasli your answer still helps!

**Comment by Rhman101** [comment]
I had this issue while updating the Azure CLI to the latest version. @jiasli's solution works, but I suspect the issue is not solved.
