### ISSUE TITLE
webapp:az webapp config hostname add fails 

### ISSUE THREAD

**Issue by therealradler** [Azure/azure-cli#18075]
### **This is autogenerated. Please review and update as needed.**

az webapp config hostname add fails with 
`Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'`

**Command Name**
`az webapp config hostname add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1426, in add_hostname
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/v2020_09_01/operations/_web_apps_operations.py", line 17868, in create_or_update_host_name_binding_slot
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 622, in body
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config hostname add --hostname {} --resource-group {} --slot {} --webapp-name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.23.0

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
@therealradler Thanks for your feedback. I am able to repro this issue. Will work on the fix.

**Comment by panchagnula** [comment]
Closing this since this has been fixed Please install latest version of CLI & re-try.

**Comment by hardboilr** [comment]
Still experiencing this issue on Azure-CLI 2.27.0.
Running this command: az webapp config hostname add --hostname $HostName --resource-group $ResourceGroupName --webapp-name $WebAppName --slot $SlotName

See full log below:

```
2021-08-06T10:47:32.7379599Z ##[section]Starting: Azure CLI: Add Custom Hostname to Slot
2021-08-06T10:47:32.7557238Z ==============================================================================
2021-08-06T10:47:32.7557556Z Task         : Azure CLI
2021-08-06T10:47:32.7558018Z Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
2021-08-06T10:47:32.7558460Z Version      : 2.1.1
2021-08-06T10:47:32.7558687Z Author       : Microsoft Corporation
2021-08-06T10:47:32.7558998Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2021-08-06T10:47:32.7559361Z ==============================================================================
2021-08-06T10:47:33.1338140Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2021-08-06T10:47:34.0476923Z 
2021-08-06T10:47:34.0479581Z azure-cli                         2.27.0
2021-08-06T10:47:34.0481054Z Please let us know how we are doing: https://aka.ms/azureclihats
2021-08-06T10:47:34.0481383Z 
2021-08-06T10:47:34.0482235Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2021-08-06T10:47:34.0482861Z core                              2.27.0
2021-08-06T10:47:34.0483662Z telemetry                          1.0.6
2021-08-06T10:47:34.0484035Z 
2021-08-06T10:47:34.0484503Z Extensions:
2021-08-06T10:47:34.0485111Z azure-devops                      0.18.0
2021-08-06T10:47:34.0485487Z 
2021-08-06T10:47:34.0486165Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2021-08-06T10:47:34.0487020Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2021-08-06T10:47:34.0487510Z 
2021-08-06T10:47:34.0488182Z Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
2021-08-06T10:47:34.0488694Z 
2021-08-06T10:47:34.0489306Z Legal docs and information: aka.ms/AzureCliLegal
2021-08-06T10:47:34.0489981Z 
2021-08-06T10:47:34.0490277Z 
2021-08-06T10:47:34.0490810Z Your CLI is up-to-date.
2021-08-06T10:47:34.0509506Z Setting AZURE_CONFIG_DIR env variable to: D:\a\_temp\.azclitask
2021-08-06T10:47:34.0534397Z Setting active cloud to: AzureCloud
2021-08-06T10:47:34.0724898Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
2021-08-06T10:47:34.6158832Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** "--password=***" --tenant *** --allow-no-subscriptions"
2021-08-06T10:47:35.7790980Z [
2021-08-06T10:47:35.7791740Z   {
2021-08-06T10:47:35.7792172Z     "cloudName": "AzureCloud",
2021-08-06T10:47:35.7792744Z     "homeTenantId": "***",
2021-08-06T10:47:35.7793182Z     "id": "cfb3e226-ce0a-434e-8271-7c1f1d5e0651",
2021-08-06T10:47:35.7793634Z     "isDefault": true,
2021-08-06T10:47:35.7793973Z     "managedByTenants": [],
2021-08-06T10:47:35.7794274Z     "name": "Visual Studio Professional",
2021-08-06T10:47:35.7794548Z     "state": "Enabled",
2021-08-06T10:47:35.7794874Z     "tenantId": "***",
2021-08-06T10:47:35.7795126Z     "user": {
2021-08-06T10:47:35.7800211Z       "name": "***",
2021-08-06T10:47:35.7800771Z       "type": "servicePrincipal"
2021-08-06T10:47:35.7801036Z     }
2021-08-06T10:47:35.7801239Z   }
2021-08-06T10:47:35.7801415Z ]
2021-08-06T10:47:35.8110749Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account set --subscription cfb3e226-ce0a-434e-8271-7c1f1d5e0651"
2021-08-06T10:47:36.3538829Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1628246853078.ps1'"
2021-08-06T10:47:36.7490609Z Resource-type: 
2021-08-06T10:47:36.7509402Z Adding custom host-name: [sc-sandbox-qa-cd-1.apoteket-online.dk], Deploy-slot: [staging], Webapp: [sc-qa-cd-webapp-1], Resource-grp: [sc-sandbox-1].
2021-08-06T10:47:36.7543668Z Adding to slot
2021-08-06T10:47:38.1176248Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-08-06T10:47:38.1208466Z ERROR: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
2021-08-06T10:47:38.1209810Z Traceback (most recent call last):
2021-08-06T10:47:38.1210545Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
2021-08-06T10:47:38.1211579Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
2021-08-06T10:47:38.1212642Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
2021-08-06T10:47:38.1213520Z AttributeError: 'str' object has no attribute 'get'
2021-08-06T10:47:38.1213813Z 
2021-08-06T10:47:38.1214354Z During handling of the above exception, another exception occurred:
2021-08-06T10:47:38.1214703Z 
2021-08-06T10:47:38.1215150Z Traceback (most recent call last):
2021-08-06T10:47:38.1215893Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
2021-08-06T10:47:38.1216715Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
2021-08-06T10:47:38.1217517Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
2021-08-06T10:47:38.1218446Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
2021-08-06T10:47:38.1219244Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
2021-08-06T10:47:38.1219867Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
2021-08-06T10:47:38.1220504Z msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
2021-08-06T10:47:38.1220806Z 
2021-08-06T10:47:38.1221131Z During handling of the above exception, another exception occurred:
2021-08-06T10:47:38.1221337Z 
2021-08-06T10:47:38.1221591Z Traceback (most recent call last):
2021-08-06T10:47:38.1222012Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
2021-08-06T10:47:38.1222530Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
2021-08-06T10:47:38.1223122Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2021-08-06T10:47:38.1223704Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
2021-08-06T10:47:38.1224287Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
2021-08-06T10:47:38.1224832Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
2021-08-06T10:47:38.1225406Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
2021-08-06T10:47:38.1225989Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
2021-08-06T10:47:38.1227042Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1433, in add_hostname
2021-08-06T10:47:38.1227835Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/v2020_09_01/operations/_web_apps_operations.py", line 17868, in create_or_update_host_name_binding_slot
2021-08-06T10:47:38.1228660Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 622, in body
2021-08-06T10:47:38.1229224Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
2021-08-06T10:47:38.1229772Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
2021-08-06T10:47:38.1230310Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
2021-08-06T10:47:38.1230846Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
2021-08-06T10:47:38.1231395Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
2021-08-06T10:47:38.1231980Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
2021-08-06T10:47:38.1232600Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
2021-08-06T10:47:38.1233453Z msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
2021-08-06T10:47:38.1855358Z To open an issue, please run: 'az feedback'
2021-08-06T10:47:38.4614739Z ##[error]Script failed with exit code: 1
2021-08-06T10:47:38.4701953Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
2021-08-06T10:47:39.1214265Z ##[section]Finishing: Azure CLI: Add Custom Hostname to Slot
```

**Comment by panchagnula** [comment]
@Kotasudhakarreddy could you validate this still fails on slot with the latest CLI version? Thanks!

**Comment by hardboilr** [comment]
Yes. As mentioned in post, I'm running 2.27.0 which is currently the latest and its against a deploy-slot.

**Comment by Kotasudhakarreddy** [comment]
I am unable to repro the issue. Find the below image for details.

![image](https://user-images.githubusercontent.com/60102891/128676857-b7cac23d-fe4a-44eb-9f05-d02e6c07ce23.png)

**Comment by hardboilr** [comment]
What happens when you do it against a deploy-slot?

**Comment by Kotasudhakarreddy** [comment]
@panchagnula Yes the issue is reproable against a Slot

**Comment by panchagnula** [comment]
> @panchagnula Yes the issue is reproable against a Slot

Thanks can

**Comment by hardboilr** [comment]
Still getting same error on Azure CLI 2.27.2

2021-09-08T10:30:25.3483592Z ##[section]Starting: Azure CLI: Add Custom Hostname to Slot
2021-09-08T10:30:25.3613157Z ==============================================================================
2021-09-08T10:30:25.3613719Z Task         : Azure CLI
2021-09-08T10:30:25.3614482Z Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
2021-09-08T10:30:25.3615230Z Version      : 2.1.1
2021-09-08T10:30:25.3615646Z Author       : Microsoft Corporation
2021-09-08T10:30:25.3616229Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2021-09-08T10:30:25.3616869Z ==============================================================================
2021-09-08T10:30:26.3307548Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2021-09-08T10:30:27.0653487Z 
2021-09-08T10:30:27.0654562Z azure-cli                         2.27.2
2021-09-08T10:30:27.0655786Z Please let us know how we are doing: https://aka.ms/azureclihats
2021-09-08T10:30:27.0656161Z 
2021-09-08T10:30:27.0657067Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2021-09-08T10:30:27.0657856Z core                              2.27.2
2021-09-08T10:30:27.0658751Z telemetry                          1.0.6
2021-09-08T10:30:27.0659239Z 
2021-09-08T10:30:27.0659800Z Extensions:
2021-09-08T10:30:27.0660434Z azure-devops                      0.20.0
2021-09-08T10:30:27.0660788Z 
2021-09-08T10:30:27.0661482Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2021-09-08T10:30:27.0662338Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2021-09-08T10:30:27.0662781Z 
2021-09-08T10:30:27.0663516Z Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
2021-09-08T10:30:27.0663992Z 
2021-09-08T10:30:27.0664633Z Legal docs and information: aka.ms/AzureCliLegal
2021-09-08T10:30:27.0665044Z 
2021-09-08T10:30:27.0665318Z 
2021-09-08T10:30:27.0665888Z Your CLI is up-to-date.
2021-09-08T10:30:27.0678026Z Setting AZURE_CONFIG_DIR env variable to: D:\a\_temp\.azclitask
2021-09-08T10:30:27.0684276Z Setting active cloud to: AzureCloud
2021-09-08T10:30:27.0817042Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
2021-09-08T10:30:27.5508839Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** "--password=***" --tenant *** --allow-no-subscriptions"
2021-09-08T10:30:28.6336167Z [
2021-09-08T10:30:28.6337051Z   {
2021-09-08T10:30:28.6337706Z     "cloudName": "AzureCloud",
2021-09-08T10:30:28.6338565Z     "homeTenantId": "***",
2021-09-08T10:30:28.6339338Z     "id": "a9285634-5b2d-4b9d-827f-6b849e281ce6",
2021-09-08T10:30:28.6340086Z     "isDefault": true,
2021-09-08T10:30:28.6340758Z     "managedByTenants": [],
2021-09-08T10:30:28.6341438Z     "name": "Pay-As-You-Go",
2021-09-08T10:30:28.6342380Z     "state": "Enabled",
2021-09-08T10:30:28.6343140Z     "tenantId": "***",
2021-09-08T10:30:28.6343778Z     "user": {
2021-09-08T10:30:28.6344492Z       "name": "***",
2021-09-08T10:30:28.6345167Z       "type": "servicePrincipal"
2021-09-08T10:30:28.6345805Z     }
2021-09-08T10:30:28.6346371Z   }
2021-09-08T10:30:28.6346924Z ]
2021-09-08T10:30:28.6538339Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account set --subscription a9285634-5b2d-4b9d-827f-6b849e281ce6"
2021-09-08T10:30:29.1529883Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1631097026292.ps1'"
2021-09-08T10:30:29.5434057Z Resource-type: 
2021-09-08T10:30:29.5446452Z Adding custom host-name: [qa-preprc-stage.apoteket-online.dk], Deploy-slot: [staging], Webapp: [aa-qa-sc-prc], Resource-grp: [aa-qa-sc-resourcegrp].
2021-09-08T10:30:29.5471020Z Adding to slot
2021-09-08T10:30:31.1385759Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-09-08T10:30:31.1395670Z ERROR: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
2021-09-08T10:30:31.1397020Z Traceback (most recent call last):
2021-09-08T10:30:31.1397975Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
2021-09-08T10:30:31.1399082Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
2021-09-08T10:30:31.1400238Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
2021-09-08T10:30:31.1401218Z AttributeError: 'str' object has no attribute 'get'
2021-09-08T10:30:31.1401627Z 
2021-09-08T10:30:31.1402347Z During handling of the above exception, another exception occurred:
2021-09-08T10:30:31.1402808Z 
2021-09-08T10:30:31.1403854Z Traceback (most recent call last):
2021-09-08T10:30:31.1404720Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
2021-09-08T10:30:31.1405742Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
2021-09-08T10:30:31.1406700Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
2021-09-08T10:30:31.1407652Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
2021-09-08T10:30:31.1408670Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
2021-09-08T10:30:31.1409785Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
2021-09-08T10:30:31.1410857Z msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
2021-09-08T10:30:31.1411352Z 
2021-09-08T10:30:31.1411972Z During handling of the above exception, another exception occurred:
2021-09-08T10:30:31.1412333Z 
2021-09-08T10:30:31.1412855Z Traceback (most recent call last):
2021-09-08T10:30:31.1413614Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
2021-09-08T10:30:31.1414548Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
2021-09-08T10:30:31.1415582Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2021-09-08T10:30:31.1416807Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
2021-09-08T10:30:31.1417801Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
2021-09-08T10:30:31.1418812Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
2021-09-08T10:30:31.1419780Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
2021-09-08T10:30:31.1420767Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
2021-09-08T10:30:31.1422365Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1433, in add_hostname
2021-09-08T10:30:31.1423492Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/v2020_09_01/operations/_web_apps_operations.py", line 17868, in create_or_update_host_name_binding_slot
2021-09-08T10:30:31.1424568Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 622, in body
2021-09-08T10:30:31.1425516Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
2021-09-08T10:30:31.1426514Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
2021-09-08T10:30:31.1427445Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
2021-09-08T10:30:31.1428414Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
2021-09-08T10:30:31.1429396Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
2021-09-08T10:30:31.1430380Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
2021-09-08T10:30:31.1431420Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
2021-09-08T10:30:31.1432804Z msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
2021-09-08T10:30:31.1857997Z To open an issue, please run: 'az feedback'
2021-09-08T10:30:31.3438321Z ##[error]Script failed with exit code: 1
2021-09-08T10:30:31.3580126Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
2021-09-08T10:30:31.8370063Z ##[section]Finishing: Azure CLI: Add Custom Hostname to Slot

**Comment by Kotasudhakarreddy** [comment]
The current version of the Azure CLI is `2.28.0`. Please install and try it should work.
