### ISSUE TITLE
Can't create and assign a managed identity.

### ISSUE THREAD

**Issue by Dave-0-0** [Azure/azure-cli#18220]
## No identity is created. An error is produced instead. Attempting to follow the tutorial at "https://docs.microsoft.com/en-us/azure/key-vault/general/tutorial-net-create-vault-azure-web-app"  I have tried this with both PowerShell and Bash in the Azure portal.

**Command Name**
`az webapp identity assign`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'identity'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 789, in assign_identity
    webapp = _assign_identity(cmd.cli_ctx, getter, setter, role, scope)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 706, in assign_identity
    resource = setter(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 761, in setter
    if webapp.identity and webapp.identity.type == ResourceIdentityType.system_assigned_user_assigned:
AttributeError: 'NoneType' object has no attribute 'identity'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp identity assign --name {} --resource-group {}`

## Expected Behavior

An identity is created per the tutorial. 

## Environment Summary
```
Linux-5.4.0-1047-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.23.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by divyanshumehta** [comment]
+1 facing this

**Comment by panchagnula** [comment]
Please use the latest version 2.24.0, this is fixed with this version.

**Comment by ransagy** [comment]
Although with a bit of a different error message, this is still broken for me.
