### ISSUE TITLE
Insufficient privileges when attaching acr to aks with managed identity enabled

### ISSUE THREAD

**Issue by khauser** [Azure/azure-cli#20559]
azure-cli                         2.30.0

I have created an aks with Managed Identity. The aks was installed without any problem. The following line also show that the manage identity creation and assignment seems to work.
```
klhauser@jkhausernb:/mnt/c/Users/khauser$ az aks show -g <our rg> -n <our aks name> --subscription <our aks subscription name> --query "servicePrincipalProfile"
{
  "clientId": "msi"
}
klhauser@jkhausernb:/mnt/c/Users/khauser$ az aks show -g <our rg> -n <our aks name> --subscription <our aks subscription name> --query "identity"
{
  "principalId": "fa2dc79c-2f2b-4970-86ed-de3b1bd8b889",
  "tenantId": "<our tenant id>",
  "type": "SystemAssigned",
  "userAssignedIdentities": null
}
```

Then I tried to attach an acr with the following command:
az aks update --debug -n $(aksName) -g $(aksResourceGroup) --attach-acr `az acr show -n $(registryName) --subscription $(registrySubscription) --query "id" -o tsv`

Debug log shows the following entries:
```
2021-11-30T12:46:46.2789421Z DEBUG: cli.knack.cli: Command arguments: ['aks', 'update', '--debug', '-n', '<our aks name>', '-g', '<our rg>', '--attach-acr', '/subscriptions/743a0c9d-3b7f-4667-818a-ac656fff69a8/resourceGroups/test-iste-common-northeurope/providers/Microsoft.ContainerRegistry/registries/ishisteacr']
2021-11-30T12:46:46.2825973Z DEBUG: cli.knack.cli: __init__ debug log:
2021-11-30T12:46:46.2827886Z Cannot enable color.
2021-11-30T12:46:46.2831684Z DEBUG: cli.knack.cli: Event: Cli.PreExecute []
2021-11-30T12:46:46.2842339Z DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fccffe1ec80>, <function OutputProducer.on_global_arguments at 0x7fccffd51730>, <function CLIQuery.on_global_arguments at 0x7fccffcdf840>]
2021-11-30T12:46:46.3110259Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
2021-11-30T12:46:46.3118171Z DEBUG: cli.azure.cli.core: Modules found from index for 'aks': ['azure.cli.command_modules.acs']
2021-11-30T12:46:46.3127920Z DEBUG: cli.azure.cli.core: Loading command modules:
2021-11-30T12:46:46.3145108Z DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
2021-11-30T12:46:46.4433479Z DEBUG: cli.azure.cli.core: acs                       0.128         8        53
2021-11-30T12:46:46.4438504Z DEBUG: cli.azure.cli.core: Total (1)                 0.128         8        53
2021-11-30T12:46:46.4448705Z DEBUG: cli.azure.cli.core: Loaded 8 groups, 53 commands.
2021-11-30T12:46:46.4455141Z DEBUG: cli.azure.cli.core: Found a match in the command table.
2021-11-30T12:46:46.4478419Z DEBUG: cli.azure.cli.core: Raw command  : aks update
2021-11-30T12:46:46.4488374Z DEBUG: cli.azure.cli.core: Command table: aks update
2021-11-30T12:46:46.4506074Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fccff7f10d0>]
2021-11-30T12:46:46.4548132Z DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/mnt/_temp/.azclitask/commands/2021-11-30.12-46-46.aks_update.9569.log'.
2021-11-30T12:46:46.4556612Z INFO: az_command_data_logger: command args: aks update --debug -n {} -g {} --attach-acr {}
2021-11-30T12:46:46.4563646Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fccff81b048>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7fccff77e7b8>]
2021-11-30T12:46:46.6957481Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
2021-11-30T12:46:46.6961963Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fccff77e840>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fccff77e950>]
2021-11-30T12:46:46.6998878Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
2021-11-30T12:46:46.7002931Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
2021-11-30T12:46:46.7023930Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fccffd517b8>, <function CLIQuery.handle_query_parameter at 0x7fccffcdf8c8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7fccff77e730>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fccff77e8c8>]
2021-11-30T12:46:46.7055082Z DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ContainerServiceClient
2021-11-30T12:46:46.7256276Z DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-11-30T12:46:46.7299229Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
2021-11-30T12:46:46.7706016Z DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "GET /***/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
2021-11-30T12:46:46.7713354Z DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/***/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/***/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/***/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
2021-11-30T12:46:46.7831666Z DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
2021-11-30T12:46:46.7836309Z DEBUG: cli.azure.cli.core.auth.msal_authentication: ServicePrincipalCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
2021-11-30T12:46:46.7849683Z DEBUG: msal.application: Cache hit an AT
2021-11-30T12:46:46.7853353Z DEBUG: msal.telemetry: Generate or reuse correlation_id: c67df809-5d5a-4073-bfdd-72e8703c93f3
2021-11-30T12:46:46.7865450Z DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/8f19e0c8-0a30-4511-83db-e718bb8eaf42/resourceGroups/<our rg>/providers/Microsoft.ContainerService/managedClusters/<our aks name>?api-version=2021-07-01'
2021-11-30T12:46:46.7904095Z DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
2021-11-30T12:46:46.7908182Z DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
2021-11-30T12:46:46.7912157Z DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
2021-11-30T12:46:46.7916329Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '93db717d-51db-11ec-8ba6-c953cb07150b'
2021-11-30T12:46:46.7919765Z DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'aks update'
2021-11-30T12:46:46.7924745Z DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug -n -g --attach-acr'
2021-11-30T12:46:46.7929688Z DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.30.0 (DEB) azsdk-python-azure-mgmt-containerservice/16.1.0 Python/3.6.10 (Linux-5.11.0-1021-azure-x86_64-with-debian-bullseye-sid) VSTS_28c253d8-c3c8-42d8-88a7-2cd371007686_build_70_0'
2021-11-30T12:46:46.7934711Z DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
2021-11-30T12:46:46.7938918Z DEBUG: cli.azure.cli.core.sdk.policies: Request body:
2021-11-30T12:46:46.7943430Z DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
2021-11-30T12:46:46.8005965Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
2021-11-30T12:46:47.3030524Z DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/8f19e0c8-0a30-4511-83db-e718bb8eaf42/resourceGroups/<our rg>/providers/Microsoft.ContainerService/managedClusters/<our aks name>?api-version=2021-07-01 HTTP/1.1" 200 None
2021-11-30T12:46:47.3031723Z DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
2021-11-30T12:46:47.3032259Z DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
2021-11-30T12:46:47.3033184Z DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
2021-11-30T12:46:47.3033880Z DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
2021-11-30T12:46:47.3034900Z DEBUG: cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
2021-11-30T12:46:47.3053532Z DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
2021-11-30T12:46:47.3054388Z DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
2021-11-30T12:46:47.3055088Z DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
2021-11-30T12:46:47.3055848Z DEBUG: cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
2021-11-30T12:46:47.3056864Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHEUROPE:20211130T124647Z:e556200a-15a7-4550-b271-4a4a785dc631'
2021-11-30T12:46:47.3057841Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11993'
2021-11-30T12:46:47.3058727Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'e556200a-15a7-4550-b271-4a4a785dc631'
2021-11-30T12:46:47.3059652Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '572a9e1d-f0f8-4671-8f04-625dec211286'
2021-11-30T12:46:47.3101200Z DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
2021-11-30T12:46:47.3129823Z DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
2021-11-30T12:46:47.3130730Z DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'nginx'
2021-11-30T12:46:47.3131591Z DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 30 Nov 2021 12:46:46 GMT'
2021-11-30T12:46:47.3132169Z DEBUG: cli.azure.cli.core.sdk.policies: Response content:
2021-11-30T12:46:47.3132612Z DEBUG: cli.azure.cli.core.sdk.policies: {
2021-11-30T12:46:47.3133683Z   "id": "/subscriptions/8f19e0c8-0a30-4511-83db-e718bb8eaf42/resourcegroups/<our rg>/providers/Microsoft.ContainerService/managedClusters/<our aks name>",
2021-11-30T12:46:47.3134256Z   "location": "northeurope",
2021-11-30T12:46:47.3134822Z   "name": "<our aks name>",
2021-11-30T12:46:47.3135346Z   "type": "Microsoft.ContainerService/ManagedClusters",
2021-11-30T12:46:47.3135761Z   "properties": {
2021-11-30T12:46:47.3136456Z    "provisioningState": "Succeeded",
2021-11-30T12:46:47.3137084Z    "powerState": {
2021-11-30T12:46:47.3137442Z     "code": "Running"
2021-11-30T12:46:47.3137700Z    },
2021-11-30T12:46:47.3138035Z    "kubernetesVersion": "1.20.7",
2021-11-30T12:46:47.3138722Z    "dnsPrefix": "<our aks name>",
2021-11-30T12:46:47.3139332Z    "fqdn": "<our aks name>-6ffe2300.hcp.northeurope.azmk8s.io",
2021-11-30T12:46:47.3140204Z    "azurePortalFQDN": "<our aks name>-6ffe2300.portal.hcp.northeurope.azmk8s.io",
2021-11-30T12:46:47.3140884Z    "agentPoolProfiles": [
2021-11-30T12:46:47.3141236Z     {
2021-11-30T12:46:47.3141503Z      "name": "initial",
2021-11-30T12:46:47.3141839Z      "count": 4,
2021-11-30T12:46:47.3142200Z      "vmSize": "Standard_D2s_v3",
2021-11-30T12:46:47.3142517Z      "osDiskSizeGB": 30,
2021-11-30T12:46:47.3142883Z      "osDiskType": "Ephemeral",
2021-11-30T12:46:47.3143621Z      "kubeletDiskType": "OS",
2021-11-30T12:46:47.3143985Z      "maxPods": 30,
2021-11-30T12:46:47.3144312Z      "type": "VirtualMachineScaleSets",
2021-11-30T12:46:47.3144770Z      "provisioningState": "Succeeded",
2021-11-30T12:46:47.3145160Z      "powerState": {
2021-11-30T12:46:47.3145451Z       "code": "Running"
2021-11-30T12:46:47.3145766Z      },
2021-11-30T12:46:47.3146110Z      "orchestratorVersion": "1.20.7",
2021-11-30T12:46:47.3146432Z      "mode": "System",
2021-11-30T12:46:47.3146780Z      "osType": "Linux",
2021-11-30T12:46:47.3147127Z      "osSKU": "Ubuntu",
2021-11-30T12:46:47.3147885Z      "nodeImageVersion": "AKSUbuntu-1804gen2containerd-2021.11.06",
2021-11-30T12:46:47.3148285Z      "enableFIPS": false
2021-11-30T12:46:47.3148604Z     }
2021-11-30T12:46:47.3148931Z    ],
2021-11-30T12:46:47.3149198Z    "linuxProfile": {
2021-11-30T12:46:47.3149562Z     "adminUsername": "localhorst",
2021-11-30T12:46:47.3149920Z     "ssh": {
2021-11-30T12:46:47.3150211Z      "publicKeys": [
2021-11-30T12:46:47.3150524Z       {
2021-11-30T12:46:47.3152101Z        "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy+OWyWG0ZYKu2JNoLJ3I2FwEtLzN61zZAj4dtZpm0hOWgOMhemIjVx2JbRtpAy4O1B0w9VK8DtO6SJhPhjXxTOzNcTUKUFC76aMExvVYjkS066+bSvjB+zmQa3u3QsUDRDKYwbghpCoaHaGeemv3+3UOmhzHAVWWJvbILOtXqUVBYly7KOkQIh4wb3k0ZtkXD7Ddpq4D/zEHyT1E2nXBk/7TinLp9oku1pWX8skCdnJzcDQNnj/u87nW06o+hnPbov8Ncls/7zJJwtcDVFMexS0HDsXZPJBXaPnkjEfmOrsXf4kBSbW5Ey16Kp3I4RTdLY2XaUGs//jdmaDDwulml iste-test@test.intershop.com"
2021-11-30T12:46:47.3153131Z       }
2021-11-30T12:46:47.3153454Z      ]
2021-11-30T12:46:47.3153687Z     }
2021-11-30T12:46:47.3153966Z    },
2021-11-30T12:46:47.3154357Z    "servicePrincipalProfile": {
2021-11-30T12:46:47.3154681Z     "clientId": "msi"
2021-11-30T12:46:47.3155003Z    },
2021-11-30T12:46:47.3155701Z    "nodeResourceGroup": "MC_<our rg>_<our aks name>_northeurope",
2021-11-30T12:46:47.3156189Z    "enableRBAC": true,
2021-11-30T12:46:47.3156492Z    "networkProfile": {
2021-11-30T12:46:47.3156876Z     "networkPlugin": "kubenet",
2021-11-30T12:46:47.3157254Z     "loadBalancerSku": "Standard",
2021-11-30T12:46:47.3157594Z     "loadBalancerProfile": {
2021-11-30T12:46:47.3157994Z      "managedOutboundIPs": {
2021-11-30T12:46:47.3158360Z       "count": 1
2021-11-30T12:46:47.3158612Z      },
2021-11-30T12:46:47.3158993Z      "effectiveOutboundIPs": [
2021-11-30T12:46:47.3159328Z       {
2021-11-30T12:46:47.3160487Z        "id": "/subscriptions/8f19e0c8-0a30-4511-83db-e718bb8eaf42/resourceGroups/MC_<our rg>_<our aks name>_northeurope/providers/Microsoft.Network/publicIPAddresses/b999116c-7d9c-4c04-984d-a41ec29374c1"
2021-11-30T12:46:47.3161156Z       }
2021-11-30T12:46:47.3161399Z      ]
2021-11-30T12:46:47.3161689Z     },
2021-11-30T12:46:47.3162018Z     "podCidr": "10.244.0.0/16",
2021-11-30T12:46:47.3162396Z     "serviceCidr": "10.0.0.0/16",
2021-11-30T12:46:47.3162728Z     "dnsServiceIP": "10.0.0.10",
2021-11-30T12:46:47.3163134Z     "dockerBridgeCidr": "172.17.0.1/16",
2021-11-30T12:46:47.3163588Z     "outboundType": "loadBalancer"
2021-11-30T12:46:47.3164077Z    },
2021-11-30T12:46:47.3164395Z    "aadProfile": {
2021-11-30T12:46:47.3164733Z     "managed": true,
2021-11-30T12:46:47.3165031Z     "adminGroupObjectIDs": [
2021-11-30T12:46:47.3165679Z      "00000000-0000-0000-0000-000000000000"
2021-11-30T12:46:47.3166059Z     ],
2021-11-30T12:46:47.3166992Z     "tenantID": "***"
2021-11-30T12:46:47.3167292Z    },
2021-11-30T12:46:47.3167639Z    "maxAgentPools": 100,
2021-11-30T12:46:47.3167997Z    "identityProfile": {
2021-11-30T12:46:47.3168297Z     "kubeletidentity": {
2021-11-30T12:46:47.3169447Z      "resourceId": "/subscriptions/8f19e0c8-0a30-4511-83db-e718bb8eaf42/resourcegroups/MC_<our rg>_<our aks name>_northeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<our aks name>-agentpool",
2021-11-30T12:46:47.3170420Z      "clientId": "91e95b63-976f-4406-9c42-b224ac57102f",
2021-11-30T12:46:47.3171347Z      "objectId": "669cd9e4-d1c8-4611-ad28-e41fee323c62"
2021-11-30T12:46:47.3171679Z     }
2021-11-30T12:46:47.3171989Z    }
2021-11-30T12:46:47.3172273Z   },
2021-11-30T12:46:47.3172519Z   "identity": {
2021-11-30T12:46:47.3172883Z    "type": "SystemAssigned",
2021-11-30T12:46:47.3173517Z    "principalId": "fa2dc79c-2f2b-4970-86ed-de3b1bd8b889",
2021-11-30T12:46:47.3174401Z    "tenantId": "***"
2021-11-30T12:46:47.3174691Z   },
2021-11-30T12:46:47.3175054Z   "sku": {
2021-11-30T12:46:47.3175380Z    "name": "Basic",
2021-11-30T12:46:47.3175653Z    "tier": "Free"
2021-11-30T12:46:47.3175953Z   }
2021-11-30T12:46:47.3176230Z  }
2021-11-30T12:46:47.3257886Z DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ContainerRegistryManagementClient
2021-11-30T12:46:47.3259311Z DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-11-30T12:46:47.3260042Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
2021-11-30T12:46:47.4137981Z DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "GET /***/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
2021-11-30T12:46:47.4162582Z DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/***/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/***/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/***/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
2021-11-30T12:46:47.4477947Z DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
2021-11-30T12:46:47.4482851Z DEBUG: cli.azure.cli.core.auth.msal_authentication: ServicePrincipalCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
2021-11-30T12:46:47.4496327Z DEBUG: msal.application: Cache hit an AT
2021-11-30T12:46:47.4501433Z DEBUG: msal.telemetry: Generate or reuse correlation_id: b7d62c15-97ba-4a65-903c-86f5fe6b9308
2021-11-30T12:46:47.4513254Z DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/743a0c9d-3b7f-4667-818a-ac656fff69a8/resourceGroups/test-iste-common-northeurope/providers/Microsoft.ContainerRegistry/registries/ishisteacr?api-version=2021-06-01-preview'
2021-11-30T12:46:47.4517646Z DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
2021-11-30T12:46:47.4521204Z DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
2021-11-30T12:46:47.4525273Z DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
2021-11-30T12:46:47.4530114Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '93db717d-51db-11ec-8ba6-c953cb07150b'
2021-11-30T12:46:47.4534299Z DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'aks update'
2021-11-30T12:46:47.4538578Z DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug -n -g --attach-acr'
2021-11-30T12:46:47.4543090Z DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.30.0 (DEB) azsdk-python-azure-mgmt-containerregistry/8.2.0 Python/3.6.10 (Linux-5.11.0-1021-azure-x86_64-with-debian-bullseye-sid) VSTS_28c253d8-c3c8-42d8-88a7-2cd371007686_build_70_0'
2021-11-30T12:46:47.4548544Z DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
2021-11-30T12:46:47.4552402Z DEBUG: cli.azure.cli.core.sdk.policies: Request body:
2021-11-30T12:46:47.4556488Z DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
2021-11-30T12:46:47.4592291Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
2021-11-30T12:46:47.6023521Z DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/743a0c9d-3b7f-4667-818a-ac656fff69a8/resourceGroups/test-iste-common-northeurope/providers/Microsoft.ContainerRegistry/registries/ishisteacr?api-version=2021-06-01-preview HTTP/1.1" 200 None
2021-11-30T12:46:47.6034715Z DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
2021-11-30T12:46:47.6038230Z DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
2021-11-30T12:46:47.6042127Z DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
2021-11-30T12:46:47.6045993Z DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
2021-11-30T12:46:47.6049702Z DEBUG: cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
2021-11-30T12:46:47.6053533Z DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
2021-11-30T12:46:47.6061586Z DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
2021-11-30T12:46:47.6068731Z DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
2021-11-30T12:46:47.6076725Z DEBUG: cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
2021-11-30T12:46:47.6098177Z DEBUG: cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2021-06-01-preview'
2021-11-30T12:46:47.6109029Z DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
2021-11-30T12:46:47.6113085Z DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
2021-11-30T12:46:47.6117240Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11993'
2021-11-30T12:46:47.6121068Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'e8dbe3d1-f43c-4678-87e1-040e6279ae52'
2021-11-30T12:46:47.6126492Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'e8dbe3d1-f43c-4678-87e1-040e6279ae52'
2021-11-30T12:46:47.6155783Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHEUROPE:20211130T124647Z:e8dbe3d1-f43c-4678-87e1-040e6279ae52'
2021-11-30T12:46:47.6182497Z DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
2021-11-30T12:46:47.6183713Z DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 30 Nov 2021 12:46:46 GMT'
2021-11-30T12:46:47.6184277Z DEBUG: cli.azure.cli.core.sdk.policies: Response content:
2021-11-30T12:46:47.6188271Z DEBUG: cli.azure.cli.core.sdk.policies: {"sku":{"name":"Basic","tier":"Basic"},"type":"Microsoft.ContainerRegistry/registries","id":"/subscriptions/743a0c9d-3b7f-4667-818a-ac656fff69a8/resourceGroups/test-iste-common-northeurope/providers/Microsoft.ContainerRegistry/registries/ishisteacr","name":"ishisteacr","location":"northeurope","tags":{},"systemData":{"createdBy":"TBergmann@intershop.com","createdByType":"User","createdAt":"2021-10-26T13:21:55.8781183+00:00","lastModifiedBy":"KHauser@intershop.com","lastModifiedByType":"User","lastModifiedAt":"2021-11-30T08:56:16.2177845+00:00"},"properties":{"loginServer":"ishisteacr.azurecr.io","creationDate":"2021-10-26T13:21:55.8781183Z","provisioningState":"Succeeded","adminUserEnabled":true,"policies":{"quarantinePolicy":{"status":"disabled"},"trustPolicy":{"type":"Notary","status":"disabled"},"retentionPolicy":{"days":7,"lastUpdatedTime":"2021-10-26T13:21:57.7249403+00:00","status":"disabled"},"exportPolicy":{"status":"enabled"}},"encryption":{"status":"disabled"},"dataEndpointEnabled":false,"dataEndpointHostNames":[],"privateEndpointConnections":[],"publicNetworkAccess":"Enabled","networkRuleBypassOptions":"AzureServices","zoneRedundancy":"Disabled","anonymousPullEnabled":false}}
2021-11-30T12:46:47.6241111Z INFO: cli.azure.cli.command_modules.acs.custom: Waiting for AAD role to propagate
2021-11-30T12:46:47.6256733Z DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=AuthorizationManagementClient
2021-11-30T12:46:47.6278523Z DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-11-30T12:46:47.6311374Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
2021-11-30T12:46:47.6715237Z DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "GET /***/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
2021-11-30T12:46:47.6736814Z DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/***/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/***/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/***/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
2021-11-30T12:46:47.6819039Z DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
2021-11-30T12:46:47.6826344Z DEBUG: cli.azure.cli.core.commands.client_factory: Adding custom headers to the client:
2021-11-30T12:46:47.6830806Z DEBUG: cli.azure.cli.core.commands.client_factory:     'x-ms-client-request-id': '93db717d-51db-11ec-8ba6-c953cb07150b'
2021-11-30T12:46:47.6835019Z DEBUG: cli.azure.cli.core.commands.client_factory:     'CommandName': 'aks update'
2021-11-30T12:46:47.6839161Z DEBUG: cli.azure.cli.core.commands.client_factory:     'ParameterSetName': '--debug -n -g --attach-acr'
2021-11-30T12:46:47.6906789Z DEBUG: msrest.async_paging: Paging async iterator protocol is not available for RoleDefinitionPaged
2021-11-30T12:46:47.6914023Z DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token
2021-11-30T12:46:47.6918200Z DEBUG: cli.azure.cli.core.auth.msal_authentication: ServicePrincipalCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
2021-11-30T12:46:47.6931779Z DEBUG: msal.application: Cache hit an AT
2021-11-30T12:46:47.6936269Z DEBUG: msal.telemetry: Generate or reuse correlation_id: 188d7e36-59dc-4ca6-b3aa-702ceb6f0c23
2021-11-30T12:46:47.6946342Z DEBUG: msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/743a0c9d-3b7f-4667-818a-ac656fff69a8/resourceGroups/test-iste-common-northeurope/providers/Microsoft.ContainerRegistry/registries/ishisteacr/providers/Microsoft.Authorization/roleDefinitions?$filter=roleName%20eq%20%27acrpull%27&api-version=2018-01-01-preview'
2021-11-30T12:46:47.6950457Z DEBUG: msrest.http_logger: Request method: 'GET'
2021-11-30T12:46:47.6958503Z DEBUG: msrest.http_logger: Request headers:
2021-11-30T12:46:47.6962413Z DEBUG: msrest.http_logger:     'Accept': 'application/json'
2021-11-30T12:46:47.6965618Z DEBUG: msrest.http_logger:     'accept-language': 'en-US'
2021-11-30T12:46:47.6971025Z DEBUG: msrest.http_logger:     'User-Agent': 'python/3.6.10 (Linux-5.11.0-1021-azure-x86_64-with-debian-bullseye-sid) msrest/0.6.21 VSTS_28c253d8-c3c8-42d8-88a7-2cd371007686_build_70_0 msrest_azure/0.6.3 azure-mgmt-authorization/0.61.0 Azure-SDK-For-Python AZURECLI/2.30.0 (DEB)'
2021-11-30T12:46:47.6975572Z DEBUG: msrest.http_logger: Request body:
2021-11-30T12:46:47.6979391Z DEBUG: msrest.http_logger: None
2021-11-30T12:46:47.6983610Z DEBUG: msrest.universal_http: Configuring redirects: allow=True, max=30
2021-11-30T12:46:47.6987439Z DEBUG: msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
2021-11-30T12:46:47.6991561Z DEBUG: msrest.universal_http: Configuring proxies: ''
2021-11-30T12:46:47.6995362Z DEBUG: msrest.universal_http: Evaluate proxies against ENV settings: True
2021-11-30T12:46:47.7029055Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
2021-11-30T12:46:47.7596889Z DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/743a0c9d-3b7f-4667-818a-ac656fff69a8/resourceGroups/test-iste-common-northeurope/providers/Microsoft.ContainerRegistry/registries/ishisteacr/providers/Microsoft.Authorization/roleDefinitions?$filter=roleName%20eq%20%27acrpull%27&api-version=2018-01-01-preview HTTP/1.1" 200 None
2021-11-30T12:46:47.7611440Z DEBUG: msrest.http_logger: Response status: 200
2021-11-30T12:46:47.7615159Z DEBUG: msrest.http_logger: Response headers:
2021-11-30T12:46:47.7619238Z DEBUG: msrest.http_logger:     'Cache-Control': 'no-cache'
2021-11-30T12:46:47.7623283Z DEBUG: msrest.http_logger:     'Pragma': 'no-cache'
2021-11-30T12:46:47.7627287Z DEBUG: msrest.http_logger:     'Transfer-Encoding': 'chunked'
2021-11-30T12:46:47.7631263Z DEBUG: msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
2021-11-30T12:46:47.7635243Z DEBUG: msrest.http_logger:     'Content-Encoding': 'gzip'
2021-11-30T12:46:47.7639209Z DEBUG: msrest.http_logger:     'Expires': '-1'
2021-11-30T12:46:47.7643032Z DEBUG: msrest.http_logger:     'Vary': 'Accept-Encoding'
2021-11-30T12:46:47.7647078Z DEBUG: msrest.http_logger:     'x-ms-request-id': '572274c8-7cc8-40db-bc26-3b6d4d5ea2e6'
2021-11-30T12:46:47.7650486Z DEBUG: msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
2021-11-30T12:46:47.7655865Z DEBUG: msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
2021-11-30T12:46:47.7660150Z DEBUG: msrest.http_logger:     'Set-Cookie': 'x-ms-gateway-slice=Production; path=/; secure; samesite=none; httponly'
2021-11-30T12:46:47.7665132Z DEBUG: msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-reads': '11995'
2021-11-30T12:46:47.7669672Z DEBUG: msrest.http_logger:     'x-ms-correlation-request-id': '468f622e-743f-4f19-bf28-e27781fb16a4'
2021-11-30T12:46:47.7677248Z DEBUG: msrest.http_logger:     'x-ms-routing-request-id': 'NORTHEUROPE:20211130T124647Z:468f622e-743f-4f19-bf28-e27781fb16a4'
2021-11-30T12:46:47.7682079Z DEBUG: msrest.http_logger:     'Date': 'Tue, 30 Nov 2021 12:46:47 GMT'
2021-11-30T12:46:47.7686239Z DEBUG: msrest.http_logger: Response content:
2021-11-30T12:46:47.7692451Z DEBUG: msrest.http_logger: {"value":[{"properties":{"roleName":"AcrPull","type":"BuiltInRole","description":"acr pull","assignableScopes":["/"],"permissions":[{"actions":["Microsoft.ContainerRegistry/registries/pull/read"],"notActions":[],"dataActions":[],"notDataActions":[]}],"createdOn":"2018-10-22T19:01:56.8227182Z","updatedOn":"2021-11-11T20:13:08.8779328Z","createdBy":null,"updatedBy":null},"id":"/subscriptions/743a0c9d-3b7f-4667-818a-ac656fff69a8/providers/Microsoft.Authorization/roleDefinitions/7f951dda-4ed3-4680-a7ca-43fe172d538d","type":"Microsoft.Authorization/roleDefinitions","name":"7f951dda-4ed3-4680-a7ca-43fe172d538d"}]}
2021-11-30T12:46:47.7714315Z DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-11-30T12:46:47.7747795Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
2021-11-30T12:46:47.8187075Z DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "GET /***/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
2021-11-30T12:46:47.8208621Z DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/***/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/***/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/***/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/***/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
2021-11-30T12:46:47.8285171Z DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
2021-11-30T12:46:47.8291874Z DEBUG: cli.azure.cli.core.commands.client_factory: Adding custom headers to the client:
2021-11-30T12:46:47.8296419Z DEBUG: cli.azure.cli.core.commands.client_factory:     'x-ms-client-request-id': '93db717d-51db-11ec-8ba6-c953cb07150b'
2021-11-30T12:46:47.8300432Z DEBUG: cli.azure.cli.core.commands.client_factory:     'CommandName': 'aks update'
2021-11-30T12:46:47.8307412Z DEBUG: cli.azure.cli.core.commands.client_factory:     'ParameterSetName': '--debug -n -g --attach-acr'
2021-11-30T12:46:47.8311680Z DEBUG: msrest.async_paging: Paging async iterator protocol is not available for ServicePrincipalPaged
2021-11-30T12:46:47.8319020Z DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token
2021-11-30T12:46:47.8323422Z DEBUG: cli.azure.cli.core.auth.msal_authentication: ServicePrincipalCredential.get_token: scopes=('https://graph.windows.net//.default',), kwargs={}
2021-11-30T12:46:47.8355787Z DEBUG: msal.application: Found 0 RTs matching {'environment': 'login.microsoftonline.com', 'home_account_id': None, 'client_id': '***'}
2021-11-30T12:46:47.8443841Z DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "GET /common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/authorize HTTP/1.1" 200 945
2021-11-30T12:46:47.8476504Z DEBUG: msal.telemetry: Generate or reuse correlation_id: bf01bff7-3c5d-4d9a-9df2-b84747fab50c
2021-11-30T12:46:47.8941892Z DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /***/oauth2/v2.0/token HTTP/1.1" 200 1353
2021-11-30T12:46:47.8992667Z DEBUG: msal.token_cache: event={
2021-11-30T12:46:47.8993893Z     "client_id": "***",
2021-11-30T12:46:47.8994471Z     "data": {
2021-11-30T12:46:47.8994783Z         "claims": null,
2021-11-30T12:46:47.8995064Z         "scope": [
2021-11-30T12:46:47.8995512Z             "https://graph.windows.net//.default"
2021-11-30T12:46:47.8995871Z         ]
2021-11-30T12:46:47.8996153Z     },
2021-11-30T12:46:47.8996443Z     "environment": "login.microsoftonline.com",
2021-11-30T12:46:47.8996856Z     "grant_type": "client_credentials",
2021-11-30T12:46:47.8997214Z     "params": null,
2021-11-30T12:46:47.8997485Z     "response": {
2021-11-30T12:46:47.8997857Z         "access_token": "********",
2021-11-30T12:46:47.8998228Z         "expires_in": 3599,
2021-11-30T12:46:47.8998549Z         "ext_expires_in": 3599,
2021-11-30T12:46:47.8998915Z         "token_type": "Bearer"
2021-11-30T12:46:47.8999268Z     },
2021-11-30T12:46:47.8999564Z     "scope": [
2021-11-30T12:46:47.8999866Z         "https://graph.windows.net//.default"
2021-11-30T12:46:47.9000207Z     ],
2021-11-30T12:46:47.9001184Z     "token_endpoint": "https://login.microsoftonline.com/***/oauth2/v2.0/token"
2021-11-30T12:46:47.9001753Z }
2021-11-30T12:46:47.9002994Z DEBUG: msrest.http_logger: Request URL: 'https://graph.windows.net/***/servicePrincipals?$filter=servicePrincipalNames%2Fany%28c%3Ac%20eq%20%2791e95b63-976f-4406-9c42-b224ac57102f%27%29&api-version=1.6'
2021-11-30T12:46:47.9024139Z DEBUG: msrest.http_logger: Request method: 'GET'
2021-11-30T12:46:47.9024753Z DEBUG: msrest.http_logger: Request headers:
2021-11-30T12:46:47.9025472Z DEBUG: msrest.http_logger:     'Accept': 'application/json'
2021-11-30T12:46:47.9026311Z DEBUG: msrest.http_logger:     'accept-language': 'en-US'
2021-11-30T12:46:47.9027508Z DEBUG: msrest.http_logger:     'User-Agent': 'python/3.6.10 (Linux-5.11.0-1021-azure-x86_64-with-debian-bullseye-sid) msrest/0.6.21 VSTS_28c253d8-c3c8-42d8-88a7-2cd371007686_build_70_0 msrest_azure/0.6.3 azure-graphrbac/0.60.0 Azure-SDK-For-Python AZURECLI/2.30.0 (DEB)'
2021-11-30T12:46:47.9028326Z DEBUG: msrest.http_logger: Request body:
2021-11-30T12:46:47.9028774Z DEBUG: msrest.http_logger: None
2021-11-30T12:46:47.9029244Z DEBUG: msrest.universal_http: Configuring redirects: allow=True, max=30
2021-11-30T12:46:47.9029799Z DEBUG: msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
2021-11-30T12:46:47.9030537Z DEBUG: msrest.universal_http: Configuring proxies: ''
2021-11-30T12:46:47.9062501Z DEBUG: msrest.universal_http: Evaluate proxies against ENV settings: True
2021-11-30T12:46:47.9071563Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): graph.windows.net:443
2021-11-30T12:46:47.9845617Z DEBUG: urllib3.connectionpool: https://graph.windows.net:443 "GET /***/servicePrincipals?$filter=servicePrincipalNames%2Fany%28c%3Ac%20eq%20%2791e95b63-976f-4406-9c42-b224ac57102f%27%29&api-version=1.6 HTTP/1.1" 403 219
2021-11-30T12:46:47.9856985Z DEBUG: msrest.http_logger: Response status: 403
2021-11-30T12:46:47.9860477Z DEBUG: msrest.http_logger: Response headers:
2021-11-30T12:46:47.9864995Z DEBUG: msrest.http_logger:     'Cache-Control': 'no-cache'
2021-11-30T12:46:47.9868760Z DEBUG: msrest.http_logger:     'Pragma': 'no-cache'
2021-11-30T12:46:47.9873023Z DEBUG: msrest.http_logger:     'Content-Type': 'application/json; odata=minimalmetadata; streaming=true; charset=utf-8'
2021-11-30T12:46:47.9877104Z DEBUG: msrest.http_logger:     'Expires': '-1'
2021-11-30T12:46:47.9881037Z DEBUG: msrest.http_logger:     'ocp-aad-diagnostics-server-name': 'VYULrg9BrbQMfsib4O4o7OK+SYrLz+SnMZQ8MXNDUUQ='
2021-11-30T12:46:47.9885039Z DEBUG: msrest.http_logger:     'request-id': 'ff41d790-c4e8-4f49-8454-afbde4aa03ab'
2021-11-30T12:46:47.9889160Z DEBUG: msrest.http_logger:     'client-request-id': '93db717d-51db-11ec-8ba6-c953cb07150b'
2021-11-30T12:46:47.9892610Z DEBUG: msrest.http_logger:     'x-ms-dirapi-data-contract-version': '1.6'
2021-11-30T12:46:47.9897955Z DEBUG: msrest.http_logger:     'ocp-aad-session-key': 'mp2QRIk5AqInK4AxlPKgGNAS52fkR17sQ2s5UTWtS4BpUte_-T-WNlkpQjNUWu9rx-4TstY8FwFc7kI9HqDf-dtxC7iGsydG0rxhoUTmrnl9GfXrHEMG5Ghp-Ae7-5ND.bW5Cf-byRHuru1vikHLRvJeTbnmXT-eplIeS69oWeXo'
2021-11-30T12:46:47.9902867Z DEBUG: msrest.http_logger:     'Duration': '398809'
2021-11-30T12:46:47.9907214Z DEBUG: msrest.http_logger:     'x-ms-resource-unit': '1'
2021-11-30T12:46:47.9911293Z DEBUG: msrest.http_logger:     'DataServiceVersion': '3.0;'
2021-11-30T12:46:47.9915609Z DEBUG: msrest.http_logger:     'X-AspNet-Version': '4.0.30319'
2021-11-30T12:46:47.9920080Z DEBUG: msrest.http_logger:     'X-Powered-By': 'ASP.NET'
2021-11-30T12:46:47.9924612Z DEBUG: msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
2021-11-30T12:46:47.9928942Z DEBUG: msrest.http_logger:     'Access-Control-Allow-Origin': '*'
2021-11-30T12:46:47.9933385Z DEBUG: msrest.http_logger:     'Date': 'Tue, 30 Nov 2021 12:46:47 GMT'
2021-11-30T12:46:47.9937798Z DEBUG: msrest.http_logger:     'Content-Length': '219'
2021-11-30T12:46:47.9941699Z DEBUG: msrest.http_logger: Response content:
2021-11-30T12:46:47.9946977Z DEBUG: msrest.http_logger: {"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"ff41d790-c4e8-4f49-8454-afbde4aa03ab","date":"2021-11-30T12:46:47"}}
2021-11-30T12:46:47.9965659Z DEBUG: msrest.exceptions: Insufficient privileges to complete the operation.
```

I tried several role assignments (Owner, Contributor, AcrPull) for all SP (the app of our service connection) and Managed Identities (from the aks) I found. It also doesn't matter if the acr is in the same subscription. But if I execute the attachment locally it works.

#17308 does have the same 403. There I saw that with Managed Identity no one should call `graph.windows.net`.

Are you able to help me with these information?

Best,
Karsten

**Comment by khauser** [comment]
Was I 5 hours to late? #20477

**Comment by yonzhan** [comment]
route to service team

**Comment by FumingZhang** [comment]
Hi @khauser, the issue should have been resolved in the latest release version (2.31.0), please update your azure-cli (via `az upgrade`) and have a try, thanks!

**Comment by khauser** [comment]
working as expected

Thanks

**Comment by aakanshaverma1310** [comment]
Hi, I'm using az cli version 2.46.0 but still getting same error when updating AKS cluster. 
I have Managed ID, ACR attached. 
Error :
```
Waiting for AAD role to propagate[###                                 ]  10.0000%
Waiting for AAD role to propagate[#######                             ]  20.0000%
Waiting for AAD role to propagate[##########                          ]  30.0000%
Waiting for AAD role to propagate[##############                      ]  40.0000%
Waiting for AAD role to propagate[##################                  ]  50.0000%
Waiting for AAD role to propagate[#####################               ]  60.0000%
Waiting for AAD role to propagate[#########################           ]  70.0000%
Waiting for AAD role to propagate[############################        ]  80.0000%
Waiting for AAD role to propagate[################################    ]  90.0000%ERROR: Could not create a role assignment for ACR. Are you an Owner on this subscription?

```

Please suggest.
