### ISSUE TITLE
Not able to get credentials az aks get-credentials command

### ISSUE THREAD

**Issue by ashwinpagarkhed** [Azure/azure-cli#20565]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

cannot import name 'edge_zone_type'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 563, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py", line 511, in load_arguments
  File "C:\Users\ashwin.agarkhed\.azure\cliextensions\aks-preview\azext_aks_preview\__init__.py", line 47, in load_arguments
    from ._params import load_arguments
  File "C:\Users\ashwin.agarkhed\.azure\cliextensions\aks-preview\azext_aks_preview\_params.py", line 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: 

azure-cli 2.19.1 *

Extensions:
aks-preview 0.5.41

```

**Comment by yonzhan** [comment]
route to service team

**Comment by ashwinpagarkhed** [comment]
Resolved after I installing aks-preview. Had to reinstall kubectl

**Comment by nrjohnstone-omnia** [comment]
This still happens, just ran into it today.. the fix is as @ashwinpagarkhed says, just remove the aks-preview ... Pretty painful that this is not fixed yet !
