### ISSUE TITLE
az vm create fails with error VMCustomization is not enabled

### ISSUE THREAD

**Issue by ozzy92** [Azure/azure-cli#21224]
## Describe the bug
Following basic how to on creating vms from command line doesn't work, and preview feature doesn't appear in azure.
https://app.pluralsight.com/course-player?clipId=4924ba21-099c-42e1-8683-a131b1f5e442

Closest thing I found is this signup page, which doesn't really help much: 
https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR3_Cn0JTTIxChanY12UDdkpUMDNRRFdHSTRUMU1OUjBTSkw0MFFIRThFRi4u&web=1&wdLOR=c82F6F682-783D-477D-B824-BF81D3A7C7D3

**Command Name**
`az vm create`

**Errors:**
```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature.\"\r\n  }\r\n}"}]}}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

az login
az group create
az vm create --resource-group "psdemo-rg-2" --name "psdemo-win-cli" --image "win2019datacenter" --admin-username "demoadmin" --admin-password "<snip>" --public-ip-sku Standard

## Expected Behavior
creates a vm

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.0
```

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@ozzy92 Hi, we have submitted a PR #21232 to fix this issue. Our planned release time is **03-01**,  do you think this time is acceptable?

**Comment by j5awry** [comment]
@zhoxing-ms : I'd kindly request that  this move faster. This currently affects all new installs, as well as anyone upgrading on Windows or from the latest Linux distro PPAs (for Ubuntu, the `hirsute` PPA). For my team, this breaks some integrations, as well as members of my team. A workaround for Debian based distros is below. Something similar will probably work for RHEL based (untested). 

Minimally, please document the workaround for the broken Windows versions (at least noting the broken version and pointing to the docs to pinning to a version)

For those coming from Debian or Ubuntu: the Microsoft PPAs have past versions, so you can look up the version previous to this push, pin to that version, and force a downgrade. For those on Ubuntu non-LTS > Focal, you can also "fallback" to the Focal PPA as that version (`2.27.2-1~focal`) is operating as expected.

**Comment by ozzy92** [comment]
Is there a workaround?  I see the fix is manipulating the size param, is there a param that can be set?  This doesn't affect me too much, I'm just doing some simple how-to courses.

**Comment by gjolly** [comment]
The easiest workaround is to downgrade to the previous version. On Ubuntu/Debian, users can check what the previous version was with `apt-cache policy azure-cli` and downgrade `apt install azure-cli=$VERSION`.

They can also pin this version for now:

```bash
cat << EOF > /etc/apt/preferences.d/99-azure-cli
Package: azure-cli
Pin: version $VERSION
Pin-Priority: 999
EOF
```

But they will have to remove this file when a fixed package gets released.

**Comment by zhoxing-ms** [comment]
@j5awry @ozzy92 OK, we will solve this issue as soon as possible, and we plan to release the hotfix next Monday (**02-14**).

**Comment by djhmateer** [comment]
On WSL2 Ubuntu this worked for me:

```bash
# 2.33.0
az --version

# find what I had previously (look at the top of the list)
apt-cache policy azure-cli

# downgrade
sudo apt install azure-cli=2.32.0-1~bionic

# refresh token
az login
```

**Comment by bertneef** [comment]
2.33.0 is currently the active version in azure cloud shell as well, hope the upcoming hotfix will be pushed there as well.

**Comment by ringoc** [comment]
> 2.33.0 is currently the active version in azure cloud shell as well, hope the upcoming hotfix will be pushed there as well.

Hi Team, please prioritize the hotfix as this is blocking user from VM creation in Cloud Shell. Thanks.

**Comment by yonzhan** [comment]
Yes, we planned to apply the hotfix today and it will be applied to cloud shell afterwards as well.

**Comment by zhoxing-ms** [comment]
The version 2.33.1 of CLI for hotfix has been released. 
@edyoung Please help deploy the latest version of CLI in the Cloud Shell and then sync the progress here

**Comment by TiloGit** [comment]
just checked cloud shell: 
`azure-cli                         2.33.0 *`
`You have 2 updates available. They will be updated with the next build of Cloud Shell.`

**Comment by bmp-dot** [comment]
@TiloGit same.  Waiting for this build.

**Comment by jokervulinh6789** [comment]
has it been fixed?

**Comment by zhoxing-ms** [comment]
@TiloGit  @bmp-dot  @jokervulinh6789 Now the latest version (2.33.1) of CLI for this fix is available. You can refer to the doc https://docs.microsoft.com/en-us/cli/azure/install-azure-cli to install or use the `az upgrade --yes` command to update the CLI version.
However, the cloud shell environment still needs a few days to deploy the latest CLI package

**Comment by bmp-dot** [comment]
@zhoxing-ms thanks for the update.  I need the Cloud Shell version for some training I am giving.  Currently we are stopped unless we mitigate to local installs.

**Comment by wfouche** [comment]
@zhoxing-ms  MS Training at https://docs.microsoft.com/en-us/learn/modules/secure-network-connectivity-azure/6-configure-access-network-security-group still broken. 

![image](https://user-images.githubusercontent.com/13682850/154211139-9976a7f3-734a-4d41-a273-32d7de040103.png)

**Comment by zhoxing-ms** [comment]
@wfouche This is because the Cloud Shell environment has not completed the deployment of the latest version of CLI.
If Cloud Shell has completed the deployment of latest CLI, please sync the status here @dsajanice @edyoung

**Comment by steveluper** [comment]
Still failing in Cloud Shell. @dsajanice  and @edyoung update please.

**Comment by ssennettau** [comment]
For reference, I've submitted an issue to the Azure CloudShell repo as well, linking back to this issue. Thanks to the CLI team for the rapid fix, look forward to seeing it also in CloudShell!

https://github.com/Azure/CloudShell/issues/145

**Comment by neanderson** [comment]
Cloud Shell is showing the 2.33.1 update now.

`@Azure:~$ az --version
azure-cli                         2.33.1`

**Comment by zhoxing-ms** [comment]
![Screenshot 2022-02-21 100344](https://user-images.githubusercontent.com/16612065/154877447-27dfe2ea-e393-4941-9877-68a148c53bc7.png)
