### ISSUE TITLE
Unable to add az extension rdbms-connect in cloud shell

### ISSUE THREAD

**Issue by chuculain** [Azure/azure-cli#21535]
## Describe the bug
I am unable to add az extension rdbms-connect from the  cloud shell.

**Command Name**
`az extension add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: 'sudo'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 336, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 115, in _add_whl_ext
    _install_deps_for_psycopg2()
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 224, in _install_deps_for_psycopg2
    exit_code = subprocess.call(apt_update_cmd, True)
  File "/opt/az/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/az/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/az/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension add -n rdbms-connect`

## Expected Behavior
Extension install without failures.

## Environment Summary
```
Linux-5.4.0-1070-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.34.0 *

Extensions:
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context
I ran into this problem while attempting to automate the DB deployment for a azure postgres flexible server using the command:
`az postgres flexible-server execute <args>`

**Comment by chuculain** [comment]
Here is the output when the command is run with debug:

**az extension add --upgrade -n rdbms-connect --debug**
cli.knack.cli: Command arguments: ['extension', 'add', '--upgrade', '-n', 'rdbms-connect', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f6da26581f0>, <function OutputProducer.on_global_arguments at 0x7f6da258f0d0>, <function CLIQuery.on_global_arguments at 0x7f6da25215e0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'extension': ['azure.cli.command_modules.extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: extension                 0.002         1         7
cli.azure.cli.core: Total (1)                 0.002         1         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.123         1         1  /opt/az/lib/python3.8/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.123         1         1  
cli.azure.cli.core: Loaded 2 groups, 8 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : extension add
cli.azure.cli.core: Command table: extension add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f6da1cfc550>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/sean/.azure/commands/2022-03-04.20-45-59.extension_add.284.log'.
az_command_data_logger: command args: extension add --upgrade -n {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f6da1c81940>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f6da1bb7ca0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f6da1bb7dc0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f6da258f160>, <function CLIQuery.handle_query_parameter at 0x7f6da2521670>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f6da1bb7d30>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): azcliextensionsync.blob.core.windows.net:443
urllib3.connectionpool: https://azcliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 1592393
cli.azure.cli.core.extension._resolve: Candidates ['rdbms_connect-0.1.0-py2.py3-none-any.whl', 'rdbms_connect-0.1.1-py2.py3-none-any.whl', 'rdbms_connect-0.1.2-py2.py3-none-any.whl', 'rdbms_connect-0.1.3-py2.py3-none-any.whl', 'rdbms_connect-0.1.4-py2.py3-none-any.whl', 'rdbms_connect-1.0.0-py2.py3-none-any.whl', 'rdbms_connect-1.0.1-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['rdbms_connect-0.1.0-py2.py3-none-any.whl', 'rdbms_connect-0.1.1-py2.py3-none-any.whl', 'rdbms_connect-0.1.2-py2.py3-none-any.whl', 'rdbms_connect-0.1.3-py2.py3-none-any.whl', 'rdbms_connect-0.1.4-py2.py3-none-any.whl', 'rdbms_connect-1.0.0-py2.py3-none-any.whl', 'rdbms_connect-1.0.1-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['rdbms_connect-0.1.0-py2.py3-none-any.whl', 'rdbms_connect-0.1.1-py2.py3-none-any.whl', 'rdbms_connect-0.1.2-py2.py3-none-any.whl', 'rdbms_connect-0.1.3-py2.py3-none-any.whl', 'rdbms_connect-0.1.4-py2.py3-none-any.whl', 'rdbms_connect-1.0.0-py2.py3-none-any.whl', 'rdbms_connect-1.0.1-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['rdbms_connect-1.0.1-py2.py3-none-any.whl', 'rdbms_connect-1.0.0-py2.py3-none-any.whl', 'rdbms_connect-0.1.4-py2.py3-none-any.whl', 'rdbms_connect-0.1.3-py2.py3-none-any.whl', 'rdbms_connect-0.1.2-py2.py3-none-any.whl', 'rdbms_connect-0.1.1-py2.py3-none-any.whl', 'rdbms_connect-0.1.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Choosing the latest of the remaining candidates.
cli.azure.cli.core.extension._resolve: Chosen {'downloadUrl': 'https://azcliprod.blob.core.windows.net/cli-extensions/rdbms_connect-1.0.1-py2.py3-none-any.whl', 'filename': 'rdbms_connect-1.0.1-py2.py3-none-any.whl', 'metadata': {'azext.minCliCoreVersion': '2.19.0', 'classifiers': ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'Programming Language :: Python', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'License :: OSI Approved :: MIT License'], 'extensions': {'python.details': {'contacts': [{'email': 'azpycli@microsoft.com', 'name': 'Microsoft Corporation', 'role': 'author'}], 'document_names': {'description': 'DESCRIPTION.rst'}, 'project_urls': {'Home': 'https://github.com/Azure/azure-cli-extensions/tree/master/src/rdbms-connect'}}}, 'extras': [], 'generator': 'bdist_wheel (0.30.0)', 'license': 'MIT', 'metadata_version': '2.0', 'name': 'rdbms-connect', 'run_requires': [{'requires': ['mycli (==1.22.2)', 'pgcli (==3.0.0)', 'setproctitle (==1.2.2)']}], 'summary': 'Support for testing connection to Azure Database for MySQL & PostgreSQL servers.', 'version': '1.0.1'}, 'sha256Digest': 'c13bd245524b6c0f8dab0b7c80e51d710934f12f1f68fbc74614805aeb1429f7'}
cli.azure.cli.core.extension.operations: Extension source is url? True
cli.azure.cli.core.extension.operations: This extension depends on gcc, libpq-dev, python3-dev and they will be installed first.
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 336, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 115, in _add_whl_ext
    _install_deps_for_psycopg2()
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 224, in _install_deps_for_psycopg2
    exit_code = subprocess.call(apt_update_cmd, True)
  File "/opt/az/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/az/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/az/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: [Errno 2] No such file or directory: 'sudo'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 336, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 115, in _add_whl_ext
    _install_deps_for_psycopg2()
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 224, in _install_deps_for_psycopg2
    exit_code = subprocess.call(apt_update_cmd, True)
  File "/opt/az/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/az/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/az/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo'
az_command_data_logger: [Errno 2] No such file or directory: 'sudo'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 336, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 115, in _add_whl_ext
    _install_deps_for_psycopg2()
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/extension/operations.py", line 224, in _install_deps_for_psycopg2
    exit_code = subprocess.call(apt_update_cmd, True)
  File "/opt/az/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/az/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/az/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo'
To open an issue, please run: 'az feedback'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f6da1cfc790>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.449 seconds (init: 0.131, invoke: 0.318)
telemetry.save: Save telemetry record of length 6475 in cache
telemetry.check: Negative: The /home/sean/.azure/telemetry.txt was modified at 2022-03-04 20:42:44.323245, which in less than 600.000000 s

**Comment by yonzhan** [comment]
route to CXP team

**Comment by evelyn-ys** [comment]
@DaeunYim Can you check if Cloud Shell has related dependencies already?

**Comment by jiasli** [comment]
The issue is because Cloud Shell doesn't have `sudo` command. 

https://github.com/Azure/azure-cli/blob/2e87ac82207b345be80aa7051cabf5071f1b94dd/src/azure-cli-core/azure/cli/core/extension/operations.py#L219-L224

I commented on it in https://github.com/Azure/azure-cli/pull/21294#r806475019 and now these lines are indeed causing problems. 🤔

**Comment by navba-MSFT** [comment]
@chuculain Apologies for the late reply. The issue is currently waiting on the above PR's review. We will update this thread once we have more details.

CC @DaeunYim @jiasli

**Comment by DaeunYim** [comment]
We are still working with CloudShell team to resolve this issue.

**Comment by louisliu15** [comment]
Met the same issue when trying to install rdbms-connect in cloud shell.

The main reason for that is exception when trying to install and compile psycopg2, which misses the dependency of libpq-dev.
`
In file included from psycopg/psycopgmodule.c:28:
  ./psycopg/psycopg.h:36:10: fatal error: libpq-fe.h: No such file or directory
   #include <libpq-fe.h>
            ^~~~~~~~~~~~
  compilation terminated.
`
I tried to install psycopg2-binary individually however it didn't fix the libpq dependency.

**Comment by DaeunYim** [comment]
Hi, I'm still waiting for CloudShell team to finish this. As they are the one who need to resolve this dependency issue..

**Comment by jcontti-axa** [comment]
was this solved?

**Comment by nunomaia-diconium** [comment]
I have the same issue, using the azure-cli 2.46.0 version, and while simply running " az extension add --name rdbms-connect". Was this solved?

**Comment by chuculain** [comment]
It looks like it was fixed and commited to dev branch. I don't know what release of azure cli it will come out on.

**Comment by green-munkey** [comment]
The issue is still present on Windows. 
![image](https://github.com/Azure/azure-cli/assets/15044310/073cd8f9-8ece-4f37-8dd3-8e4ee2fc01fb)

**Comment by jupiter19914** [comment]
Did this ever get resolved?  I have same issue unable to install extension on windows in Bash.

**Comment by LTK-Leo** [comment]
Not resolved yet.

**Comment by Ameenbharuchi1** [comment]
Has this been resolved?

**Comment by andreapasqualiTechedge** [comment]
Hello, 2024 here. The issue is still present in Windows.

**Comment by sofbkeller** [comment]
Running into this issue as well.
