### ISSUE TITLE
azure CLI beta uses Azure AD Graph

### ISSUE THREAD

**Issue by ausfestivus** [Azure/azure-cli#22264]
**Describe the bug**

The Azure CLI beta described [here](https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration?tabs=powershell) says it uses the MS Graph API. When I run the Azure CLI command with the debug switch enabled, the CLI beta still uses the old Azure AD Graph API address.

Service Principals which are granted only MS Graph API permissions cannot be used with the Azure CLI beta to make changes in Azure AD. This can be demonstrated when trying to use an SP in an automation pipeline that will create an Azure AD Group.

**To Reproduce**

* create an Azure AD Service Principal that has the MS Graph Application API Permissions described [here](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#permissions).
* Install the Azure CLI beta per the instructions above.
* Sign in to Azure as the Service Principal via the Azure CLI using this command: `az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant "GUID HERE" --allow-no-subscriptions --debug`
* Attempt to create an Azure AD Group with this command: `az ad group create --display-name "YOUR GROUP NAME HERE" --mail-nickname "YOUR GROUP NAME HERE" --debug`
* Note the response that the request is not authorized
* Note in the debug output that the Azure CLI shows the CLI passing API requests to https://graph.windows.net (the legacy Azure AD Graph API) and not the new API at https://graph.microsoft.com (the new MS Graph API). Per this documentation [here](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-request-differences).

**Expected behavior**

The Azure CLI beta uses the correct APIs that the documentation says it does.

**Environment summary**

* Mac OS 12.3.1
* Python 3.10 via HomeBrew
* Azure CLI beta installed per instructions [here](https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration?tabs=powershell#try-azure-cli-beta-with-microsoft-graph).

**Additional context**

Premier Support Case #: `2205030030000806`

**Comment by yonzhan** [comment]
azure CLI beta

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by ausfestivus** [comment]
What's also annoying about this is that I am also unable to add the Azure Active Directory Graph API Permissions to the SP. The ARM Portal currently has it disabled.

![Screen Shot 2022-05-05 at 10 29 18 am](https://user-images.githubusercontent.com/40222285/166847894-2bff6d55-a047-41a9-b767-bf471c1e3618.png)

Note also, that the Azure Active Directory Graph API deprecation appears to have been pushed back 6 months. See [this](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/azure-ad-change-management-simplified/ba-p/2967456) post. Someone should probably tell the AAD team to reenable the selector in the ARM Portal for customers.

This issue is now blocking our scheduled work.

**Comment by jiasli** [comment]
The previous beta (2.35.0.postxxx) was overridden by the latest 2.36.0 release. I will release a new beta (2.36.0.postxxx) soon with some new refactoring.

> What's also annoying about this is that I am also unable to add the Azure Active Directory Graph API Permissions to the SP. The ARM Portal currently has it disabled.

This was the decision of AAD team and Azure Portal. Instead of using Azure Portal, you may grant AD Graph permissions using Azure CLI. Please see https://github.com/Azure/azure-cli/issues/19818#issuecomment-939216867.

**Comment by ausfestivus** [comment]
> I will release a new beta (2.36.0.postxxx) soon with some new refactoring.

Can you be more specific than soon? How feasible is it to restore the previous (2.35) beta to the repo?

Im currently blocked by this. Im required to use an SP that has MS Graph API permissions AND Azure CLI for this work. With these two requirements on me I cannot continue the work. At least give me a rough timeframe to work with instead of "soon"? That way I can at least get the PM off my back.

**Comment by jiasli** [comment]
I am doing that right now! 😉

**Comment by jiasli** [comment]
I have released [2.36.0.post20220505034434](https://azurecliprod.blob.core.windows.net/beta/simple/azure-cli/). Please follow https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration to install this version and give it a try!

NOTE: The beta version doesn't guarantee production quality and tends to change at any time.

**Comment by ausfestivus** [comment]
Have just updated, saw the updates come in. Still failing with the same error.
Debugs showing the CLI still making requests to windows.net instead of windows.com.

Standby, let me get you a gist.

**Comment by jiasli** [comment]
Judging from the path

```
/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py
```

You are still calling the Azure CLI installed by Homebrew. Please make sure the virtual env is activated and the `az` you are running is 

```
$ az --version
azure-cli                2.36.0.post20220505034434

core                     2.36.0.post20220505034434
telemetry                1.0.6.post20220505034434
```

**Comment by ausfestivus** [comment]
> You are still calling the Azure CLI installed by Homebrew.

You are correct sir. My bad. Too many terminal windows open with different environments in them.
I can confirm that the issue is now resolved.

Thank you!
