### ISSUE TITLE
aks command invoke failing due to init container failure

### ISSUE THREAD

**Issue by datadot** [Azure/azure-cli#22738]
**Related command**

az aks command invoke

**Describe the bug**

When running az aks command invoke to run any command eg kubectl get pods -A, the command returns with:

(KubernetesOperationError) Failed to run command due to cluster perf issue, container command-4a5fb8583ae44b069516eb2d9db9fc88 in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).
Code: KubernetesOperationError
Message: Failed to run command due to cluster perf issue, container command-4a5fb8583ae44b069516eb2d9db9fc88 in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).

Actual cause of error is a failure in the init container:

copying default SA
wait for AAD token
inotifywait: error while loading shared libraries: libinotifytools.so.0: cannot open shared object file: No such file or directory
Error from server (BadRequest): container "user-command" in pod "command-4a5fb8583ae44b069516eb2d9db9fc88" is waiting to start: PodInitializing

**To Reproduce**

az aks command invoke --resource-group <my-rg> --name <my-aks-cluster> --command 'kubectl get pods -A'

**Expected behavior**

Command to run successfully

**Environment summary**

azure-cli 2.37.0
Tested on Windows 11, Azure DevOps pipeline (Ubuntu), WSL (Ubuntu)

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@datadot Thanks for reaching out to us and sharing this feedback. Please answer the below questions:

1. Could you please let us know if you are still facing the same issue or was it a transient issue ?
2. Are you trying to connect to a private AKS cluster ?
3. Could you please share the `--debug `output ?

Awaiting your reply.

**Comment by andyliuliming** [comment]
working on the fix now.

**Comment by datadot** [comment]
@navba-MSFT thanks for following this up:

1) Yes issue is persistent
2) Both private and public AKS clusters.
3) Will update shortly.

@andyliuliming thanks, so you are confirming reproduction of this issue?

**Comment by rcgokhale** [comment]
This is affecting us as well. All our CI/CD pipelines are broken and kind of P1 for us. Issue seems to appear only when "AKS-managed Azure Active Directory" option is enabled and "az aks command invoke" is used. 

We use "az aks command invoke" on Microsoft hosted agents on azure devops with private cluster enabled. 

kubectl get pods -n aks-command
command-527f7f3d04ab440da4fb36229fe57d39   0/1     Init:Error   0          5m59s

kubectl logs command-ed4909772b794cd68bcc1e7ded55cdad  -n aks-command
Defaulted container "user-command" out of: user-command, init-command (init)
Error from server (BadRequest): container "user-command" in pod "command-ed4909772b794cd68bcc1e7ded55cdad" is terminated.

**Comment by andyliuliming** [comment]
fix released. please check.

**Comment by rcgokhale** [comment]
@andyliuliming Many thanks for quick response and fix, It is now working for us.

**Comment by datadot** [comment]
@andyliuliming confirmed - thanks for the fix.

**Comment by dennistandian** [comment]
Hi, I am encountering the same issue now. 

Which version is the bug fix released in?

Do I need to update my AZ CLI version to the latest (2.38.0)?

**Comment by navba-MSFT** [comment]
@tdn-revan Please use the [most recent version ](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli)of Az CLI and check if that helps. If you still face the same issue after updating please open a new issue [here](https://github.com/Azure/azure-cli/issues).

**Comment by tdn-revan** [comment]
> @tdn-revan Please use the [most recent version ](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli)of Az CLI and check if that helps. If you still face the same issue after updating please open a new issue [here](https://github.com/Azure/azure-cli/issues).

Still faced the same error even with the latest version (2.38.0). Have raised another issue [here](https://safe.menlosecurity.com/https://github.com/Azure/azure-cli/issues/23203).
