### ISSUE TITLE
Azure CLI cannot download "azcopy" (409 Conflict)

### ISSUE THREAD

**Issue by ramondeklein** [Azure/azure-cli#24277]
## Describe the bug

The command `az storage blob sync` seems to use [`azcopy`](https://github.com/Azure/azure-storage-azcopy) under the hood. This binary isn't included in the Docker image and is downloaded when needed.

**Errors:**
The download fails on a lot of systems with error `409 Conflict`. The download location is https://azcopyvnext.azureedge.net/release20211027/azcopy_linux_amd64_10.13.0.tar.gz and it is broken since a few hours.

## To Reproduce:
Any `az storage blob sync` command will generate this error when it's trying to invoke `azcopy`.

## Expected Behavior
I would expect that the Docker container is self-supporting and would have `azcopy` already in the `/root/bin` folder, so it doesn't need to download it.

## Environment Summary
```
Linux-5.15.68.1-microsoft-standard-WSL2-x86_64-with, Alpine Linux v3.16
Python 3.10.7
Installer: DOCKER

azure-cli 2.41.0
```

**Comment by ramondeklein** [comment]
See also https://github.com/Azure/azure-storage-azcopy/issues/1933

**Comment by ValKiriann** [comment]
thanks for the linking the issues :)

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
@zezha-msft Can you help with this `azcopy` download issue?

**Comment by zezha-msft** [comment]
https://azcopyvnext.azureedge.net/release20211027/azcopy_linux_amd64_10.13.0.tar.gz is working now as far as I can tell. Maybe it was a transient issue?

**Comment by Goz3rr** [comment]
Still failing from one computer for me, but working when trying from another. DNS seems to resolve to the same IP for both so I'm not sure where the difference is.

```xml
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:31d075a6-101e-0074-4ce8-e3be2f000000 Time:2022-10-19T18:26:55.3022744Z</Message>
</Error>
```

**Comment by zezha-msft** [comment]
@Goz3rr thanks for the feedback. It seems that there were some issues with our distribution account. It should be all fixed now. Please kindly retry and let us know. Thanks!

**Comment by ValKiriann** [comment]
Hi @zezha-msft,  I can confirm it is still happening to us. I just tried to launch one of our deploy pipelines and it continues with the same error: 

##[error]ERROR: Connection error while attempting to download azcopy 10.13.0. You could also install the specified azcopy version to /home/AzDevOps/bin manually. (HTTP Error 409: Conflict)

**Comment by Goz3rr** [comment]
Same here, although it does seem to be changing. Computers where it worked yesterday now don't work, and vice versa.

**Comment by ramondeklein** [comment]
For anybody that is experiencing issues with this. If you install `azcopy` locally, then it won't try to download. Make sure you install the 10.13.0 version into `$HOME/bin`. You can download from https://azcopyvnext.azureedge.net/release20211027/azcopy_linux_amd64_10.13.0.tar.gz (if it works and otherwise try to use a different DNS, like `1.1.1.1` or `8.8.8.8`).

Details on the actual stuff that is going on in `az` is here: https://github.com/Azure/azure-cli/blob/main/src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py

**Comment by ramondeklein** [comment]
> @Goz3rr thanks for the feedback. It seems that there were some issues with our distribution account. It should be all fixed now. Please kindly retry and let us know. Thanks!

It would be much better to include `azcopy` in the Docker image, so it doesn't need to download it. We use Docker images to have isolated build environments, but downloading "arbitrary" stuff inside the image breaks that philosophy. The `azcopy` version is fixed, so I don't see any issues to download it. It's pretty big file, so it would also save a lot of bandwidth too.

**Comment by dds-julian-duerr** [comment]
I'm using the `AzureCLI@2` task from Azure DevOps in our pipeline and it also runs in this issue when I try to do a `az storage blob sync ...`.

Any workarounds I could use here to get it working again?

**Comment by almenscorner** [comment]
We are also running in to this issue now on our Azure DevOps Linux pipelines and trying to run it on a mac. I tried the link above @ramondeklein but can not get it to work, also tried different DNS.

Any other way we can work around this right now to get the pipelines back up?

**Comment by juhl7** [comment]
We had this issue today. Pipeline in AzureDevops, on MS provided build agent, using AzureCLI@2 task.
My workaround that helped was to upgrade to the ubuntu-latest vm image.

Change applied to deploy.yaml:

pool:
-  vmImage: 'ubuntu-20.04'
+  vmImage: 'ubuntu-latest'

**Comment by dds-julian-duerr** [comment]
> We had this issue today. Pipeline in AzureDevops, on MS provided build agent, using AzureCLI@2 task. My workaround that helped was to upgrade to the ubuntu-latest vm image.
> 
> Change applied to deploy.yaml:
> 
> pool:
> 
> * vmImage: 'ubuntu-20.04'
> 
> * vmImage: 'ubuntu-latest'

We already use the 'ubuntu-latest' image and that also has this issue. At least in our Azure DevOps pipelines.

**Comment by almenscorner** [comment]
> 

Same for us

**Comment by almenscorner** [comment]
> > We had this issue today. Pipeline in AzureDevops, on MS provided build agent, using AzureCLI@2 task. My workaround that helped was to upgrade to the ubuntu-latest vm image.
> > Change applied to deploy.yaml:
> > pool:
> > 
> > * vmImage: 'ubuntu-20.04'
> > * vmImage: 'ubuntu-latest'
> 
> We already use the 'ubuntu-latest' image and that also has this issue. At least in our Azure DevOps pipelines.

Same for us

**Comment by ramondeklein** [comment]
@zezha-msft replied in the linked issue. See https://github.com/Azure/azure-storage-azcopy/issues/1933#issuecomment-1286248816

**Comment by almenscorner** [comment]
For me, these two are working:

- https://azcopyvnext.azureedge.net/release20211027/azcopy_linux_amd64_10.13.0.tar.gz
- https://azcopyvnext.azureedge.net/release20210415/azcopy_darwin_amd64_10.13.0.zip

**Comment by zezha-msft** [comment]
Hey folks, we are really sorry for this issue. We figured out that the only way to fix the links (in the short-term) is just to purge the links from the CDN. The problem occurs for certain geographies but we have no way of telling. 

The links used for Az CLI should all be fixed now. Please let me know if you are still blocked.

We will look into long-term ways to diversify the distribution of the tool.
