### ISSUE TITLE
az keyvault list-deleted: Resource provider 'Microsoft.KeyVault' failed to return collection response for type 'deletedManagedHSMs'

### ISSUE THREAD

**Issue by PetrPospisil** [Azure/azure-cli#25444]
## Describe the bug
Blocking issue... Happening since 9am CET. Seems like broken azure call. Happening also in v 2.40.0. Thx for help.

**Command Name**
`az keyvault list-deleted`

**Errors:**
```
cli.azure.cli.core.azclierror: (ProviderError) Resource provider 'Microsoft.KeyVault' failed to return collection response for type 'deletedManagedHSMs'.
Code: ProviderError
Message: Resource provider 'Microsoft.KeyVault' failed to return collection response for type 'deletedManagedHSMs'.
az_command_data_logger: (ProviderError) Resource provider 'Microsoft.KeyVault' failed to return collection response for type 'deletedManagedHSMs'.
Code: ProviderError
Message: Resource provider 'Microsoft.KeyVault' failed to return collection response for type 'deletedManagedHSMs'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

[out.txt](https://github.com/Azure/azure-cli/files/10723381/out.txt)
- `az keyvault list-deleted`

## Expected Behavior
No error when running this call

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
error returned from service

need keyvault service side to take a look

**Comment by kaylumah** [comment]
We have been running into this issue since yesterday

**Comment by jayintheoffice** [comment]
This bug is reproduceable on 2.42 and 2.45, but the command works as expected on 2.30.

**Comment by emanjogu** [comment]
If you want to list deleted vaults, specifying '--resource-type vault' seems to work still with v.2.45 of azure-cli.

**Comment by kaylumah** [comment]
@emanjogu so the full command you run is `az keyvault list-deleted --resource-type vault` ?

**Comment by emanjogu** [comment]
The command I run is:
az keyvault list-deleted --subscription "<name of your subscription" --resource-type vault

That is for listing deleted keyvaults. The other resource type 'hsm' seems to be the part not working.

**Comment by evelyn-ys** [comment]
Listing deleted hsm would be fixed by tomorrow EOD -- said by keyvault service backend engineer.

**Comment by jayintheoffice** [comment]
Confirmed. Specifying resource-type works. @emanjogu you are a god among men. Thankyou.

**Comment by PetrPospisil** [comment]
Fixed, we can close it.

**Comment by raymonvtu** [comment]
i read that this issue would have been solved in feb yet i still get the same error when trying to view deleted hsm's in version 2.47

**Comment by karlrissland** [comment]
I just upgraded and am still getting the error with version 2.53.1

<img width="790" alt="image" src="https://github.com/Azure/azure-cli/assets/9871029/38c63ddd-f155-4a56-9a59-631f729a854c">
