### ISSUE TITLE
az webapp up | post-deployment Python error

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#25599]
From: Dina Berry (SHE/HER) <[Dina.Berry@microsoft.com](mailto:Dina.Berry@microsoft.com)> 
Sent: Friday, February 24, 2023 5:24 PM
To: Delora Bradish <[Delora.Bradish@microsoft.com](mailto:Delora.Bradish@microsoft.com)>
Subject: Would you report this or no? 

While deploying a JS app with az web app up, I get an error for python after the deployment. **What would you expect a customer to do with this?** I don't know if I should ignore it or do something about it? 

dina [ ~/js-e2e-web-app-easy-auth-app-to-app/frontend ]$ **az webapp up --name diberry-frontend-aad --sku FREE --location "West Europe" --os-type Linux --logs --runtime "NODE:18-lts"** 
/usr/lib64/az/lib/python3.9/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
The webapp 'diberry-frontend-aad' doesn't exist
Creating Resource group 'diberry-app-service-aad' ...
Resource group creation complete
Creating AppServicePlan 'diberry_asp_0703' ...
Creating webapp 'diberry-frontend-aad' ...
Configuring default logging for the app, if not already enabled
Creating zip with contents of dir /home/dina/js-e2e-web-app-easy-auth-app-to-app/frontend ...
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
You can launch the app at [http://diberry-frontend-aad.azurewebsites.net](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdiberry-frontend-aad.azurewebsites.net%2F&data=05%7C01%7CDelora.Bradish%40microsoft.com%7C66470d90b25c46d7a0fe08db191736f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638131359743839367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1wXX4IbeDqoHCzp11gcF%2F2K0TZH49z0LGd6SuKsddlI%3D&reserved=0)
Configuring default logging for the app, if not already enabled
2023-02-25T00:17:17  Welcome, you are now connected to log-streaming service.
**Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 697, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''**

During handling of the above exception, **another exception** occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 701, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, **another exception** occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 2656, in _get_log
    for chunk in r.stream():
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by asrlata** [comment]
Facing the same error. Please suggest the possible reasons and resolutions for this

**Comment by asrlata** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 697, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/response.py", line 701, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()

**Comment by rfernandezdo** [comment]
In my case, I could fix it temporally after installing the latest version of paramiko in cloud shell and modify az locally. This are my detailled steps without any kind of guarantee :) :

python3 -m pip install paramiko==3.0.0
cp /usr/bin/az  /home/myuser/az


az modified:

#!/usr/bin/env bash
bin_dir=`cd "/usr/bin/"; pwd`
python_cmd=python3
if command -v python3.9 &>/dev/null; then python_cmd=python3.9; fi
AZ_INSTALLER=RPM PYTHONPATH="$bin_dir/../lib64/az/lib/python3.9/site-packages:/home/myuser/.local/lib/python3.9/site-packages/" $python_cmd -sm azure.cli "$@


Before:

az webapp list --query [0].name --output tsv
/usr/lib64/az/lib/python3.9/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms. Blowfish,
seguropaco
  
 After:
./az webapp list --query [0].name --output tsv
seguropaco

**Comment by seligj95** [comment]
Can you try updating to the latest CLI version 2.46.0 and see if the issue still persists? This should be fixed with an update we recently made.

**Comment by seligj95** [comment]
Closing as this is addressed. Please update to the latest CLI. Please re-open if still an issue.

**Comment by pamelafox** [comment]
I just got the same error, and I do have 2.46.0

Here are my logs:

```
(.venv) ms-identity-python-webapp % az webapp up --runtime PYTHON:3.9 --sku B1 --logs
The webapp 'ashy-mushroom-ef88daf52c5742fb96666e2eeb512ef0' doesn't exist
Creating Resource group 'pamelafox_rg_0371' ...
Resource group creation complete
Creating AppServicePlan 'pamelafox_asp_2592' ...
Creating webapp 'ashy-mushroom-ef88daf52c5742fb96666e2eeb512ef0' ...
Configuring default logging for the app, if not already enabled
Creating zip with contents of dir /Users/pamelafox/ms-identity-python-webapp ...
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
You can launch the app at http://ashy-mushroom-ef88daf52c5742fb96666e2eeb512ef0.azurewebsites.net
Configuring default logging for the app, if not already enabled
2023-03-25T22:21:27  Welcome, you are now connected to log-streaming service.
Exception in thread Thread-1 (_get_log):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 697, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 701, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2688, in _get_log
    for chunk in r.stream():
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 752, in read_chunked
    with self._error_catcher():
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```


az version says:

```
{
  "azure-cli": "2.46.0",
  "azure-cli-core": "2.46.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "containerapp": "0.3.22",
    "containerapp-compose": "0.2.2"
  }
}
```

My environment: VS Code Terminal, inside a Python3.10 virtual env, on a Mac M1 running Ventura

**Comment by seligj95** [comment]
reopening, needs further investigation

**Comment by mwartell** [comment]
I have just hit the same error as listed above https://github.com/Azure/azure-cli/issues/25599#issuecomment-1483936086

This is in Ubuntu 22.04 in WSL with `az version` giving:

```
{
  "azure-cli": "2.46.0",
  "azure-cli-core": "2.46.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```

**Comment by btardif** [comment]
+ @sarsharma to help with log stream angle

**Comment by btardif** [comment]
this should be resolved once we hook this up to the new deployment status API

**Comment by calcium** [comment]
Still happening.

$  az --version
azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/ccang/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Aug 31 2023, 09:13:51) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by tulikac** [comment]
Evaluating if this could be a fix on the client-side rather than deployment status API. @sarsharma please take a look.

**Comment by dbradish-microsoft** [comment]
CCing @diberry

**Comment by JimacoMS4** [comment]
I'm getting similar behavior trying to deploy a Python app from CLI running in a Windows terminal in VS Code.

I'm using this article: [Quickstart: Deploy a Python (Django or Flask) web app to Azure App Service](https://learn.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=django%2Cwindows%2Cazure-cli%2Cvscode-deploy%2Cdeploy-instructions-azportal%2Cterminal-bash%2Cdeploy-instructions-zip-azcli), but using Python 3.11. I've tried it with 3.10 also. 

I’m using the most current version of the Azure CLI:

```
(.venv) C:\test-repos\msdocs-python-django-webapp-quickstart>az --version
azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\v-jibrannian\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```
Here's the az weapp up command and output: 
```
(.venv) C:\test-repos\msdocs-python-django-webapp-quickstart>az webapp up --runtime PYTHON:3.11 --sku B1 --logs --location eastus2 --name jimaco-whitenoise-web-app-3
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\OpenSSL/_util.py:6: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.
The webapp 'jimaco-whitenoise-web-app-3' doesn't exist
Creating Resource group 'v-jibrannian_rg_8876' ...
Resource group creation complete
Creating AppServicePlan 'v-jibrannian_asp_5264' or Updating if already exists
Creating webapp 'jimaco-whitenoise-web-app-3' ...
Configuring default logging for the app, if not already enabled
Creating zip with contents of dir C:\test-repos\msdocs-python-django-webapp-quickstart ...
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
You can launch the app at [http://jimaco-whitenoise-web-app-3.azurewebsites.net](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fjimaco-whitenoise-web-app-3.azurewebsites.net%2F&data=05%7C01%7Cv-jibrannian%40microsoft.com%7Ccb81abbd2fc64e06c98c08dbbedbb4e8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313623073477823%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6%2FON7tKUfDDJ1ZOqFENfLlsZ311pvTt8747UDNusE%2F8%3D&reserved=0)
Configuring default logging for the app, if not already enabled
2023-09-26T20:54:58  Welcome, you are now connected to log-streaming service.
Exception in thread Thread-1 (_get_log):
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 761, in _update_chunk_length
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 444, in _error_catcher
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 828, in read_chunked
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 765, in _update_chunk_length
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2852, in _get_log
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 624, in stream
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 816, in read_chunked
  File "contextlib.py", line 153, in __exit__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 461, in _error_catcher
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
Terminate batch job (Y/N)? y
```

**Comment by btardif** [comment]
@tulikac do we have any updates on this?

**Comment by btardif** [comment]
This is being addressed: https://github.com/Azure/azure-cli/pull/27471
