### ISSUE TITLE
"az aks update" ignores --load-balancer-outbound-ports 0

### ISSUE THREAD

**Issue by MaxHorstmann** [Azure/azure-cli#27071]
### Describe the bug

[az aks update](https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-update) ignores the `--load-balancer-outbound-ports` (load balancer outbound allocated ports) parameter if the intended new value is `0` (which is valid).

We can clearly see in debug that the PUT request to `Microsoft.ContainerService/managedClusters` sends the currently configured value instead of the desired value of 0. 

### Related command

az aks update

### Errors

No error, the 0 parameter is silently ignored

### Issue script & Debug output

Let's set load-balancer-outbound-ports to a non-zero value (8000) first:

```
$ az aks update -n foo -g maxhorstmann-test --load-balancer-managed-outbound-ip-count 1 --load-balancer-outbound-ports 8000 --debug

...
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/137f0351-8235-42a6-ac7a-6b46be2d21c7/resourceGroups/maxhorstmann-test/providers/Microsoft.ContainerService/managedClusters/foo?api-version=2023-02-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
...
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {..."allocatedOutboundPorts": 8000}...
...
```
^^ This is correct.

Now let's try setting load-balancer-outbound-ports to 0:

```
$ az aks update -n foo -g maxhorstmann-test --load-balancer-managed-outbound-ip-count 1 --load-balancer-outbound-ports 0 --debug 
...
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/137f0351-8235-42a6-ac7a-6b46be2d21c7/resourceGroups/maxhorstmann-test/providers/Microsoft.ContainerService/managedClusters/foo?api-version=2023-02-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
...
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {..."allocatedOutboundPorts": 8000}...
...
```

^^ We can see that the PUT request sent the *current* value (8000) instead of the desired *new* value (0). 

### Expected behavior

The PUT request should send `{..."allocatedOutboundPorts": 0}...`

### Environment Summary

azure-cli                         2.50.0 *

core                              2.50.0 *
telemetry                          1.0.8 *

Extensions:
containerapp                      0.3.28

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.50.0_1/libexec/bin/python'
Extensions directory '/Users/maxhorstmann/.azure/cliextensions'

Python (Darwin) 3.10.12 (main, Jul 28 2023, 18:34:01) [Clang 14.0.3 (clang-1403.0.22.14.1)]

### Additional context

IcM 411113950

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
Non customer reported issue. Adding Service team to look into this.

**Comment by FumingZhang** [comment]
ack, taking a look

**Comment by FumingZhang** [comment]
The issue has been fixed in PR #27050 and released with [2.52.0](https://github.com/Azure/azure-cli/milestone/133)

**Comment by rabpoi** [comment]
> The issue has been fixed in PR #27050 and released with [2.52.0](https://github.com/Azure/azure-cli/milestone/133)

Hi Fuming Zhang
Just tested this on my side and it seems issue still present
I am using 2.56.0 CLI version

From my test
 
az aks show --resource-group newResourceGroup --name testenew123 | grep allocatedOutboundPorts
WARNING: The behavior of this command has been altered by the following extension: aks-preview
      "allocatedOutboundPorts": 2048,
 
az aks update -g newResourceGroup -n testenew123 --load-balancer-outbound-ports 0 --debug
 
but after this last command I can see that 2048 remains, when running show command

Can you help please?

**Comment by FumingZhang** [comment]
> WARNING: The behavior of this command has been altered by the following extension: aks-preview

@rabpoi, could you please uninstall aks-preview and try again? Also can you share which version aks-preview are you using (`az version`)? 

@MartinForReal, the previous fix #27050 was applied in azure-cli 2.52.0, but aks-preview relies on [2.49.0](https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azext_aks_preview/azext_metadata.json#L2), so maybe there is still this problem in aks-preview?

**Comment by rabpoi** [comment]
> > WARNING: The behavior of this command has been altered by the following extension: aks-preview
> 
> @rabpoi, could you please uninstall aks-preview and try again? Also can you share which version aks-preview are you using (`az version`)?
> 
> @MartinForReal, the previous fix #27050 was applied in azure-cli 2.52.0, but aks-preview relies on [2.49.0](https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azext_aks_preview/azext_metadata.json#L2), so maybe there is still this problem in aks-preview?

@FumingZhang my aks-preview version is 1.0.0b2

az version
{
  "azure-cli": "2.56.0",
  "azure-cli-core": "2.56.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "1.0.0b2",
    "amg": "1.2.9"
  }
}

**Comment by rabpoi** [comment]
@FumingZhang 
Already uninstall aks-preview and issue still the same
Now new version installed is "aks-preview": "1.0.0b3"

**Comment by FumingZhang** [comment]
@rabpoi
The issue has been fixed in azure-cli since 2.58.0 (#28273) and aks-preview since 2.0.0b7 ([#7230](https://github.com/Azure/azure-cli-extensions/pull/7230)).
