### ISSUE TITLE
v2.51.0: "az keyvault show" fails with invalid api-version

### ISSUE THREAD

**Issue by vedion** [Azure/azure-cli#27109]
### Describe the bug

Hi,

With v2.50.0 the command "az keyvault show" worked as expected.
https://learn.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-show

With v2.51.0 it fails with "The api-version '2023-02-01' is invalid".

Best Regards,
Anders Havn

### Related command

az keyvault show --name "<key vault name>"

### Errors

(InvalidApiVersionParameter) The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter
Message: The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

### Issue script & Debug output

cli.knack.cli: Command arguments: ['keyvault', 'show', '--name', 'dev-mcz-kv-energinet', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01549388>, <function OutputProducer.on_global_arguments at 0x01BBC5C8>, <function CLIQuery.on_global_arguments at 0x01BD1220>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'keyvault': ['azure.cli.command_modules.keyvault']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: keyvault                  0.009        22       133
cli.azure.cli.core: Total (1)                 0.009        22       133
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0  
cli.azure.cli.core: Loaded 22 groups, 133 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : keyvault show
cli.azure.cli.core: Command table: keyvault show
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03DEA4F0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\AndersHavn\.azure\commands\2023-08-07.20-41-15.keyvault_show.14072.log'.
az_command_data_logger: command args: keyvault show --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03E11658>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03E205C8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03E207C0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01BBC610>, <function CLIQuery.handle_query_parameter at 0x01BD1268>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03E20778>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=KeyVaultManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\AndersHavn\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\AndersHavn\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/f7619355-6c67-4100-9a78-1847f30742e2/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/f7619355-6c67-4100-9a78-1847f30742e2/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/f7619355-6c67-4100-9a78-1847f30742e2/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/f7619355-6c67-4100-9a78-1847f30742e2/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/f7619355-6c67-4100-9a78-1847f30742e2/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/f7619355-6c67-4100-9a78-1847f30742e2/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/f7619355-6c67-4100-9a78-1847f30742e2/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 
'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 99cb567e-139a-4bdc-ade1-27de466e1de2
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/c368eed6-4e8e-4f01-9a08-3a43ec1c2c6d/resources?$filter=resourceType%20eq%20%27Microsoft.KeyVault%2Fvaults%27%20and%20name%20eq%20%27dev-mcz-kv-energinet%27&api-version=2015-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fdaf5478-3551-11ee-b77d-546cebdaca8b'
cli.azure.cli.core.sdk.policies:     'CommandName': 'keyvault show'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (MSI) azsdk-python-azure-mgmt-keyvault/10.2.2 Python/3.10.10 (Windows-10-10.0.19045-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/c368eed6-4e8e-4f01-9a08-3a43ec1c2c6d/resources?$filter=resourceType%20eq%20%27Microsoft.KeyVault%2Fvaults%27%20and%20name%20eq%20%27dev-mcz-kv-energinet%27&api-version=2015-11-01 HTTP/1.1" 200 811
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11990'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '00605c34-f563-4cf5-b6f7-2394550c160f'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '00605c34-f563-4cf5-b6f7-2394550c160f'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SWEDENSOUTH:20230807T184116Z:00605c34-f563-4cf5-b6f7-2394550c160f'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 07 Aug 2023 18:41:15 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '811'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[],"nextLink":"https://management.azure.com/subscriptions/c368eed6-4e8e-4f01-9a08-3a43ec1c2c6d/resources?%24filter=resourceType+eq+%27Microsoft.KeyVault%2fvaults%27+and+name+eq+%27dev-mcz-kv-energinet%27&api-version=2015-11-01&%24skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU5VUkVNalEtIiwibmV4dFJvd0tleSI6IjEhMjgwIVF6TTJPRVZGUkRZMFJUaEZORVl3TVRsQk1EZ3pRVFF6UlVNeFF6SkROa1JmUjFKTUxWSkhPakpFUlU1RVN6b3lSRVJFVURveVJFSTZNa1F3TVMxTlNVTlNUMU5QUmxRNk1rVkpUbE5KUjBoVVV6b3lSa0ZEVkVsUFRrZFNUMVZRVXpveVJrRkRWRWxQVGpveU1FZFNUMVZRT2pJd09qSkVPakl3VTBWU1ZrbERSVG95TUVKVlV6b3lNRG95UkRveU1GQlNSVkJTVDBRNk1rUk5RMW82TWtSVFFqb3lSRVZPUlZKSFNVNUZWRG95TURveVJEb3lNRU5CVUVGRFNWUlpUVUZTUzBWVVdFWlNVaTFIVEU5Q1FVdy0ifQ%3d%3d"}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/c368eed6-4e8e-4f01-9a08-3a43ec1c2c6d/resources?$filter=resourceType%20eq%20%27Microsoft.KeyVault/vaults%27%20and%20name%20eq%20%27dev-mcz-kv-energinet%27&api-version=2023-02-01&$skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU5VUkVNalEtIiwibmV4dFJvd0tleSI6IjEhMjgwIVF6TTJPRVZGUkRZMFJUaEZORVl3TVRsQk1EZ3pRVFF6UlVNeFF6SkROa1JmUjFKTUxWSkhPakpFUlU1RVN6b3lSRVJFVURveVJFSTZNa1F3TVMxTlNVTlNUMU5QUmxRNk1rVkpUbE5KUjBoVVV6b3lSa0ZEVkVsUFRrZFNUMVZRVXpveVJrRkRWRWxQVGpveU1FZFNUMVZRT2pJd09qSkVPakl3VTBWU1ZrbERSVG95TUVKVlV6b3lNRG95UkRveU1GQlNSVkJTVDBRNk1rUk5RMW82TWtSVFFqb3lSRVZPUlZKSFNVNUZWRG95TURveVJEb3lNRU5CVUVGRFNWUlpUVUZTUzBWVVdFWlNVaTFIVEU5Q1FVdy0ifQ%3D%3D'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fdaf5478-3551-11ee-b77d-546cebdaca8b'
cli.azure.cli.core.sdk.policies:     'CommandName': 'keyvault show'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (MSI) azsdk-python-azure-mgmt-keyvault/10.2.2 Python/3.10.10 (Windows-10-10.0.19045-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/c368eed6-4e8e-4f01-9a08-3a43ec1c2c6d/resources?$filter=resourceType%20eq%20%27Microsoft.KeyVault/vaults%27%20and%20name%20eq%20%27dev-mcz-kv-energinet%27&api-version=2023-02-01&$skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU5VUkVNalEtIiwibmV4dFJvd0tleSI6IjEhMjgwIVF6TTJPRVZGUkRZMFJUaEZORVl3TVRsQk1EZ3pRVFF6UlVNeFF6SkROa1JmUjFKTUxWSkhPakpFUlU1RVN6b3lSRVJFVURveVJFSTZNa1F3TVMxTlNVTlNUMU5QUmxRNk1rVkpUbE5KUjBoVVV6b3lSa0ZEVkVsUFRrZFNUMVZRVXpveVJrRkRWRWxQVGpveU1FZFNUMVZRT2pJd09qSkVPakl3VTBWU1ZrbERSVG95TUVKVlV6b3lNRG95UkRveU1GQlNSVkJTVDBRNk1rUk5RMW82TWtSVFFqb3lSRVZPUlZKSFNVNUZWRG95TURveVJEb3lNRU5CVUVGRFNWUlpUVUZTUzBWVVdFWlNVaTFIVEU5Q1FVdy0ifQ%3D%3D HTTP/1.1" 400 761
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '4d8c7a21-7c37-451b-a193-9207eb52cfb4'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '4d8c7a21-7c37-451b-a193-9207eb52cfb4'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SWEDENSOUTH:20230807T184116Z:4d8c7a21-7c37-451b-a193-9207eb52cfb4'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 07 Aug 2023 18:41:15 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '761'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/invocation.py", line 113, in _validation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 859, in _validate_arg_level
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_validators.py", line 387, in validate_resource_group_name
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_validators.py", line 110, in _get_resource_group_from_resource_name
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 128, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/keyvault/v2023_02_01/operations/_vaults_operations.py", line 1591, in get_next
azure.core.exceptions.HttpResponseError: (InvalidApiVersionParameter) The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter
Message: The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

cli.azure.cli.core.azclierror: (InvalidApiVersionParameter) The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter
Message: The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
az_command_data_logger: (InvalidApiVersionParameter) The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter
Message: The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03DEA610>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 1.026 seconds (init: 0.238, invoke: 0.788)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4850 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\AndersHavn\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

That the command would not fail like it did with v2.50.0

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
application-insights              0.1.19
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
will be fixed in CLI next release

for now, pls add `--resource-group-name` to unblock customer

**Comment by vedion** [comment]
Hi again,

Thank you for the fast feedback.
It works with "--resource-group" (but not --resource-group-name).

Best Regards,
Anders Havn

**Comment by CraigM-OS** [comment]
I'm getting the same error with `az keyvault set-policy` command

**Comment by OranguTech** [comment]
This appears to have been fixed in v[ 2.52.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.52.0), though it is not in the [release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md) that I can find.

**Comment by Archomeda** [comment]
> This appears to have been fixed in v[ 2.52.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.52.0), though it is not in the [release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md) that I can find.

I had updated to 2.52 after I had this issue in 2.51, but I still encountered this problem sadly.

**Comment by evelyn-ys** [comment]
> > This appears to have been fixed in v[ 2.52.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.52.0), though it is not in the [release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md) that I can find.
> 
> I had updated to 2.52 after I had this issue in 2.51, but I still encountered this problem sadly.

It should not be. Please make sure your CLI has been fully upgraded with all dependencies

**Comment by OranguTech** [comment]
> > > This appears to have been fixed in v[ 2.52.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.52.0), though it is not in the [release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md) that I can find.
> > 
> > 
> > I had updated to 2.52 after I had this issue in 2.51, but I still encountered this problem sadly.
> 
> It should not be. Please make sure your CLI has been fully upgraded with all dependencies

One thing that would help @evelyn-ys if possible, (since it's not in the release notes) would be linking a PR or commit that has the fix?

**Comment by Archomeda** [comment]
> > > This appears to have been fixed in v[ 2.52.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.52.0), though it is not in the [release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md) that I can find.
> > 
> > 
> > I had updated to 2.52 after I had this issue in 2.51, but I still encountered this problem sadly.
> 
> It should not be. Please make sure your CLI has been fully upgraded with all dependencies

Sadly this is definitely the case for me.
az cli says that it's at the latest version 2.52.0, and all my extensions are as well (which is only azure-devops). And using `az keyvault show --name <NAME>` is still giving me the same InvalidApiVersionParameter error.

**Comment by evelyn-ys** [comment]
@OranguTech The fix PR is already linked above https://github.com/Azure/azure-cli/pull/27114
Since this is a SDK issue, what CLI did is just bump SDK to the fixed version so we didn't mention it in our release notes.

@Archomeda I am unsure if the dependency `azure-mgmt-keyvault` SDK is properly upgraded with latest CLI

**Comment by Archomeda** [comment]
@evelyn-ys Ah alright. I'm afraid that I have no clue how to diagnose that. I did find the `az --version` output however:

```
azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2
```
