### ISSUE TITLE
"az sql mi update" - throw exception

### ISSUE THREAD

**Issue by msliwkaFP** [Azure/azure-cli#28371]
### Describe the bug

Command `az sql mi update` with any parameters (eg. "--service-principal-type SystemAssigned" or "--public-data-endpoint-enabled true") throw exception.

Example: 
`az sql mi update --name {SQL_MI_name} --resource-group {RG_name} --public-data-endpoint-enabled true `

Exception:
```
(ManagedInstanceVersionEditionParameterNotAllowedForUsing) Specifying the database format property value is not supported at this time.
Code: ManagedInstanceVersionEditionParameterNotAllowedForUsing
Message: Specifying the database format property value is not supported at this time.
```

### Related command

 az sql mi update --name sliwa-sql-mi --resource-group sliwa-sql-mi  --public-data-endpoint-enabled true

### Errors

(ManagedInstanceVersionEditionParameterNotAllowedForUsing) Specifying the database format property value is not supported at this time.
Code: ManagedInstanceVersionEditionParameterNotAllowedForUsing
Message: Specifying the database format property value is not supported at this time.

### Issue script & Debug output

cli.knack.cli: Command arguments: ['sql', 'mi', 'update', '--name', 'sliwa-sql-mi', '--resource-group', 'sliwa-sql-mi', '--public-data-endpoint-enabled', 'true', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000001D13476B880>, <function OutputProducer.on_global_arguments at 0x000001D1348F6020>, <function CLIQuery.on_global_arguments at 0x000001D134923BA0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'sql': ['azure.cli.command_modules.sql', 'azure.cli.command_modules.sqlvm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: sql                       0.146        62       223
cli.azure.cli.core: sqlvm                     0.075         4        20
cli.azure.cli.core: Total (2)                 0.221        66       243
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 65 groups, 243 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : sql mi update
cli.azure.cli.core: Command table: sql mi update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000001D1377DAA20>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\msliwka\.azure\commands\2024-02-14.13-28-21.sql_mi_update.28840.log'.
az_command_data_logger: command args: sql mi update --name {} --resource-group {} --public-data-endpoint-enabled {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000001D137812E80>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000001D137834F40>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000001D137835080>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000001D1348F60C0>, <function CLIQuery.handle_query_parameter at 0x000001D134923C40>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000001D137834FE0>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=SqlManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\msliwka\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\msliwka\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/0e4f51b3-3fb6-4f54-adfb-22c9ca3a1e72/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/0e4f51b3-3fb6-4f54-adfb-22c9ca3a1e72/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/0e4f51b3-3fb6-4f54-adfb-22c9ca3a1e72/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/0e4f51b3-3fb6-4f54-adfb-22c9ca3a1e72/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/0e4f51b3-3fb6-4f54-adfb-22c9ca3a1e72/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/0e4f51b3-3fb6-4f54-adfb-22c9ca3a1e72/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/0e4f51b3-3fb6-4f54-adfb-22c9ca3a1e72/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 41f178d1-5eee-4aef-b686-d7defdeef6bc
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/a4595d8d-cf7d-4eca-867e-69b24df7ea6e/resourceGroups/sliwa-sql-mi/providers/Microsoft.Sql/managedInstances/sliwa-sql-mi?api-version=2023-05-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '8a104b55-cb34-11ee-bbc5-a83b76a7f51e'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sql mi update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group --public-data-endpoint-enabled --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.57.0 (MSI) azsdk-python-mgmt-sql/4.0.0b15 Python/3.11.7 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/a4595d8d-cf7d-4eca-867e-69b24df7ea6e/resourceGroups/sliwa-sql-mi/providers/Microsoft.Sql/managedInstances/sliwa-sql-mi?api-version=2023-05-01-preview HTTP/1.1" 200 1723
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1723'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'f2ed5a5f-6c1c-4f57-a879-3fa411bf7376'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11951'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '74f94fbe-4c30-4ff2-981e-a0e032c247a3'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'POLANDCENTRAL:20240214T122821Z:74f94fbe-4c30-4ff2-981e-a0e032c247a3'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 14 Feb 2024 12:28:21 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: ....
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=SqlManagementClient
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': ...
msal.application: Broker enabled? False
cli.azure.cli.command_modules.sql.custom: _find_managed_instance_sku_from_capabilities input: {'additional_properties': {}, 'name': None, 'tier': 'GeneralPurpose', 'size': None, 'family': 'Gen5', 'capacity': 8}
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=SqlManagementClient
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': ....
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: c345b79f-8dc8-42a6-91be-2c43029bbc8b
cli.azure.cli.core.sdk.policies: Request URL:...
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '8a104b55-cb34-11ee-bbc5-a83b76a7f51e'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sql mi update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group --public-data-endpoint-enabled --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.57.0 (MSI) azsdk-python-mgmt-sql/4.0.0b15 Python/3.11.7 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/a4595d8d-cf7d-4eca-867e-69b24df7ea6e/providers/Microsoft.Sql/locations/polandcentral/capabilities?include=supportedManagedInstanceVersions&api-version=2020-11-01-preview HTTP/1.1" 200 31807
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '31807'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '48b89fac-6d0d-463b-bf60-72b17d6f7f2e'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11946'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '37b1319c-49d0-4f2f-947a-532f0b72ef1f'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'POLANDCENTRAL:20240214T122821Z:37b1319c-49d0-4f2f-947a-532f0b72ef1f'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 14 Feb 2024 12:28:21 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: ...
cli.azure.cli.command_modules.sql.custom: _assert_capability_available: {'additional_properties': {}, 'name': 'Poland Central', 'supported_server_versions': None, 'supported_managed_instance_versions': [<azure.mgmt.sql.models._models_py3.ManagedInstanceVersionCapability object at 0x000001D139C10C50>], 'status': 'Available', 'reason': None}
cli.azure.cli.command_modules.sql.custom: _get_default_capability: [<azure.mgmt.sql.models._models_py3.ManagedInstanceVersionCapability object at 0x000001D139C10C50>]
cli.azure.cli.command_modules.sql.custom: _get_default_capability found default: {'additional_properties': {}, 'name': '12.0', 'supported_editions': [<azure.mgmt.sql.models._models_py3.ManagedInstanceEditionCapability object at 0x000001D139C10D90>, <azure.mgmt.sql.models._models_py3.ManagedInstanceEditionCapability object at 0x000001D139C10E10>, <azure.mgmt.sql.models._models_py3.ManagedInstanceEditionCapability object at 0x000001D139C1F450>], 'supported_instance_pool_editions': [], 'status': 'Default', 'reason': None}
cli.azure.cli.command_modules.sql.custom: _find_edition_capability: {'additional_properties': {}, 'name': None, 'tier': 'GeneralPurpose', 'size': None, 'family': 'Gen5', 'capacity': 8}; [<azure.mgmt.sql.models._models_py3.ManagedInstanceEditionCapability object at 0x000001D139C10D90>, <azure.mgmt.sql.models._models_py3.ManagedInstanceEditionCapability object at 0x000001D139C10E10>, <azure.mgmt.sql.models._models_py3.ManagedInstanceEditionCapability object at 0x000001D139C1F450>]
cli.azure.cli.command_modules.sql.custom: _find_family_capability: {'additional_properties': {}, 'name': None, 'tier': 'GeneralPurpose', 'size': None, 'family': 'Gen5', 'capacity': 8}; [<azure.mgmt.sql.models._models_py3.ManagedInstanceFamilyCapability object at 0x000001D139C11010>, <azure.mgmt.sql.models._models_py3.ManagedInstanceFamilyCapability object at 0x000001D139C12610>, <azure.mgmt.sql.models._models_py3.ManagedInstanceFamilyCapability object at 0x000001D139C1C8D0>]
cli.azure.cli.command_modules.sql.custom: _find_managed_instance_sku_from_capabilities return: {'additional_properties': {}, 'name': 'GP_Gen5', 'tier': None, 'size': None, 'family': None, 'capacity': None}
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=SqlManagementClient
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': ...
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: f0285920-285e-4e83-843f-37978b1c4391
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/a4595d8d-cf7d-4eca-867e-69b24df7ea6e/resourceGroups/sliwa-sql-mi/providers/Microsoft.Sql/managedInstances/sliwa-sql-mi?api-version=2023-05-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '756'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '8a104b55-cb34-11ee-bbc5-a83b76a7f51e'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sql mi update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group --public-data-endpoint-enabled --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.57.0 (MSI) azsdk-python-mgmt-sql/4.0.0b15 Python/3.11.7 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies:...
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/a4595d8d-cf7d-4eca-867e-69b24df7ea6e/resourceGroups/sliwa-sql-mi/providers/Microsoft.Sql/managedInstances/sliwa-sql-mi?api-version=2023-05-01-preview HTTP/1.1" 400 166
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '166'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '763c28fc-58e7-41e2-ae0a-713a0d4edcfd'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1197'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '45570a31-2812-42b5-afb5-8340b02489c9'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'POLANDCENTRAL:20240214T122822Z:45570a31-2812-42b5-afb5-8340b02489c9'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 14 Feb 2024 12:28:21 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"ManagedInstanceVersionEditionParameterNotAllowedForUsing","message":"Specifying the database format property value is not supported at this time."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 729, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 698, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 240, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 453, in cached_put
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 447, in _put_operation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/sql/operations/_managed_instances_operations.py", line 989, in begin_create_or_update
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/sql/operations/_managed_instances_operations.py", line 855, in _create_or_update_initial
azure.core.exceptions.HttpResponseError: (ManagedInstanceVersionEditionParameterNotAllowedForUsing) Specifying the database format property value is not supported at this time.
Code: ManagedInstanceVersionEditionParameterNotAllowedForUsing
Message: Specifying the database format property value is not supported at this time.

cli.azure.cli.core.azclierror: (ManagedInstanceVersionEditionParameterNotAllowedForUsing) Specifying the database format property value is not supported at this time.
Code: ManagedInstanceVersionEditionParameterNotAllowedForUsing
Message: Specifying the database format property value is not supported at this time.
az_command_data_logger: (ManagedInstanceVersionEditionParameterNotAllowedForUsing) Specifying the database format property value is not supported at this time.
Code: ManagedInstanceVersionEditionParameterNotAllowedForUsing
Message: Specifying the database format property value is not supported at this time.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001D1377DACA0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.891 seconds (init: 0.414, invoke: 2.476)
cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 62, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 55, in <module>
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/decorators.py", line 79, in _wrapped_func
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/telemetry.py", line 532, in _get_secrets_warning_config
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 147, in getboolean
ValueError: Not a boolean: None

telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3712 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\msliwka\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Property "publicDataEndpointEnabled" changed to "true"

### Environment Summary

azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Extensions:
application-insights               1.2.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by msliwkaFP** [comment]
I reverted az cli to version  2.56.0 and it working so only version 2.57.0 is broken

**Comment by msliwkaFP** [comment]
Any news about it? I still have this bug....

**Comment by Roman-Konstantinov** [comment]
The issue has been fixed with Az.Sql module downgrade to version is 4.13.0.

**Comment by msliwkaFP** [comment]
> The issue has been fixed with Az.Sql module downgrade to version is 4.13.0.

This doesn't fix the error, it just bypasses it.

I using this command in Azure DevOps pipeline and agent hosted by Microsoft have always the newest version of AZ CLI (so it won't work there)

**Comment by ptsapralis** [comment]
I have the same problem when attempting to increase the storage capacity of a SQL Managed Instance. I am using the following command:

az sql mi update --subscription <subscription-id> --verbose -g <sql-mi-rg> --name <sql-mi-name> --storage 768GB

Azure CLI version "2.58.0". Tested on different platforms (Mac OS X, WSL, Ubuntu Linux).

Is there any ETA defined for a fix, please?
