### ISSUE TITLE
Unable to create VM with standard security

### ISSUE THREAD

**Issue by matt-boris** [Azure/azure-cli#31191]
### Describe the bug

Hi there,

After upgrading to az v2.71.0, my `az vm create` commands fail with `The value of parameter securityProfile.securityType is invalid.`.

After downgrading the cli via `brew install --build-from-source azure-cli.rb` with the file being taken from https://github.com/Homebrew/homebrew-core/blob/4ebae799157b908501142a9752101fd0e69722ba/Formula/a/azure-cli.rb the cli version is v2.70.0 and works properly with security type of `Standard`.

### Related command

```bash
az vm create --name="az-cli-test" --image="MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition:latest" --resource-group=<your RG here> --computer-name="ImageBuilder" --os-disk-delete-option=Delete --data-disk-delete-option=Delete --nic-delete-option=Delete --nsg-rule=NONE --license-type="Windows_Server" --accept-term --location="eastus" --size="Standard_F32s_v2" --security-type="Standard" --admin-username=<your user here> --admin-password=<your password here>
```

### Errors

Command failed with `The value of parameter securityProfile.securityType is invalid.`

### Issue script & Debug output

<details>
<summary>
Debug output

</summary>

```bash
DEBUG: cli.knack.cli: Command arguments: ['vm', 'create', '--name=********', '--image=MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition:latest', '--resource-group=********', '--computer-name=ImageBuilder', '--os-disk-delete-option=Delete', '--data-disk-delete-option=Delete', '--nic-delete-option=Delete', '--nsg-rule=NONE', '--license-type=Windows_Server', '--accept-term', '--location=eastus', '--size=Standard_F32s_v2', '--security-type=Standard', '--admin-username=********', '--admin-password=********', '--debug']
DEBUG: cli.azure.cli.core.sdk.policies: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/********/resourceGroups/********/providers/Microsoft.Resources/deployments/vm_deploy_Ab3CzBhmNVo0tKDI2MUaMetgowTc7LrJ","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."}]}}
DEBUG: cli.azure.cli.core.sdk.policies: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/********/resourceGroups/********/providers/Microsoft.Resources/deployments/vm_deploy_Ab3CzBhmNVo0tKDI2MUaMetgowTc7LrJ","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."}]}}
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 757, in run
    self._poll()
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 789, in _poll
    raise OperationFailed("Operation failed or canceled")
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 120, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/command_modules/vm/custom.py", line 1139, in create_vm
    LongRunningOperation(cmd.cli_ctx)(client.begin_create_or_update(resource_group_name, deployment_name, deployment))
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 1076, in __call__
    raise exception
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 1063, in __call__
    result = poller.result()
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/_poller.py", line 251, in result
    self.wait(timeout)
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/_poller.py", line 270, in wait
    raise self._exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/_poller.py", line 185, in _start
    self._polling_method.run()
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 772, in run
    raise HttpResponseError(response=self._pipeline_response.http_response, error=err) from err
azure.core.exceptions.HttpResponseError: (DeploymentFailed) At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Code: DeploymentFailed
Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Target: /subscriptions/********/resourceGroups/********/providers/Microsoft.Resources/deployments/vm_deploy_Ab3CzBhmNVo0tKDI2MUaMetgowTc7LrJ
Exception Details:	(InvalidParameter) The value of parameter securityProfile.securityType is invalid.
	Code: InvalidParameter
	Message: The value of parameter securityProfile.securityType is invalid.
	Target: securityProfile.securityType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/arm.py", line 109, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpeDEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 757, in run
    self._poll()
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 789, in _poll
    raise OperationFailed("Operation failed or canceled")
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 120, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/command_modules/vm/custom.py", line 1139, in create_vm
    LongRunningOperation(cmd.cli_ctx)(client.begin_create_or_update(resource_group_name, deployment_name, deployment))
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 1076, in __call__
    raise exception
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 1063, in __call__
    result = poller.result()
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/_poller.py", line 251, in result
    self.wait(timeout)
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/_poller.py", line 270, in wait
    raise self._exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/_poller.py", line 185, in _start
    self._polling_method.run()
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 772, in run
    raise HttpResponseError(response=self._pipeline_response.http_response, error=err) from err
azure.core.exceptions.HttpResponseError: (DeploymentFailed) At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Code: DeploymentFailed
Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Target: /subscriptions/********/resourceGroups/********/providers/Microsoft.Resources/deployments/vm_deploy_Ab3CzBhmNVo0tKDI2MUaMetgowTc7LrJ
Exception Details:	(InvalidParameter) The value of parameter securityProfile.securityType is invalid.
	Code: InvalidParameter
	Message: The value of parameter securityProfile.securityType is invalid.
	Target: securityProfile.securityType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/arm.py", line 109, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OperationFailed' object has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 734, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_job
    return cmd_copy.exception_handler(ex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/arm.py", line 112, in handle_template_based_exception
    raise_subdivision_deployment_error(ex.response.internal_response.text, ex.error.code if ex.error else None)
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/arm.py", line 104, in raise_subdivision_deployment_error
    raise DeploymentError(error_message)
azure.cli.core.azclierror.DeploymentError: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/********/resourceGroups/********/providers/Microsoft.Resources/deployments/vm_deploy_Ab3CzBhmNVo0tKDI2MUaMetgowTc7LrJ","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."}]}}

rationFailed' object has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 734, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_job
    return cmd_copy.exception_handler(ex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/arm.py", line 112, in handle_template_based_exception
    raise_subdivision_deployment_error(ex.response.internal_response.text, ex.error.code if ex.error else None)
  File "/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/lib/python3.12/site-packages/azure/cli/core/commands/arm.py", line 104, in raise_subdivision_deployment_error
    raise DeploymentError(error_message)
azure.cli.core.azclierror.DeploymentError: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/********/resourceGroups/********/providers/Microsoft.Resources/deployments/vm_deploy_Ab3CzBhmNVo0tKDI2MUaMetgowTc7LrJ","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."}]}}

ERROR: cli.azure.cli.core.azclierror: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/********/resourceGroups/********/providers/Microsoft.Resources/deployments/vm_deploy_Ab3CzBhmNVo0tKDI2MUaMetgowTc7LrJ","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."}]}}
ERROR: cli.azure.cli.core.azclierror: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/********/resourceGroups/********/providers/Microsoft.Resources/deployments/vm_deploy_Ab3CzBhmNVo0tKDI2MUaMetgowTc7LrJ","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."}]}}
ERROR: az_command_data_logger: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/********/resourceGroups/********/providers/Microsoft.Resources/deployments/vm_deploy_Ab3CzBhmNVo0tKDI2MUaMetgowTc7LrJ","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."}]}}
ERROR: az_command_data_logger: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/********/resourceGroups/********/providers/Microsoft.Resources/deployments/vm_deploy_Ab3CzBhmNVo0tKDI2MUaMetgowTc7LrJ","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."}]}}
```

</details>

### Expected behavior

The VM is created, as it does in v2.70.0.

### Environment Summary

```
azure-cli                         2.71.0

core                              2.71.0
telemetry                          1.1.0

Extensions:
image-copy-extension              0.2.13

Dependencies:
msal                            1.31.2b1
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.71.0/libexec/bin/python'
Config directory '/Users/mboris/.azure'
Extensions directory '/Users/mboris/.azure/cliextensions'

Python (Darwin) 3.12.9 (main, Feb  4 2025, 14:38:38) [Clang 16.0.0 (clang-1600.0.26.6)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nvzard** [comment]
I am also facing the same issue. It broke my deployments.

**Comment by SergeyVartanov** [comment]
Same issue with Azure PowerShell
...
$vm_config = Add-AzVMNetworkInterface -VM $vm_config -Id XXXX
...
New-AzVM -ResourceGroupName "rg1" -Location $Location -VM $vm_config

Explicit configuration of SecurityType does not help
$vm_config = Set-AzVMSecurityProfile -VM $vm_config -SecurityType "Standard"

This is a critical regression.

**Comment by yagmurbaydogan** [comment]
having the same issue

**Comment by AjKundnani** [comment]
> Please on-board subscription to feature flag `Microsoft.Compute\UseStandardSecurityType` for bypassing Trusted launch as default experience and using `securityType = Standard`.
> 
> Currently this feature flag is using manual approval, if you can share the sub ID through email at [ajay.kundnani@microsoft.com](mailto:ajay.kundnani@microsoft.com), I can get it added to un-block. We're actively working to make this feature registration as self-serve and auto-approve.

@yagmurbaydogan @SergeyVartanov @nvzard - Same response as above, please do the needful to onboard to required feature registration.

**Comment by CyanDevs** [comment]
Customer experience is not great and should be improved. Any plans on updating the error message and documentation to reflect the registration requirement for the Standard security type? https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create

**Comment by matt-boris** [comment]
> Bumping this one, is there a hotfix on the way for this?

@USBAkimbo fwiw, adding the feature flag fixes this issue for now https://github.com/Azure/azure-cli/issues/31191#issuecomment-2784205683

**Comment by GalinKarabadzhakov** [comment]
Here is my full vm create script:
VM_NAME="gh-runner-01"
RESOURCE_GROUP="server-automation"
VM_IMAGE="/subscriptions//resourceGroups/server-automation-sig/providers/Microsoft.Compute/galleries//images/RHEL9/versions/1.[2]\https://github.com/***/infrastructure/actions/runs/***/job/4038850653002503.04"
ADMIN_USERNAME="***"
REPO_URL="***"

echo "Creating VM: $VM_NAME"
az vm create
--resource-group $RESOURCE_GROUP
--name $VM_NAME
--image $VM_IMAGE
--admin-username $ADMIN_USERNAME
--size Standard_D2s_v[3]
--tags Environment=Test
--generate-ssh-keys
--security-type Standard \
--nic-delete-option delete
--os-disk-delete-option delete
--authentication-type ssh
--assign-identity

```
Creating VM: gh-runner-01

WARNING: Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch.
ERROR: "status":"Failed","error":"code":"DeploymentFailed","target":"/subscriptions//resourceGroups/server-automation/providers/Microsoft.Resources/deployments/vm_deploy_J3kyyueySsbWD3zH2V[9]([https://github.com/***/infrastructure/actions/runs/14401629847/job/40388506530nz0XJFFbkrbl3","message":"At](https://github.com/***/infrastructure/actions/runs/14401629847/job/40388506530nz0XJFFbkrbl3%22,%22message%22:%22At) least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":["code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."]****

```
GalinKarabadzhakov

**Comment by dixon-cox** [comment]
Is there any update on this issue?  This has broken my deployment pipelines.

**Comment by USBAkimbo** [comment]
@dixon-cox the current workaround is to downgrade Azure CLI from `2.71.0` to `2.70.0`

Here's my VMSS template image build pipeline for reference if it helps

```
trigger: none # Prevents the pipeline from running when any random commit to a branch is made

schedules:
  - cron: "0 0 1 * *" # Run on the 1st day of every month at 00:00
    displayName: ADO pipeline agent VMSS image build
    always: true # Required to run daily
    branches:
      include:
        - develop

pool:
  vmImage: "ubuntu-latest" # MS hosted pipeline agent

variables:
  - name: SERVICE_CONNECTION_NAME
    value: "connection" # Name of the service connection as it's displayed in ADO
  - name: VMSS_RESOURCE_GROUP
    value: "rg1"
  - name: VM_NAME
    value: "temp-vm"
  - name: VM_IMAGE
    value: "Ubuntu2204"
  - name: VM_SIZE
    value: "Standard_D4as_v4"
  - name: VM_DISK_SIZE_GB
    value: "64"
  - name: VMSS_NAME
    value: "vmss"

jobs:
  - job: BuildVMSSImage
    displayName: Build VMSS image
    steps:
      - task: Bash@3
        displayName: "Send image build is starting Slack notification"
        inputs:
          targetType: inline
          script: |
            PIPELINE_URL="$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"<$PIPELINE_URL|Monthly ADO pipeline agent VMSS build is starting>\"}" $(SLACK_URL)

      - task: Bash@3
        displayName: "Install Azure CLI v2.70.0 for #9919" # https://github.com/Azure/azure-cli/issues/31191
        inputs:
          targetType: inline
          script: |
            # Remove current Azure CLI
            sudo apt-get remove -y azure-cli
            
            # Install specific version from Microsoft repo
            curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
            sudo apt-get update
            sudo apt-get install -y azure-cli=2.70.0-1~jammy
            
            # Verify version
            az --version

      - task: AzureCLI@2
        displayName: Build VMSS image
        inputs:
          azureSubscription: $(SERVICE_CONNECTION_NAME)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # Exit with an error if a command fails
            set -e

            echo "=== Creating temp VM ==="
            VM_INFO=$(az vm create \
              --resource-group $(VMSS_RESOURCE_GROUP) \
              --name $(VM_NAME) \
              --image $(VM_IMAGE) \
              --security-type Standard \
              --location westeurope \
              --admin-username azureuser \
              --generate-ssh-keys \
              --size $(VM_SIZE) \
              --os-disk-size-gb $(VM_DISK_SIZE_GB) \
              -o json)

            # Extract the public IP address
            VM_IP=$(echo $VM_INFO | jq -r .publicIpAddress)
            echo "VM Public IP: $VM_IP"

            echo "=== Sleeping for 30s to wait for the VM to be ready ==="
            sleep 30

            echo "=== Configuring VM with Ansible ==="
            export ANSIBLE_HOST_KEY_CHECKING=False
            export ANSIBLE_FORCE_COLOR=1
            ansible-playbook -i "$VM_IP," -u azureuser ansible/playbooks/apa-vmss-image/apa-vmss-image.yml

            echo "=== Sleep for 30s to allow VM to generalize ==="
            sleep 30

            echo "=== Deallocating VM ==="
            az vm deallocate \
              --resource-group $(VMSS_RESOURCE_GROUP) \
              --name $(VM_NAME)

            echo "=== Marking VM as generalized ==="
            az vm generalize \
              --resource-group $(VMSS_RESOURCE_GROUP) \
              --name $(VM_NAME)

            # Get current timestamp in YYYY-MM-DD--HH-MM format
            timestamp=$(date '+%Y-%m-%d--%H-%M')

            echo "=== Creating VMSS image ==="
            az image create \
              --resource-group $(VMSS_RESOURCE_GROUP) \
              --source $(VM_NAME) \
              --hyper-v-generation V2 \
              --name apa-image-${timestamp}

            echo "=== Updating VMSS to use new image ==="
            IMAGE_ID=$(az image show \
            --resource-group $(VMSS_RESOURCE_GROUP) \
            --name apa-image-${timestamp} \
            --query 'id' \
            --output tsv)

            az vmss update \
              --resource-group $(VMSS_RESOURCE_GROUP) \
              --name $(VMSS_NAME) \
              --set virtualMachineProfile.storageProfile.imageReference.id=$IMAGE_ID

            echo "=== Deleting VMSS images older than 90 days ==="
            CUTOFF_DATE=$(date -d "90 days ago" +%Y-%m-%d)

            OLD_IMAGES=$(az image list \
              --resource-group $(VMSS_RESOURCE_GROUP) \
              --query "[].name" \
              --output tsv)

            for IMAGE in $OLD_IMAGES; do
              # Get the YYYY-MM-DD string from the image name
              IMAGE_DATE=$(echo $IMAGE | grep -oP '\d{4}-\d{2}-\d{2}')

              # Convert dates to Unix time
              IMAGE_SECONDS=$(date -d "$IMAGE_DATE" +%s)
              CUTOFF_SECONDS=$(date -d "$CUTOFF_DATE" +%s)

              if [[ $IMAGE_SECONDS < $CUTOFF_SECONDS ]]; then
                echo "Deleting image: $IMAGE"
                az image delete \
                    --resource-group $(VMSS_RESOURCE_GROUP) \
                    --name "$IMAGE" \
                    --yes
              fi
            done

      - task: Bash@3
        displayName: "Send image build is complete Slack notification"
        inputs:
          targetType: inline
          script: |
            PIPELINE_URL="$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"<$PIPELINE_URL|Monthly ADO pipeline agent VMSS build completed successfully>\"}" $(SLACK_URL)

  - job:
    displayName: Cleanup temp VM resources
    dependsOn: BuildVMSSImage
    condition: always() # Run cleanup even if previous job fails
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(SERVICE_CONNECTION_NAME)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            for attempt in {1..10}; do
              echo "=== Cleaning up temporary resources attempt $attempt/10 ==="
              # Find and delete all resources containing $(VM_NAME)
              for resource in $(az resource list --resource-group $(VMSS_RESOURCE_GROUP) --query "[?contains(name, '$(VM_NAME)')].id" -o tsv); do
                  echo "Deleting resource: $resource"
                  az resource delete --ids "$resource" --verbose
                  sleep 5
              done
            done

  - job: FailNotification
    displayName: Failure Notification
    dependsOn: BuildVMSSImage
    condition: failed()
    steps:
      - task: Bash@3
        displayName: "Send image build failed Slack notification"
        inputs:
          targetType: inline
          script: |
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"ERROR: Monthly ADO pipeline agent VMSS build failed - please check the logs\"}" $(SLACK_URL)
```

**Comment by dixon-cox** [comment]
Thanks @USBAkimbo, I will test this over the weekend.  I attempted something similar yesterday, but could not find a working download location for  2.70.0..

**Comment by dixon-cox** [comment]
Thanks @USBAkimbo your suggestion worked and I am now able to deploy VMs from my pipeline again.

**Comment by windoys** [comment]
> [@matt-boris](https://github.com/matt-boris) - Please on-board subscription to feature flag `Microsoft.Compute\UseStandardSecurityType` for bypassing Trusted launch as default experience and using `securityType = Standard`.
> 
> You can self-register the feature flag on subscription using PowerShell or CLI. Refer to [Set up preview features in Azure subscription](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/preview-features)
> 
> **Note**: This is not a preview feature, it is implemented such a way to ensure users consciously bypass the foundational compute security offered by Trusted launch.

Thanks , [AjKundnani](https://github.com/AjKundnani), After adding this subscription, I solved the problem of VM creation failure in version 2.71.0. 
However, I have a question: If some of my environments are still earlier versions of Azure-CLI, will adding this subscription under my account cause VM creation problems in these environments?

**Comment by AjKundnani** [comment]
> Thanks , [AjKundnani](https://github.com/AjKundnani), After adding this subscription, I solved the problem of VM creation failure in version 2.71.0. However, I have a question: If some of my environments are still earlier versions of Azure-CLI, will adding this subscription under my account cause VM creation problems in these environments?

@windoys - No, adding this feature flag will not impact VM creations using older versions of CLI. This flag is required only where `--security-type=Standard` is explicitly added to command.

**Comment by vg19gupta** [comment]
Hi @AjKundnani I am owner of my azure subscription but still i don't see Microsoft.Compute\UseStandardSecurityType in the preview feature list.

**Comment by sdemura** [comment]
So am I reading this issue as 'wont fix' by azure-cli team? This is absurd.

**Comment by USBAkimbo** [comment]
@AjKundnani for clarification, is there a reason why this change has been made?

I don't see another way to create Azure VM images without using a VM with a standard security type, and needing to add a specific option in Azure for this seems strange considering we didn't before

**Comment by AjKundnani** [comment]
> So am I reading this issue as 'wont fix' by azure-cli team? This is absurd.

@sdemura - Refer to #31234

**Comment by yongboyang** [comment]
It's a severe issue that blocks customers to deploy VMs with standard security type.

**Comment by codethief** [comment]
We're having the same issue.

> You can self-register the feature flag on subscription using PowerShell or CLI. Refer to [Set up preview features in Azure subscription](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/preview-features)

Unfortunately, we can't *really* self-register, at least not in the literal sense of the word. When trying to do so we get

```
Feature request pending approval
Registration request for feature 'Compute Profiles' was successfully submitted. Request pending approval from Microsoft owning service.
```

**Comment by AjKundnani** [comment]
> Unfortunately, we can't _really_ self-register, at least not in the literal sense of the word. When trying to do so we get
> 
> ```
> Feature request pending approval
> Registration request for feature 'Compute Profiles' was successfully submitted. Request pending approval from Microsoft owning service.
> ```

@codethief - What is the command used to submit registration.

**Comment by codethief** [comment]
@AjKundnani I used the Azure Portal to activate (request activation of) the `Microsoft.Compute` Preview Feature, as described in the link you shared in https://github.com/Azure/azure-cli/issues/31191#issuecomment-2784205683.

**Comment by AjKundnani** [comment]
> [@AjKundnani](https://github.com/AjKundnani) I used the Azure Portal to activate (request activation of) the `Microsoft.Compute` Preview Feature, as described in the link you shared in [#31191 (comment)](https://github.com/Azure/azure-cli/issues/31191#issuecomment-2784205683).

@codethief, please try registering using PowerShell or CLI.

set your subscription then run the below commands

```
az feature register --name UseStandardSecurityType --namespace Microsoft.Compute
az feature show --name UseStandardSecurityType --namespace Microsoft.Compute
```

**Comment by codethief** [comment]
@AjKundnani Thanks, I'll give this a shot tomorrow!

**Comment by codethief** [comment]
@AjKundnani Thanks, the azure-cli commands did the trick!

```
$ az feature register --name UseStandardSecurityType --namespace Microsoft.Compute
{
  "id": "/subscriptions/<subscription id>/providers/Microsoft.Features/providers/Microsoft.Compute/features/UseStandardSecurityType",
  "name": "Microsoft.Compute/UseStandardSecurityType",
  "properties": {
    "state": "Registering"
  },
  "type": "Microsoft.Features/providers/features"
}

$ az feature show --name UseStandardSecurityType --namespace Microsoft.Compute

{
  "id": "/subscriptions/<subscription id>/providers/Microsoft.Features/providers/Microsoft.Compute/features/UseStandardSecurityType",
  "name": "Microsoft.Compute/UseStandardSecurityType",
  "properties": {
    "state": "Registering"
  },
  "type": "Microsoft.Features/providers/features"
}
```

A few minutes later…

```
$ az feature show --name UseStandardSecurityType --namespace Microsoft.Compute
{
  "id": "/subscriptions/<subscription id>/providers/Microsoft.Features/providers/Microsoft.Compute/features/UseStandardSecurityType",
  "name": "Microsoft.Compute/UseStandardSecurityType",
  "properties": {
    "state": "Registered" <----------------------------------------------------------
  },
  "type": "Microsoft.Features/providers/features"
}
```

**Comment by cuongtnh** [comment]
I have the same issue, and downgrading to 2.70.0 works for me.

**Comment by surajssd** [comment]
@codethief thanks, this worked for me:

```bash
az feature register --name UseStandardSecurityType --namespace Microsoft.Compute
while true; do az feature show --name UseStandardSecurityType --namespace Microsoft.Compute; date; sleep 15; done
```

**Comment by AjKundnani** [comment]
The issue is resolved with [CLI v2.72.0](https://learn.microsoft.com/cli/azure/release-notes-azure-cli#compute).

Please note you need not specify `--security-type=Standard` for all deployments, it's only required for Gen2 VM/VMSS deployments using PIR/Marketplace images when you need to bypass [Trusted launch default in CLI](https://techcommunity.microsoft.com/blog/azurecompute/breaking-change-for-vm--vmss-powershellcli-customers/3937037)

i.e., you need not specify `--security-type=Standard` if you're using any of the following for deployment:
- Gen1 image
- Azure compute gallery image
- Managed image
- VM size not supported with Trusted launch.

@matt-boris - As author of this issue, request to validate the fix in v2.72.0 and close this thread if issue is resolved. Please unregister `UseStandardSecurityType` AFEC for end to end testing.

**Comment by AjKundnani** [comment]
@matt-boris - gentle reminder.

**Comment by matt-boris** [comment]
@AjKundnani

After running the following:

```bash
$ az feature unregister --name UseStandardSecurityType --namespace Microsoft.Compute
Once the feature 'UseStandardSecurityType' is unregistered, invoking 'az provider register -n Microsoft.Compute' is required to get the change propagated
{
  "id": "/subscriptions/***/providers/Microsoft.Features/providers/Microsoft.Compute/features/UseStandardSecurityType",
  "name": "Microsoft.Compute/UseStandardSecurityType",
  "properties": {
    "state": "Unregistering"
  },
  "type": "Microsoft.Features/providers/features"
}

$ az feature show --name UseStandardSecurityType --namespace Microsoft.Compute                                     
{
  "id": "/subscriptions/***/providers/Microsoft.Features/providers/Microsoft.Compute/features/UseStandardSecurityType",
  "name": "Microsoft.Compute/UseStandardSecurityType",
  "properties": {
    "state": "Unregistered"
  },
  "type": "Microsoft.Features/providers/features"
}
```

I tried creating a VM with standard security type with no success...

```bash
$ az vm create --name="mboris-test" --image="MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition:latest" --resource-group="<rg name>" --computer-name="ImageBuilder" --os-disk-delete-option=Delete --data-disk-delete-option=Delete --nic-delete-option=Delete --nsg-rule=NONE --license-type="Windows_Server" --accept-term --location="eastus" --size="Standard_F32s_v2" --security-type="Standard" --admin-username="<user>" --admin-password="<pass>"
{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/***/resourceGroups/<rg name>/providers/Microsoft.Resources/deployments/vm_deploy_***","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."}]}}
```

Environment:

```bash
$ az --version
azure-cli                         2.72.0

core                              2.72.0
telemetry                          1.1.0

Extensions:
image-copy-extension              0.2.13

Dependencies:
msal                              1.32.3
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.72.0/libexec/bin/python'
Config directory '/Users/mboris/.azure'
Extensions directory '/Users/mboris/.azure/cliextensions'

Python (Darwin) 3.12.10 (main, Apr  8 2025, 11:35:47) [Clang 16.0.0 (clang-1600.0.26.6)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by matt-boris** [comment]
I thought this whole issue was about giving the user the ability to bypass any default that Azure decided on if they specified `--security-type="Standard"`.

I've no need to use/test any other cases, as I figured the patch in the latest CLI version was to accept the user input bypassing Azure's default behavior, apparently not.

This was quite a disruptive, breaking change that I'll only consider fixed at this point because the docs were at least updated to note the feature flag requirement.

**Comment by AjKundnani** [comment]
@matt-boris - We're working towards removing the feature flag dependency in backend which will fix it for CLI as well in future. Will update the docs accordingly once the dependency is removed.

**Comment by RSwarnkar** [comment]
Any update guys? I see still issue exists, Azure PWSH is also impacted : https://stackoverflow.com/questions/79640272/problem-with-security-type-in-azure-powershell-virtual-machine

**Comment by yanzhudd** [comment]
> Any update guys? I see still issue exists, Azure PWSH is also impacted : https://stackoverflow.com/questions/79640272/problem-with-security-type-in-azure-powershell-virtual-machine

Please upgrade the Azure CLI to the latest version.

**Comment by arsdragonfly** [comment]
> [@matt-boris](https://github.com/matt-boris) - We're working towards removing the feature flag dependency in backend which will fix it for CLI as well in future. Will update the docs accordingly once the dependency is removed.

What the actual heck is going on with this CRP craziness? Your [announcement](https://techcommunity.microsoft.com/blog/azurecompute/breaking-change-for-vm--vmss-powershellcli-customers/3937037) explicitly said that "The PS & CLI client tools will not override inputs provided by you in deployment commands", yet the input is straight up rejected and caused breaking change. WTF?

**Comment by arsdragonfly** [comment]
> [@matt-boris](https://github.com/matt-boris) - We're working towards removing the feature flag dependency in backend which will fix it for CLI as well in future. Will update the docs accordingly once the dependency is removed.

btw the SIG image definition that I'm trying to create VMSS off of - it doesn't even support security type other than Standard. Double check your logic please.

**Comment by AjKundnani** [comment]
> btw the SIG image definition that I'm trying to create VMSS off of - it doesn't even support security type other than Standard. Double check your logic please.

@arsdragonfly - Please refer to https://github.com/Azure/azure-cli/issues/31191#issuecomment-2855431109.
The issue is resolved with CLI v2.72.0, please ensure you're using same or above.

**Comment by arsdragonfly** [comment]
@AjKundnani nope it totally isn't, something is still wrong with Azure CLI 2.74.0, and based on what you described previously, I think CRP has shipped a completely broken "security" feature that breaks standard VM creation from standard SIG image (which I'm currently working around by setting the AFEC flag).
```
/usr/bin/az account set --subscription d71c7216-6409-45f8-be15-35cf57b8527c
/usr/bin/bash /mnt/vss/_work/1/s/build_cluster.sh
azure-cli                         2.74.0

core                              2.74.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1

Dependencies:
msal                              1.32.3
azure-mgmt-resource               23.3.0

Python location '/opt/az/bin/python3'
Config directory '/home/cloudtest/.azure'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.12.10 (main, May 27 2025, 09:12:38) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
##[debug]Headnode name : headnode-1750894779
##[debug]Image : /subscriptions/d2c9544f-4329-4642-b73d-020e7fef844f/resourceGroups/azhpc-images-rg/providers/Microsoft.Compute/galleries/AzHPCImageReleaseCandidates/images/AzureLinuxHPC-3.0-gen2/versions/2025.0623.0
Creating headnode-1750894779 VM of /subscriptions/d2c9544f-4329-4642-b73d-020e7fef844f/resourceGroups/azhpc-images-rg/providers/Microsoft.Compute/galleries/AzHPCImageReleaseCandidates/images/AzureLinuxHPC-3.0-gen2/versions/2025.0623.0
az vm create 		--name headnode-1750894779 		--resource-group hpc-image-validation-9c8f08-rg 		--accelerated-networking False 		--admin-username hpcuser 		--generate-ssh-keys 		--size Standard_D8s_v5 		--subnet /subscriptions/d71c7216-6409-45f8-be15-35cf57b8527c/resourceGroups/1ES-peered-vnets/providers/Microsoft.Network/virtualNetworks/southcentralus-vnet/subnets/default 		--image /subscriptions/d2c9544f-4329-4642-b73d-020e7fef844f/resourceGroups/azhpc-images-rg/providers/Microsoft.Compute/galleries/AzHPCImageReleaseCandidates/images/AzureLinuxHPC-3.0-gen2/versions/2025.0623.0 		--assign-identity /subscriptions/d71c7216-6409-45f8-be15-35cf57b8527c/resourcegroups/1ES-hosted-pool/providers/Microsoft.ManagedIdentity/userAssignedIdentities/GHRMI 		--location southcentralus 		--security-type Standard 		--tags AzSecPackAutoConfigReady=true 		--nsg nsg

##[error]WARNING: The default value of '--size' will be changed to 'Standard_D2s_v5' from 'Standard_DS1_v2' in a future release.
WARNING: SSH key files '/home/cloudtest/.ssh/id_rsa' and '/home/cloudtest/.ssh/id_rsa.pub' have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage, back up your keys to a safe location.
WARNING: Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch.
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/d71c7216-6409-45f8-be15-35cf57b8527c/resourceGroups/hpc-image-validation-9c8f08-rg/providers/Microsoft.Resources/deployments/vm_deploy_syFHSy417W5u5FNb2vn3FFKz1lYKC0AN","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.securityType","message":"The value of parameter securityProfile.securityType is invalid."}]}}

##[error]Script failed with exit code: 1
```

**Comment by AjKundnani** [comment]
> `az vm create 		--name headnode-1750894779 		--resource-group hpc-image-validation-9c8f08-rg 		--accelerated-networking False 		--admin-username hpcuser 		--generate-ssh-keys 		--size Standard_D8s_v5 		--subnet /subscriptions/d71c7216-6409-45f8-be15-35cf57b8527c/resourceGroups/1ES-peered-vnets/providers/Microsoft.Network/virtualNetworks/southcentralus-vnet/subnets/default 		--image /subscriptions/d2c9544f-4329-4642-b73d-020e7fef844f/resourceGroups/azhpc-images-rg/providers/Microsoft.Compute/galleries/AzHPCImageReleaseCandidates/images/AzureLinuxHPC-3.0-gen2/versions/2025.0623.0 		--assign-identity /subscriptions/d71c7216-6409-45f8-be15-35cf57b8527c/resourcegroups/1ES-hosted-pool/providers/Microsoft.ManagedIdentity/userAssignedIdentities/GHRMI 		--location southcentralus 		--security-type Standard 		--tags AzSecPackAutoConfigReady=true 		--nsg nsg`

@arsdragonfly - You need not specify `--security-type = Standard` explicitly in above command, as called out in https://github.com/Azure/azure-cli/issues/31191#issuecomment-2855431109

**Comment by arsdragonfly** [comment]
> > `az vm create 		--name headnode-1750894779 		--resource-group hpc-image-validation-9c8f08-rg 		--accelerated-networking False 		--admin-username hpcuser 		--generate-ssh-keys 		--size Standard_D8s_v5 		--subnet /subscriptions/d71c7216-6409-45f8-be15-35cf57b8527c/resourceGroups/1ES-peered-vnets/providers/Microsoft.Network/virtualNetworks/southcentralus-vnet/subnets/default 		--image /subscriptions/d2c9544f-4329-4642-b73d-020e7fef844f/resourceGroups/azhpc-images-rg/providers/Microsoft.Compute/galleries/AzHPCImageReleaseCandidates/images/AzureLinuxHPC-3.0-gen2/versions/2025.0623.0 		--assign-identity /subscriptions/d71c7216-6409-45f8-be15-35cf57b8527c/resourcegroups/1ES-hosted-pool/providers/Microsoft.ManagedIdentity/userAssignedIdentities/GHRMI 		--location southcentralus 		--security-type Standard 		--tags AzSecPackAutoConfigReady=true 		--nsg nsg`
> 
> [@arsdragonfly](https://github.com/arsdragonfly) - You need not specify `--security-type = Standard` explicitly in above command, as called out in [#31191 (comment)](https://github.com/Azure/azure-cli/issues/31191#issuecomment-2855431109)

WHY MUST I NOT USE `--security-type Standard`? This was totally working before and suddenly you implemented some bullshit logic that is breaking this without giving me a good reason. You are making it sound like specifying the security type explicitly all the time is some sort of unintended use case, which is complete lunacy. Please reopen this issue so that we can track the fix for this broken behavior.

**Comment by ChawnLimited** [comment]
Same issue with powershell
az.compute 8.2.0 if fine and can create a standard VM no issue
it broke when i updated to 9.2.0, but the issue could have surfaced between 8.2.0-9.2.0
strangely new-azvmss is not affected by this change - just VMs

I've tried -securitytype None
just because AZ-GalleryImagedefinitions don't accept Standard - has to be none
but it didn't help here

https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azvmconfig?view=azps-14.2.0
and
https://learn.microsoft.com/en-us/powershell/module/az.compute/set-azvmsecurityprofile?view=azps-14.2.0

both fail with 9.2+ but the documentation stills suggest it should work

I've wasted 5 hours on this. It's friday and the pub is open. Thanks M$.

**Comment by ChawnLimited** [comment]
after more playing, az.compute 9.0 does support -securitytype standard
az.compute 9.0 is currently listed as 'current version'
https://www.powershellgallery.com/packages/Az.Compute/9.0.0

when you successfully create the VM, it simply does not have a securityprofile indicating standard

Using the latest az.compute, i tried creating a vm with a no security profile but azure just seems to want to set TrustedLaunch securityprofile by default - This default did change from standard a while back for gen2 vms - https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch

this however worked with az.compute 10.1.0 - kick yourself moment
**$VirtualMachine = Set-AzVMSecurityProfile -VM $VirtualMachine -SecurityType "";**

this didn't work with 10.1
**$VirtualMachine = New-AzVMConfig -VMName stvda -VMSize Standard_B2s -SecurityType "";**
it throws
New-AzVMConfig : Cannot validate argument on parameter 'SecurityType'. The argument "" does not belong to the set
"TrustedLaunch,ConfidentialVM,Standard" specified by the ValidateSet attribute. Supply an argument that is in the set
and then try the command again.

perhaps documentation should be update to remove securitytype from new-azvmconfig and advised to use set-azvmsecurityprofile

another workaround is to run
**Install-Module -Name az.compute -RequiredVersion 9.0.0
Import-Module -Name az.compute -MaximumVersion 9.0.0**

MS documentation still has not been updated to reflect the default securitytype
https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azvm?view=azps-14.2.0#-securitytype
https://learn.microsoft.com/en-us/powershell/module/az.compute/set-azvmsecurityprofile?view=azps-14.2.0#-securitytype
