### ISSUE TITLE
x-ms-client-request-id causes Interactive Mode / ScenarioTest scenarios to fail

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3647]
Consider the following commands:
```
az network lb create -g myrg -n lb
az network lb inbound-nat-rule create -g myrg --lb-name lb -n rule1 --frontend-port 100 --backend-port 100 --protocol tcp
az network lb inbound-nat-rule create -g myrg --lb-name lb -n rule2 --frontend-port 200 --backend-port 200 --protocol tcp
```

This creates a load balancer with two inbound NAT rules. This scenario runs just fine if you use the CLI normally, and it runs fine in the current scenario test (which uses the `ResourceGroupVCRTestBase` class).

However, if you run these commands in interactive mode, or you run it as part of a `ScenarioTest` based test, the call to create the second rule will fail, stating that the second rule does not exist. Examination via the portal confirms this as well.

- [X] Remove x-ms-client-id from LiveTest and ScenarioTest base (PR #3655)
- [x] Generate new x-ms-client-id in `az interactive` for each new command (PR #3435)

cc/ @troydai, @oakeyc

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.7+dev)

acr (2.0.5+dev)
acs (2.0.7+dev)
appservice (0.1.7+dev)
batch (3.0.0+dev)
billing (0.1.0+dev)
cdn (0.0.3+dev)
cloud (2.0.3+dev)
cognitiveservices (0.1.3+dev)
component (2.0.5+dev)
configure (2.0.7+dev)
consumption (0.1.0+dev)
core (2.0.7+dev)
cosmosdb (0.1.7+dev)
dla (0.0.7+dev)
dls (0.0.7+dev)
feedback (2.0.3+dev)
find (0.2.3+dev)
interactive (0.3.3+dev)
iot (0.1.6+dev)
keyvault (2.0.5+dev)
lab (0.0.5+dev)
monitor (0.0.5+dev)
network (2.0.7+dev)
nspkg (3.0.0+dev)
profile (2.0.5+dev)
rdbms (0.0.2+dev)
redis (0.2.4+dev)
resource (2.0.7+dev)
role (2.0.5+dev)
sf (1.0.2+dev)
sql (2.0.4+dev)
storage (2.0.7+dev)
taskhelp (0.1.2+dev)
testsdk (0.1.0+dev)
utility-automation (0.1.1)
vm (2.0.7+dev)

Python (Windows) 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]

**OS Version:** What OS and version are you using?  
Answer here: Win10 CU

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by tjprescott** [comment]
I believe I have discovered why this occurs.  When I run these three commands normally, each command has a unique request ID (which appears in multiple requests).  However, when I run them inside `az interactive` the *same request ID is used for all requests for all commands*.  I believe that, since I am making a call with the same URI using the same request ID, the server is essentially returning me a cached result--that is, the result of the original call.

**Comment by tjprescott** [comment]
Talk about reinventing the wheel 🤢 
See #456.  cc/ @troydai  @oakeyc since this issue affects both the ScenarioTest base and `az interactive`

**Comment by troydai** [comment]
@tjprescott the issue should be fixed in https://github.com/Azure/azure-cli/commit/89844da9cd3963c4bcbb89655d948519337af843. I'll close this issue for now and let me know if it still blocks you from updating the tests.

**Comment by tjprescott** [comment]
The issue isn't resolved fully until #3435 is merged. I'll leave this open until then.

**Comment by troydai** [comment]
ok

**Comment by troydai** [comment]
@tjprescott I believe this issue can be closed. The pull request #3435 doesn't involve any changes related to the client side request anymore. The change I made in 89844da can guarantee the uniqueness of the client side request ID when `Application.execute` is executed.
