### ISSUE TITLE
[Storage] --if-unmodified-since The condition specified using HTTP conditional header(s) is not met

### ISSUE THREAD

**Issue by luisamador** [Azure/azure-cli#5286]
I have a storage account with a storage container called "backups".

when the storage container is empty (no blob backup files in it) this command works:
```
az storage blob delete-batch --source backups --if-unmodified-since `date -d "1 month ago" '+%Y-%m-%dT%H:%MZ'`
[]
```

the command above deletes the files that were not modified since the last month, and it works as expected.

if I upload one blob backup file into the storage container and run the same command, it errors:
```
az storage blob delete-batch --source backups --if-unmodified-since `date -d "1 month ago" '+%Y-%m-%dT%H:%MZ'`
The condition specified using HTTP conditional header(s) is not met.
<?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>**The condition specified using HTTP conditional header(s) is not met.**
RequestId:ce18a9b3-001e-0117-78ab-8bea95000000
Time:2018-01-12T13:45:08.3718745Z</Message></Error>
```

Another example:

I have uploaded two blob files into the same storage container (now the storage container is not empty, it contains the two blob backup files)

```
az storage blob delete-batch --source backups --if-unmodified-since `date -d "2 minutes ago" '+%Y-%m-%dT%H:%MZ'`
The condition specified using HTTP conditional header(s) is not met.
<?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>**The condition specified using HTTP conditional header(s) is not met.**
```

It errors but it has actually deleted one of the backup files that I uploaded 4 minutes ago.

It would be great to fix that error message since the delete operation is actually working properly. Thanks

**Comment by elibarzilay** [comment]
Sidenote for random readers: you should use a `-u` flag for `date` to make it show UTC times.  (I'm guessing that you happened to use a machine that is on UTC time anyway.)

**Comment by arbaiti** [comment]
Hi luisamador,
Did you find a fix to this issue bacause i'm facing the same.
Regards,

**Comment by rupert654** [comment]
I've got this problem and can't tell from this ticket if this fix has been released yet.

What milestone did #5702  go into?

**Comment by williexu** [comment]
Milestone 33.
It was published yesterday, ver 2.0.29; sorry for the confusion.

**Comment by its-vincesanity** [comment]
Now it's 2021, and I got the same Problem as described above. So it's not fixed or is the example "just" not working?

**Comment by justinmchase** [comment]
This is happening on the delete also.
