### ISSUE TITLE
[Stack] Authority url broken for CLI

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#6457]
**Describe the bug**
While trying to login to the stack cloud using "az login" the following error occurs:
("The authority url must be of the format https://login.microsoftonline.com/your_tenant")

**To Reproduce**
az login -u <username> -p <password> --tenant <tenantid>

**Expected behavior**
Expected to login to cloud.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
edge build
Bash on Windows

**Additional context**
22616 : 2018-05-30 04:29:15,196 : DEBUG : cli.knack.cli : Command arguments: ['login', '-u', '********@msazurestack.onmicrosoft.com', '-p', '********', '--tenant', '**********************']

22616 : 2018-05-30 04:29:16,118 : ERROR : cli.azure.cli.core.util : The authority url must be of the format https://login.microsoftonline.com/your_tenant
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 336, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Python35\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 310, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 171, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Python35\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 131, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\_profile.py", line 168, in find_subscriptions_on_login
    username, password, tenant, self._ad_resource_uri)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\_profile.py", line 660, in find_from_user_account
    context = self._create_auth_context(tenant)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\_profile.py", line 705, in _create_auth_context
    return self._auth_context_factory(self.cli_ctx, tenant, token_cache)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\_profile.py", line 76, in _authentication_context_factory
    return adal.AuthenticationContext(authority_url, cache=cache, api_version=None, validate_authority=(not is_adfs))
  File "C:\Program Files (x86)\Python35\lib\site-packages\adal\authentication_context.py", line 88, in __init__
    self.authority = Authority(authority, validate_authority is None or validate_authority)
  File "C:\Program Files (x86)\Python35\lib\site-packages\adal\authority.py", line 49, in __init__
    self._validate_authority_url()
  File "C:\Program Files (x86)\Python35\lib\site-packages\adal\authority.py", line 74, in _validate_authority_url
    raise ValueError("The authority url must be of the format https://login.microsoftonline.com/your_tenant")
ValueError: The authority url must be of the format https://login.microsoftonline.com/your_tenant

**Comment by yugangw-msft** [comment]
#6458 should fix this

**Comment by sebastianjungels** [comment]
Hi, I just installed version 1.1.0 and am still getting the error. Can you please advice what I need to do?

**Comment by viananth** [comment]
@sebastianjungels can you pls update to latest version of CLI? This should be fixed in latest.
