### ISSUE TITLE
"Az Storage Blob Download .. -Max-Connections 1" file handling needs improvement.

### ISSUE THREAD

**Issue by v-tisheg** [Azure/azure-cli#6608]
Currently the "AZ Storage Blob Download ... --Max-connections 1" arguments will only attempt to pull the larger files in one peice.  When the file it is trying to download is larger than the memory on the workstation running the task the process consumes the workstation's entire memory and swap file then fails.

Looking to get the Azure CLI Storage blob download command structure to handle "--Max-Connections 1" like it does when the max connections is set to 2 or more.  That is to handle files larger than the memory of the workstation by breaking the file into multiple peices and make multiple requests to get the full file to download.

The Customer needs to download the blob to a named pipe so they must be able to use a single download connection to prevent seek operations on the pipe.

**Comment by williexu** [comment]
The CLI relies on the [storage sdk](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/baseblobservice.py#L1704) to download blobs.

Looping in storage team guys @seguler, @zezha-msft to answer the question regarding support via sdk.

**Comment by zezha-msft** [comment]
Hi @v-tisheg and @williexu, I took a look at the code, and it seems to me that this is a design flaw in the SDK and should be fixed.

To be more specific, the SDK currently does not address the scenario that @v-tisheg has described, where a large file needs to be downloaded serially to a non-seekable stream.

@williexu Please create an issue in the SDK's repo, so that we can track this work. Thanks!

**Comment by williexu** [comment]
Done: https://github.com/Azure/azure-storage-python/issues/464

**Comment by v-tisheg** [comment]
3116c4c9-8997-451c-a249-5cd093312804

**Comment by v-tisheg** [comment]
Has this been published?
Does the customer need to download the cli modules?
The customer tried again this morning and the issue persists

**Comment by zezha-msft** [comment]
No @v-tisheg, this work will be scheduled soon.

**Comment by v-tisheg** [comment]
Hello all,
I was out last week.  has there been any update to this issue yet?

**Comment by williexu** [comment]
@zezha-msft

**Comment by zezha-msft** [comment]
Hi @v-tisheg, the code is in review. I'll update this thread once it's ready to be released.

**Comment by v-tisheg** [comment]
Thank you so much.


Timothy Shegrud

Support Engineer
Cloud & Infrastructure Solutions
Customer Services & Support | Microsoft Corporation
(425) 706-4408; * v-tisheg@microsoft.com<mailto:v-tisheg@microsoft.com> | Hours: Mon - Fri, 7:00am-4:00pm PST
Need help outside of my working hours for a technical issue?
*: AzBackup@microsoft.com<mailto:AzBackup@microsoft.com>

Meeting and exceeding your expectations are my top priorities. We are interested in any feedback you might have about the service you received on this incident.  Please let my Manager, FNU Manjunatha know what you think of the level of service provided, by contacting him via email at v-fnman@microsoft.com<mailto:v-fnman@microsoft.com>.

[cid:image001.png@01D2DECD.52D68C60]    [cid:image002.jpg@01D2DECD.52D68C60]

**Comment by zezha-msft** [comment]
Hi @v-tisheg, the issue has been fixed in version 1.3.1 of the blob package. It is up to the CLI to pick up the new version in their next release. Thanks.
