### ISSUE TITLE
`az webapp create`  doesnt support using a acr image 

### ISSUE THREAD

**Issue by khowling** [Azure/azure-cli#7261]
**Describe the bug**
```az webapp create```  can only create a webapp using a public dockerhub or built in image, it doesnt support passing in registry credentials for a acr image.  

I'm trying to create a webapp based on a image in acr,  but I cannot pass in the registry credentials into the create command. So I need to first create the webapp with a random public container, then run the ```az webapp config container set``` command that accepts registry credentials 

**To Reproduce**
run ```az webapp create --deployment-container-image-name``` no way of passing in registry credentials

**Expected behavior**
I'd like to see consistency between the command line options for ```az webapp create --deployment-container-image-name``` and ```az webapp config container set --docker-custom-image-name``` 

**Environment summary**
Bash on Windows

**Comment by ahmedelnably** [comment]
We have it on our backlog and will update the thread once we finish the work, that's said we don't have an ETA to share right now

**Comment by mcwienczek** [comment]
+1 for this, could be useful for us as well

**Comment by markheath** [comment]
Also, if you have a container that needs certain environment variables set, there is no obvious way to create the webapp with the app settings. you have to first do `az webapp create` and then `az webapp config appsettings set`.

Would be nice to be able to create a new webapp from ACR and with environment variables correctly configured in a single step

**Comment by panchagnula** [comment]
@yiliaomsft & @Nking92  can you look at this request

**Comment by SindreEquinor** [comment]
+1 from me as well. This is really needed.

**Comment by yiliaomsft** [comment]
We're looking into it.

**Comment by panchagnula** [comment]
CC: //@apwestgarth for windows containers

**Comment by WilliamMortlMicrosoft** [comment]
this is needed as soon as possible for Microsoft engagements with other companies (I'm an employee in CSE)

**Comment by btardif** [comment]
@panchagnula and @Nking92 I think this item has enough traction that we need to have some sort of design figure out as well as costing and review where it fits in the backlog.

**Comment by panchagnula** [comment]
@Nking92 is already looking at this along with the container up work he is doing.

**Comment by btardif** [comment]
We are on track for s69

**Comment by panchagnula** [comment]
This has been fixed.

**Comment by tsgenge** [comment]
Using az webapp create using an ACR image still returns "Access is denied. Not authorized. latest". Is this in production now? Even using the Azure CLI shell in the portal (therefore latest) gives the same error.

**Comment by tsgenge** [comment]
> Using az webapp create using an ACR image still returns "Access is denied. Not authorized. latest". Is this in production now? Even using the Azure CLI shell in the portal (therefore latest) gives the same error.

It works today, but in an odd way. I assume it was an outage, though I have switched to linux containers / service plan. I noticed that it still doesn't connect using the ACR option - inspecting the app service created its connecting using a "private repository" connecting using my ACR access tokens.

**Comment by nkemakolam** [comment]
I tried creating a web app for container I used the -i option yet it didn’t give me acr as a default container reg instead it treated my parameter as a private container repo.where as i supplied my acr url and image name to the command.please any idea.??????

**Comment by mjdall** [comment]
@nkemakolam I had this issue when my ACR url didn't start with https://. Setting with https:// registered it as a container registry instead.

**Comment by mjdall** [comment]
> 
> 
> I tried creating a web app for container I used the -i option yet it didn’t give me acr as a default container reg instead it treated my parameter as a private container repo.where as i supplied my acr url and image name to the command.please any idea.??????

 I had this issue when my ACR url didn't start with https://. Setting with https:// registered it as a container registry instead.
