### ISSUE TITLE
Please document default values

### ISSUE THREAD

**Issue by kskvarci** [Azure/azure-cli#7479]
In cases where an optional parameter has set valid values the default value should always be documented. E.G. what is the result if i chose not to include the parameter in my call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-create)
* Content Source: [src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by yungezz** [comment]
hi @kskvarci thanks for reporting the issue, could you pls share specifically which parameters' default value not documented? Then we can add missing one. As you found in CLI code, there're default value property for parameters, eg. https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_params.py#L75 ,default value of `sku` , this default value in code will be automatically build in az cli doc: https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-create as below:
```
--sku
Required. SKU details.

accepted values: premium, standard
default value: standard
```

**Comment by bim-msft** [comment]
@yungezz I've noticed that we do missed some default values, this is an example:
```
az keyvault key create -h

--disabled              : Create key in disabled state.  Allowed values: false, true.
--protection -p      : Specifies the type of key protection.  Allowed values: hsm, software.
```
The default values of `--disabled` and `--protection` are not documented.
This is a tedious work, will work on this when high priority things get done.

**Comment by yungezz** [comment]
hi @bim-msft is the issue resolved now?

**Comment by bim-msft** [comment]
> hi @bim-msft is the issue resolved now?

Hi @yungezz , this is not resolved so far, moved it to S170.

**Comment by RakeshMohanMSFT** [comment]
Default values are updated
