### ISSUE TITLE
postgres server vnet-rule create fails with --subscription <NAME>

### ISSUE THREAD

**Issue by mooninite** [Azure/azure-cli#8491]
**Describe the bug**
Fails: az postgres server vnet-rule create --name foo -g foobar -s foobar-test --subnet foobar-subnet --vnet-name foobar-vnet --subscription foobar

Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/uuid/resourceGroups/foobar/providers/Microsoft.DBforPostgreSQL/servers/foobar-test/virtualNetworkRules/test?api-version=2017-12-01 (Caused by ResponseError('too many 502 error responses',))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/uuid/resourceGroups/foobar/providers/Microsoft.DBforPostgreSQL/servers/foobar-test/virtualNetworkRules/test?api-version=2017-12-01 (Caused by ResponseError('too many 502 error responses',))

Works: az postgres server vnet-rule create --name foo -g foobar -s foobar-test --subnet /subscriptions/uuid/resourceGroups/foobar/providers/Microsoft.Network/virtualNetworks/foobar-vnet/subnets/foobar-subnet --subscription foobar

**To Reproduce**
az postgres server vnet-rule create --name foo -g foobar -s foobar-test --subnet foobar-subnet --vnet-name foobar-vnet --subscription foobar

**Expected behavior**
A new VNET rule.

**Environment summary**
pip install azure-cli

azure-cli (2.0.57)

acr (2.1.13)
acs (2.3.16)
advisor (2.0.0)
ams (0.4.0)
appservice (0.2.12)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.7)
billing (0.2.0)
botservice (0.1.5)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.20)
consumption (0.4.2)
container (0.3.13)
core (2.0.57)
cosmosdb (0.2.7)
dla (0.2.3)
dls (0.1.7)
dms (0.1.2)
eventgrid (0.2.1)
eventhubs (0.3.3)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.3.0)
interactive (0.4.1)
iot (0.3.5)
iotcentral (0.1.5)
keyvault (2.2.10)
kusto (0.1.0)
lab (0.1.5)
maps (0.3.3)
monitor (0.2.9)
network (2.3.1)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.1.3)
rdbms (0.3.6)
redis (0.3.2)
relay (0.1.3)
reservations (0.4.1)
resource (2.1.9)
role (2.3.1)
search (0.1.1)
security (0.1.0)
servicebus (0.3.3)
servicefabric (0.1.12)
signalr (1.0.0)
sql (2.1.8)
sqlvirtualmachine (0.1.0)
storage (2.3.1)
telemetry (1.0.1)
vm (2.2.14)

Python location '/bin/python'
Extensions directory '/var/lib/jenkins/.azure/cliextensions'

Python (Linux) 2.7.5 (default, Sep 12 2018, 05:31:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Additional context**

**Comment by mooninite** [comment]
Perhaps something has changed, but my error has changed. The command with --vnet-name now shows this error:

The client has permission to perform action 'Microsoft.Network/virtualNetworks/subnets/joinViaServiceEndpoint/Action' on scope '/subscriptions/uuid/resourceGroups/foobar/providers/Microsoft.DBforPostgreSQL/servers/foobar-test/virtualNetworkRules/test', however the linked subscription 'foobar' was not found.

**Comment by tjprescott** [comment]
Are you provide --subscription by name or ID?

**Comment by tjprescott** [comment]
I think you issue may be fixed by PR #8484.

**Comment by mooninite** [comment]
I am passing in the subscription name and not the uuid. I will try out the PR and see if it fixes it. Thanks.

**Comment by tjprescott** [comment]
Hi @mooninite yes, this should be fixed in the upcoming release. If you use the subnet ID OR using the subscription GUID it should work. After this release, the name of the subscription will also work.

**Comment by mooninite** [comment]
The 2.0.58 update did not fix this. I'm still seeing this message:

The client has permission to perform action 'Microsoft.Network/virtualNetworks/subnets/joinViaServiceEndpoint/Action' on scope '/subscriptions/uuid/resourceGroups/foobar/providers/Microsoft.DBforPostgreSQL/servers/foobar-test/virtualNetworkRules/test', however the linked subscription 'foobar' was not found.

**Comment by tjprescott** [comment]
That's because it is in the 2.0.59 release.
