### ISSUE TITLE
az container export gives error AttributeError: 'NoneType' object has no attribute 'type'

### ISSUE THREAD

**Issue by eggman314** [Azure/azure-cli#8650]
**Describe the bug**
Exporting container group to yaml with command "az container export --resource-group gruppe --name containergruppe1 --output yaml -f test.yml" raises exception.

**To Reproduce**
Run command above

**Expected behavior**
For container group to be exported to test.yml

**Environment summary**
Tried under both Windows 7 Home Premium SP1 build 7601 (az 2.0.55 installed with MSI, python 3.5, and run in Powershell) and Ubuntu 18.04 (az 2.0.59, python 3.6.5, installed with apt-get and run in bash)

<img width="740" alt="2019-02-27_14-39-52" src="https://user-images.githubusercontent.com/3087751/53496942-616b1a00-3aa3-11e9-81bd-1e3041e5a96e.png">

**Comment by henryroyal** [comment]
Just encountered this in Azure cloud shell with azure-cli version 2.0.59, Python 3.5.2
Was able to reproduce in a git-bash terminal on Win 10 build 1803 using azure-cli version 2.0.56, Python 3.5.2

**Comment by dlepow** [comment]
I repro'd this exact error testing some documentation using CLI version 2.0.59 in Cloud Shell, also local Win 10.
Created container group using [this YAML](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-multi-container-yaml#configure-the-yaml-file).
Tried export:
```
az container export -g myresourcegroup --name myContainerGroup --file export-aci.yaml --debug
```

**Comment by tjprescott** [comment]
I believe this is fixed in 2.0.60.

**Comment by basxib** [comment]
I'm still experiencing this error when trying to create a container using a yaml file

**Comment by SaurabhSharma-MSFT** [comment]
@eggman314 Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.
