### ISSUE TITLE
az acr helm push with service principal has stopped working

### ISSUE THREAD

**Issue by simonness** [Azure/azure-cli#9010]
We have Azure DevOps Build Pipelines with the steps:

`az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalPassword) -t $(tenantId)`

`az acr helm push -n $(registryName) something.tgz`

Today we're suddenly getting the following error from the `az acr helm push` command:

**`ERROR: Error: authentication required. Correlation ID: 753e02ea-9dd7-400e-878c-2647a66e5006.`**

The az login command still succeeds and the service principal still has the role `AcrPush` on the registry.  I can't see anything that may have changed on our side, could there be a change in behaviour in the CLI?

I can reproduce this locally with the azure cli (2.0.61) with acr (2.2.3) installed.

Interestingly a `az acr helm show` works with the service principal. The `az acr helm push` command works after login with my user using `az login`, so is only an issue when using the service principal.

A brand new service principal created using the following steps can not do `az acr helm push`:

`$acrId = az acr show -n $registryName -g $resourceGroup --query "id" -o tsv`
`az ad sp create-for-rbac -n "sp-test" --scopes $acrId --role acrpush --query password -o tsv`
`az ad sp show --id http://sp-test --query appId -o tsv`

**Comment by yuwaMSFT2** [comment]
for now, can you assign both AcrPush and AcrDelete roles to the user as a workaround?

**Comment by mathieu-benoit** [comment]
It looks like you could now do `az acr helm push -n $(registryName) -u $(registryLogin) -p $(registryPassword) something.tgz`. See `-u` and `-p` part of this `az acr push` command. And you don't need anymore the previous task `az login`.

**Comment by simonness** [comment]
Thanks very much @yuwaMSFT2 @mathieu-benoit.  To confirm adding the `AcrDelete` role to the service principal also worked for me.

**Comment by schdief** [comment]
> It looks like you could now do `az acr helm push -n $(registryName) -u $(registryLogin) -p $(registryPassword) something.tgz`. See `-u` and `-p` part of this `az acr push` command. And you don't need anymore the previous task `az login`.

@mathieu-benoit thanks a lot for this advice, works like a charm - this issue made me crazy yesterday :) maybe you can update [your phippyandfriends guide](https://cloudblogs.microsoft.com/opensource/2018/11/27/tutorial-azure-devops-setup-cicd-pipeline-kubernetes-docker-helm/) so others won't run in the same problem?
@simonness thanks for opening the issue

**Comment by AndyMoore** [comment]
> for now, can you assign both AcrPush and AcrDelete roles to the user as a workaround?

this doesnt seem to work anymore (as of today). looks like

> az acr helm push -n $(registryName) -u $(registryLogin) -p $(registryPassword) something.tgz

does work though

**Comment by yuwaMSFT2** [comment]
@andymoore AcrPush+AcrDelete should still work. Can you try to az login again before doing docker command (az login gets an token which is only valid for one hour [)](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication).

If you still have issue, could you please send the follow information to acrsup@microsoft.com so that we can do further investigation? Thanks!

1. registry name
2. helm chart name and version you were pushing
3. approximate time frame

**Comment by AndyMoore** [comment]
this was using an azure devops pipeline, and so i added the az login step directly before i ran the az acr helm push

i tried it locally as well which also failed. the time frame was about 10 minutes before i commented above

i'll email some details shortly

**Comment by yugangw-msft** [comment]
@AndyMoore, we assume this issue has been addressed and you are unblocked, please feel free to reactivate otherwise

**Comment by luanbon** [comment]
I believe that the bug persist, i am trying this:

```
az acr helm push --name $(registryName) -u $(registryUsername) -p $(registryPassword) $(build.artifactStagingDirectory)/$(projectName)-$(GitVersion.SemVer).tgz
```
ERROR: Error: authentication required. Correlation ID: 8e639743-b3ae-4aa2-86fe-bdff31d82894.`

I tried with az login before push and occurred the same error.
