### ISSUE TITLE
webap: 'az appservice plan create' fails to create service plan with Linux OS and Free SKU

### ISSUE THREAD

**Issue by Maissae** [Azure/azure-cli#9462]
## Describe the bug
Using command `az appservice plan create` fails to create service plan with Linux operating system and free SKU in probably any region (I tried West Europe, North Europe and Central US), it returns follwing error:
```
Free SKU not supported in region "westeurope". Run the command with --location to use a supported region. See az appservice list-locations --sku F1 --linux-workers-enabled to see the list of supported regions
```
However listing the supported regions with following command `az appservice list-locations --sku F1 --linux-workers-enabled` shows that the West Europe region is supported along with other regions I tried.

## To Reproduce
I used the commands with following options, just replace `<spname>` with name of the Service Plan and `<rgname>` with Resouce Group name:

`az appservice plan create --name <spname> --resource-group <rgname> --location "West Europe" --sku F1 --is-linux` 

`az appservice plan create --name <spname> --resource-group <rgname> --location "North Europe" --sku F1 --is-linux` 

`az appservice plan create --name <spname> --resource-group <rgname> --location "Central US" --sku F1 --is-linux` 

## Expected behavior
Command should be able to create a service plan in specified region with free sku.

## Environment summary
- Powershell Core 6.2.0
- Azure Cli 2.0.64
- `az appservice` 0.2.19

## Additional context
I also tried to create App Service Plan with Linux OS and West Europe region with different SKU such as `B1` and the command went through fine, creating the service, however `F1` didn't worked. I also tried using `--sku FREE` but it didn't worked as well. Using "westeurope" as location or "West Europe" seems to have no difference. Creating Service Plan with Linux and Free SKU via Azure Portal works without any issues. Beside those I also tried changing region (Central US and North Europe) but it also threw exact same error that Free SKU is not supported in specified region. 

I also attach log with the command: [log](https://github.com/Azure/azure-cli/files/3211699/2019-05-23.11-40-21.appservice_plan_create.22548.log)

**Comment by yugangw-msft** [comment]
@panchagnula, please clarify

**Comment by panchagnula** [comment]
only a single FREE SKU ASP is supported for each sub -> if you had one already created via portal then this will fail in CLI & vice-versa if this is not the case. please run the command with --debug & share the error reported. thank you.

**Comment by Maissae** [comment]
That is interesting because I run several free app service plans on my current subscription (Azure For Students), I don't use them much but they exist. Even if I already had few I could still create another one via Portal but not via CLI. Regardless of that, I tried running that command on clean, different subscription with no resources at all, it still failed to create service plan with exact same error message as before. I also ran with a `--debug` so here's the output it produced: [errorlog.txt](https://github.com/Azure/azure-cli/files/3215532/errorlog.txt)

**Comment by panchagnula** [comment]
@Maissae  thanks for the update - i will take a look.

**Comment by panchagnula** [comment]
@Maissae this is due to a regression on the validation API on our end with specific to Linux where the validation API fails when the location name is not the Geo region format i.e  ("West Europe" -> works in the validation API & not "westeurope"). However, CLI --location always converts the georegion('west europe')  format to location name format ('westeurope'). We do have a fix rolling out for this on Tue, the deployment got pushed out due to the long weekend here in USA. Sorry for the inconvenience.

**Comment by Maissae** [comment]
Alright awesome, thanks for the info!

**Comment by panchagnula** [comment]
@Maissae  this should now be fixed.

**Comment by Maissae** [comment]
I still have issues running the command, same error message. Do I need to update anything?

**Comment by TheBlueSky** [comment]
I'm also getting the same error while using the latest version of Azure CLI.

**Comment by softeering** [comment]
I'm having the exact same issue and can't automate the resource creation except by using B1 sku instead of F1. I confirm it works from the Azure portal.

**Comment by panchagnula** [comment]
Adding this to this sprint milestone to check if this still repros & work on a fix if needed.

**Comment by panchagnula** [comment]
@TheBlueSky / @softeering / @Maissae are you able to still repro this? I tried it on our end & wasn't able to with CLI. If you still do can you share the details on if you are trying the create in a certain region? Thank you.

**Comment by TheBlueSky** [comment]
v2.0.66 of the CLI had the issue in my case, but the latest version (v2.0.69) does not have the issue; i.e., it works.

**Comment by panchagnula** [comment]
Closing this since we got a confirmation that it works with v 2.0,69

**Comment by softeering** [comment]
I confirm too, it now works with version 2.0.69.
Also, the error message when trying to create an additional FREE app service plan is clear 
```
Cannot create a Linux app service plan because there is a limit of 1 free tier linux app service plan per subscription
```

Thanks for the fix

**Comment by piclez** [comment]
I'm having this issue with version "2.0.77".

```
az appservice plan create --n name --g group --is-linux --sku F1 --location westus
```
The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

I tried with eastus2 as well.
