### ISSUE TITLE
az storage blob sync: path NoneType

### ISSUE THREAD

**Issue by dbaio** [Azure/azure-cli#9576]
The path is valid, it seems the arguments are not read...

**Command Name**
`az storage blob sync`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 609, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 240, in new_handler
    handler(ex)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 183, in handler
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 588, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 297, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 461, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/azcopy.py", line 36, in storage_blob_sync
    azcopy = _azcopy_blob_client(cmd, client)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/azcopy.py", line 54, in _azcopy_blob_client
    return AzCopy(creds=blob_client_auth_for_azcopy(cmd, client))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/storage/azcopy/util.py", line 34, in __init__
    if not os.path.isfile(install_location):
  File "/usr/local/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob sync -c {} --account-name {} -s {} -d {}`

## Environment Summary
```
FreeBSD-13.0-CURRENT-amd64-64bit-ELF
Python 3.6.8
Shell: bash

azure-cli 2.0.66

Extensions:
interactive 0.4.1

```

**Comment by limingu** [comment]
PR: https://github.com/Azure/azure-cli/pull/9589 should fix this issue.

**Comment by dbaio** [comment]
Actually I'm getting the same error. 
It seems you still don't support `azcopy` on FreeBSD. 😢 
https://github.com/Azure/azure-storage-azcopy/issues/188

https://github.com/limingu/azure-cli/blob/9564b81a92ee8f280fcbc61555571203ca824db0/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/azcopy/util.py#L35-L46

**Comment by Juliehzl** [comment]
@dbaio We have discussed with azcopy team.  Because azcopy team has high-priority work to do, they need some time to release FreeBSD version and we will keep a close watch on this.

**Comment by cemeyer** [comment]
(#9589 is not related to this bug.)

The following small change should address the issue, combined with manually building azcopy:

```
--- azure/cli/command_modules/storage/azcopy/util.py.orig        2019-12-02 13:03:52.425115000 -0800
+++ azure/cli/command_modules/storage/azcopy/util.py     2019-12-02 13:05:51.576481000 -0800
@@ -41,6 +41,8 @@
                 file_url = base_url.format('linux', 'tar.gz')
             elif self.system == 'Darwin':
                 file_url = base_url.format('darwin', 'zip')
+            elif self.system == 'FreeBSD':
+                raise CLIError('Azcopy ({}) binary not available, please build from https://github.com/Azure/azure-storage-azcopy and install in $HOME/bin/azcopy'.format(self.system))
             else:
                 raise CLIError('Azcopy ({}) does not exist.'.format(self.system))
             try:
@@ -163,7 +165,7 @@
         if not home_dir:
             return None
         install_location = os.path.join(home_dir, r'.azcopy\azcopy.exe')
-    elif system in ('Linux', 'Darwin'):
+    elif system in ('Linux', 'Darwin', 'FreeBSD'):
         install_location = os.path.expanduser(os.path.join('~', 'bin/azcopy'))
     else:
         install_location = None
```

The problem is returning `None` for `install_location` above causes an immediate and unintuitive backtrace in the caller (`os.path.isfile(None)` raises an exception because the `isfile` API only accepts strings and Paths).  While the patch above addresses the issue for FreeBSD, it might be better in general to raise an exception here for unrecognized platforms instead of returning `None`.

In addition, I have implemented basic azcopy support for FreeBSD in https://github.com/Azure/azure-storage-azcopy/pull/768 .  It seems like it is at least sufficient to upload a local image to a managed disk.
